import type { Dish } from "./types";

// First-party fixture menu. Controlled demonstration dishes — not tested recipes,
// not costed, not certified for food-service use.

export const DISHES: Dish[] = [
  {
    id: "braise-short-rib",
    name: "Red-wine braise",
    course: "anchor",
    note: "Long oven hold, improves overnight, forgiving on timing.",
    contains: ["meat", "alcohol"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 210,
    burnerMin: 25,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Beef short rib", perGuest: 0.45, unit: "kg", aisle: "protein" },
      { item: "Red wine", perGuest: 0.12, unit: "L", aisle: "drinks" },
      { item: "Onion", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Carrot", perGuest: 0.7, unit: "ea", aisle: "produce" },
      { item: "Tomato paste", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "roast-chicken",
    name: "Tray-roast chicken & lemon",
    course: "anchor",
    note: "Single tray, one oven zone, carves at the table.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "brunch"],
    ovenMin: 75,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 5,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Chicken thighs", perGuest: 0.32, unit: "kg", aisle: "protein" },
      { item: "Lemon", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 12, unit: "ml", aisle: "pantry" },
      { item: "Garlic", perGuest: 1, unit: "clove", aisle: "produce" },
    ],
  },
  {
    id: "baked-pasta",
    name: "Baked pasta, tomato & basil",
    course: "anchor",
    note: "Assembles a day ahead; oven-only finish.",
    contains: ["gluten", "dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 45,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 40,
    ingredients: [
      { item: "Dry pasta", perGuest: 0.11, unit: "kg", aisle: "pantry" },
      { item: "Tinned tomatoes", perGuest: 0.2, unit: "kg", aisle: "pantry" },
      { item: "Mozzarella", perGuest: 60, unit: "g", aisle: "dairy" },
      { item: "Basil", perGuest: 0.1, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "chickpea-tagine",
    name: "Chickpea & squash tagine",
    course: "anchor",
    note: "Stovetop only, plant-forward, holds an hour without damage.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 55,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Chickpeas", perGuest: 0.14, unit: "kg", aisle: "pantry" },
      { item: "Squash", perGuest: 0.25, unit: "kg", aisle: "produce" },
      { item: "Onion", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Ras el hanout", perGuest: 4, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "grill-skewers",
    name: "Grill skewers & charred lemon",
    course: "anchor",
    note: "Outdoor heat frees the indoor kitchen entirely.",
    contains: ["meat"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 20,
    ingredients: [
      { item: "Chicken thigh", perGuest: 0.28, unit: "kg", aisle: "protein" },
      { item: "Lemon", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Yoghurt marinade", perGuest: 60, unit: "g", aisle: "dairy" },
    ],
  },
  {
    id: "frittata",
    name: "Slab frittata",
    course: "anchor",
    note: "Brunch anchor; eats warm or at room temperature.",
    contains: ["egg", "dairy"],
    formats: ["buffet", "grazing"],
    shapes: ["brunch"],
    ovenMin: 35,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Eggs", perGuest: 1.5, unit: "ea", aisle: "dairy" },
      { item: "Potato", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Spring onion", perGuest: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "soup-white-bean",
    name: "White bean & greens soup",
    course: "anchor",
    note: "One pot, deep make-ahead, scales without extra equipment.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 45,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 120,
    ingredients: [
      { item: "White beans", perGuest: 0.12, unit: "kg", aisle: "pantry" },
      { item: "Kale", perGuest: 0.08, unit: "kg", aisle: "produce" },
      { item: "Stock", perGuest: 0.35, unit: "L", aisle: "pantry" },
    ],
  },
  {
    id: "roast-roots",
    name: "Roast roots, honey & thyme",
    course: "side",
    note: "Shares oven heat with any roast.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "cookout"],
    ovenMin: 45,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 40,
    ingredients: [
      { item: "Carrot", perGuest: 0.9, unit: "ea", aisle: "produce" },
      { item: "Parsnip", perGuest: 0.6, unit: "ea", aisle: "produce" },
      { item: "Honey", perGuest: 8, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "green-salad",
    name: "Cold green salad, sharp dressing",
    course: "side",
    note: "Zero heat. Dress at the last moment.",
    contains: [],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "brunch", "cookout", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 20,
    ingredients: [
      { item: "Salad leaves", perGuest: 0.05, unit: "kg", aisle: "produce" },
      { item: "Lemon", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "grain-salad",
    name: "Herbed grain salad",
    course: "side",
    note: "Made a day ahead, improves cold, no reheat.",
    contains: ["gluten"],
    formats: ["buffet", "grazing", "seated"],
    shapes: ["dinner", "brunch", "cookout", "reception"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Pearl barley", perGuest: 0.07, unit: "kg", aisle: "pantry" },
      { item: "Parsley", perGuest: 0.15, unit: "bunch", aisle: "produce" },
      { item: "Cucumber", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "potato-gratin",
    name: "Potato gratin",
    course: "side",
    note: "Heavy oven demand. Only when a second rack is genuinely free.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 70,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Potato", perGuest: 0.22, unit: "kg", aisle: "produce" },
      { item: "Cream", perGuest: 70, unit: "ml", aisle: "dairy" },
      { item: "Garlic", perGuest: 0.5, unit: "clove", aisle: "produce" },
    ],
  },
  {
    id: "bread-warm",
    name: "Warm bread & cultured butter",
    course: "bread",
    note: "Bought in. Ten minutes of oven at the end, or skip the heat.",
    contains: ["gluten", "dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "brunch", "reception"],
    ovenMin: 10,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 5,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Sourdough loaf", perGuest: 0.18, unit: "ea", aisle: "bakery" },
      { item: "Butter", perGuest: 15, unit: "g", aisle: "dairy" },
    ],
  },
  {
    id: "board-cured",
    name: "Cured board",
    course: "board",
    note: "Assembly only. Buys you thirty minutes of arrival cover.",
    contains: ["pork", "dairy"],
    formats: ["grazing", "buffet", "cocktail"],
    shapes: ["reception", "aperitivo", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 90,
    ingredients: [
      { item: "Cured meats", perGuest: 60, unit: "g", aisle: "protein" },
      { item: "Hard cheese", perGuest: 50, unit: "g", aisle: "dairy" },
      { item: "Crackers", perGuest: 0.15, unit: "pack", aisle: "pantry" },
    ],
  },
  {
    id: "board-vegetable",
    name: "Vegetable & dip board",
    course: "board",
    note: "Cold, plant-only, arrival-proof.",
    contains: [],
    formats: ["grazing", "buffet", "cocktail"],
    shapes: ["reception", "aperitivo", "cookout", "brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Seasonal crudités", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Hummus", perGuest: 70, unit: "g", aisle: "pantry" },
      { item: "Olives", perGuest: 40, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "starter-soup-shot",
    name: "Chilled soup, small pour",
    course: "starter",
    note: "Made ahead, poured cold, no service heat.",
    contains: [],
    formats: ["seated", "cocktail"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Tomato", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Cucumber", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Sherry vinegar", perGuest: 5, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "starter-shellfish",
    name: "Chilled shellfish, mignonette",
    course: "starter",
    note: "Cold-chain critical. Needs dedicated fridge space and ice.",
    contains: ["shellfish"],
    formats: ["seated", "cocktail"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 3,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Oysters", perGuest: 3, unit: "ea", aisle: "protein" },
      { item: "Shallot", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Crushed ice", perGuest: 0.4, unit: "kg", aisle: "frozen" },
    ],
  },
  {
    id: "starter-toast",
    name: "Warm toasts, seasonal topping",
    course: "starter",
    note: "Short oven burst; competes with the anchor if timed badly.",
    contains: ["gluten"],
    formats: ["seated", "grazing", "cocktail"],
    shapes: ["dinner", "aperitivo", "reception"],
    ovenMin: 12,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 18,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 15,
    ingredients: [
      { item: "Baguette", perGuest: 0.2, unit: "ea", aisle: "bakery" },
      { item: "Seasonal topping", perGuest: 60, unit: "g", aisle: "produce" },
    ],
  },
  {
    id: "sweet-fridge-tart",
    name: "Set cream tart",
    course: "sweet",
    note: "Finished the day before. Occupies fridge, not oven.",
    contains: ["dairy", "gluten", "egg"],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "brunch", "reception"],
    ovenMin: 25,
    burnerMin: 10,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 240,
    ingredients: [
      { item: "Tart shell", perGuest: 0.1, unit: "ea", aisle: "bakery" },
      { item: "Cream", perGuest: 60, unit: "ml", aisle: "dairy" },
      { item: "Dark chocolate", perGuest: 35, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "sweet-fruit",
    name: "Macerated fruit & citrus",
    course: "sweet",
    note: "No heat, no dairy, no gluten. The safest close available.",
    contains: [],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "brunch", "cookout", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 240,
    ingredients: [
      { item: "Seasonal fruit", perGuest: 0.18, unit: "kg", aisle: "produce" },
      { item: "Citrus", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Sugar", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "drink-zero",
    name: "Zero-proof house pour",
    course: "drink",
    note: "Equal-status pour. Batched, chilled, poured like anything else.",
    contains: [],
    formats: ["seated", "buffet", "grazing", "cocktail"],
    shapes: ["dinner", "brunch", "reception", "cookout", "aperitivo"],
    ovenMin: 0,
    burnerMin: 5,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 300,
    ingredients: [
      { item: "Citrus & shrub base", perGuest: 90, unit: "ml", aisle: "drinks" },
      { item: "Sparkling water", perGuest: 0.25, unit: "L", aisle: "drinks" },
      { item: "Ice", perGuest: 0.35, unit: "kg", aisle: "frozen" },
    ],
  },
  {
    id: "drink-wine",
    name: "Wine service",
    course: "drink",
    note: "Counted, not guessed. Chilling capacity is the constraint.",
    contains: ["alcohol"],
    formats: ["seated", "buffet", "grazing", "cocktail"],
    shapes: ["dinner", "reception", "cookout", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 0,
    activeMin: 8,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 300,
    ingredients: [
      { item: "Wine", perGuest: 0.42, unit: "bottle", aisle: "drinks" },
      { item: "Glassware hire or wash", perGuest: 1.4, unit: "glass", aisle: "non-food" },
    ],
  },
  {
    id: "non-food-service",
    name: "Service kit",
    course: "drink",
    note: "The part hosts forget. Counted per guest, not per hope.",
    contains: [],
    formats: ["seated", "buffet", "grazing", "cocktail"],
    shapes: ["dinner", "brunch", "reception", "cookout", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 0,
    activeMin: 10,
    servesPerBatch: 12,
    makeAheadDays: 2,
    holdMin: 600,
    ingredients: [
      { item: "Napkins", perGuest: 2, unit: "ea", aisle: "non-food" },
      { item: "Serving vessel", perGuest: 0.25, unit: "ea", aisle: "non-food" },
      { item: "Bin liners", perGuest: 0.2, unit: "ea", aisle: "non-food" },
    ],
  },
];
