import type { Dish } from "./types";

// Table-service fixture library. Seated-course focus: starters, anchors, sides,
// breads, sweets. Educational fixtures — not tested recipes, not live prices.

export const TABLE_DISHES: Dish[] = [
  // ---- Starters ---------------------------------------------------------
  {
    id: "tb-burrata-tomato",
    name: "Burrata with heirloom tomato",
    course: "starter",
    note: "Assembly at the last minute; tomatoes carry the dish, not technique.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 25,
    season: ["summer"],
    costPerGuest: 3.4,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    ingredients: [
      { item: "Burrata", perGuest: 0.6, unit: "ea", aisle: "dairy" },
      { item: "Heirloom tomato", perGuest: 0.18, unit: "kg", aisle: "produce" },
      { item: "Basil", perGuest: 0.05, unit: "bunch", aisle: "produce" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-leek-vinaigrette",
    name: "Leeks vinaigrette",
    course: "starter",
    note: "Boiled and dressed a day ahead, plated cold, no last-minute burner.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["spring"],
    costPerGuest: 1.7,
    method: "boil",
    tempBand: "cold",
    ingredients: [
      { item: "Baby leeks", perGuest: 1, unit: "ea", aisle: "produce" },
      { item: "Dijon mustard", perGuest: 4, unit: "g", aisle: "pantry" },
      { item: "Sherry vinegar", perGuest: 5, unit: "ml", aisle: "pantry" },
      { item: "Egg", perGuest: 0.3, unit: "ea", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-carrot-ginger-soup",
    name: "Carrot & ginger soup",
    course: "starter",
    note: "One pot, blends ahead, reheats gently while the table sits down.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 35,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 120,
    season: ["autumn", "winter"],
    costPerGuest: 1.3,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Carrot", perGuest: 0.25, unit: "kg", aisle: "produce" },
      { item: "Ginger", perGuest: 8, unit: "g", aisle: "produce" },
      { item: "Onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Vegetable stock", perGuest: 0.3, unit: "L", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-scallop-crudo",
    name: "Scallop crudo, citrus & chilli",
    course: "starter",
    note: "Sliced to order; the one course with a hard no-make-ahead line.",
    contains: ["shellfish"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    season: ["winter", "spring"],
    costPerGuest: 8.5,
    method: "raw",
    tempBand: "cold",
    ingredients: [
      { item: "Fresh scallops", perGuest: 3, unit: "ea", aisle: "protein" },
      { item: "Lime", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Red chilli", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-mushroom-tart-starter",
    name: "Wild mushroom tartlets",
    course: "starter",
    note: "Blind-baked shells stored days ahead, filling finished to order.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 18,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 30,
    season: ["autumn"],
    costPerGuest: 3.1,
    method: "bake",
    tempBand: "warm",
    ingredients: [
      { item: "Tartlet shells", perGuest: 1, unit: "ea", aisle: "bakery" },
      { item: "Mixed mushrooms", perGuest: 0.1, unit: "kg", aisle: "produce" },
      { item: "Crème fraîche", perGuest: 30, unit: "g", aisle: "dairy" },
      { item: "Thyme", perGuest: 0.05, unit: "bunch", aisle: "produce" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-beetroot-goat-cheese",
    name: "Roast beetroot, whipped goat's cheese",
    course: "starter",
    note: "Beets roast a day ahead; only the plating happens at service.",
    contains: ["dairy", "nut"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 50,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["autumn", "winter"],
    costPerGuest: 3.6,
    method: "roast",
    tempBand: "cold",
    ingredients: [
      { item: "Beetroot", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Goat's cheese", perGuest: 40, unit: "g", aisle: "dairy" },
      { item: "Walnuts", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Honey", perGuest: 6, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-pea-mint-soup",
    name: "Chilled pea & mint soup",
    course: "starter",
    note: "Blitzed and chilled two days out, served in small glasses.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 180,
    season: ["spring", "summer"],
    costPerGuest: 1.5,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    ingredients: [
      { item: "Frozen peas", perGuest: 0.12, unit: "kg", aisle: "frozen" },
      { item: "Mint", perGuest: 0.05, unit: "bunch", aisle: "produce" },
      { item: "Crème fraîche", perGuest: 15, unit: "g", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-terrine-country",
    name: "Country terrine, pickles",
    course: "starter",
    note: "Made three days out and improves; slices clean under pressure.",
    contains: ["pork", "meat"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 75,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 120,
    season: ["autumn", "winter"],
    costPerGuest: 4.4,
    method: "bake",
    tempBand: "cold",
    ingredients: [
      { item: "Pork shoulder mince", perGuest: 0.1, unit: "kg", aisle: "protein" },
      { item: "Pork belly", perGuest: 0.05, unit: "kg", aisle: "protein" },
      { item: "Pickled cornichons", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Thyme", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
    cuisine: "house",
  },

  // ---- Anchors ------------------------------------------------------------
  {
    id: "tb-beef-wellington",
    name: "Beef Wellington, individual",
    course: "anchor",
    note: "High-attention centrepiece; every portion needs a watched oven window.",
    contains: ["meat", "gluten", "egg"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 30,
    burnerMin: 15,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 70,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 15,
    season: ["winter"],
    costPerGuest: 14,
    method: "bake",
    tempBand: "hot",
    ingredients: [
      { item: "Beef fillet", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Puff pastry", perGuest: 0.12, unit: "kg", aisle: "bakery" },
      { item: "Mushroom duxelles", perGuest: 0.08, unit: "kg", aisle: "produce" },
      { item: "Egg wash", perGuest: 0.15, unit: "ea", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-duck-breast-cherry",
    name: "Pan-seared duck breast, cherry jus",
    course: "anchor",
    note: "Rests while sides plate; sauce built from the same pan.",
    contains: ["meat"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 10,
    burnerMin: 25,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    season: ["autumn"],
    costPerGuest: 11,
    method: "fry",
    tempBand: "hot",
    ingredients: [
      { item: "Duck breast", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Cherries", perGuest: 0.06, unit: "kg", aisle: "produce" },
      { item: "Red wine", perGuest: 0.05, unit: "L", aisle: "drinks" },
      { item: "Shallot", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-halibut-beurre-blanc",
    name: "Poached halibut, beurre blanc",
    course: "anchor",
    note: "Delicate cook and a sauce that splits if you look away.",
    contains: ["fish", "dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 10,
    season: ["spring"],
    costPerGuest: 13,
    method: "boil",
    tempBand: "hot",
    ingredients: [
      { item: "Halibut fillet", perGuest: 0.2, unit: "kg", aisle: "protein" },
      { item: "Butter", perGuest: 40, unit: "g", aisle: "dairy" },
      { item: "White wine", perGuest: 0.04, unit: "L", aisle: "drinks" },
      { item: "Shallot", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-mushroom-wellington",
    name: "Mushroom & chestnut wellington",
    course: "anchor",
    note: "The no-meat centrepiece that still needs its own oven slot.",
    contains: ["gluten", "nut", "egg"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 35,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 3,
    activeMin: 55,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 20,
    season: ["winter"],
    costPerGuest: 5.2,
    method: "bake",
    tempBand: "hot",
    ingredients: [
      { item: "Mixed mushrooms", perGuest: 0.18, unit: "kg", aisle: "produce" },
      { item: "Chestnuts", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Puff pastry", perGuest: 0.1, unit: "kg", aisle: "bakery" },
      { item: "Egg wash", perGuest: 0.1, unit: "ea", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-osso-buco",
    name: "Osso buco, gremolata",
    course: "anchor",
    note: "Long braise, deep make-ahead, sauce reduces itself overnight.",
    contains: ["meat"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 150,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 90,
    season: ["winter"],
    costPerGuest: 9.5,
    method: "braise",
    tempBand: "hot",
    ingredients: [
      { item: "Veal shank", perGuest: 0.4, unit: "kg", aisle: "protein" },
      { item: "White wine", perGuest: 0.06, unit: "L", aisle: "drinks" },
      { item: "Carrot", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Lemon zest", perGuest: 2, unit: "g", aisle: "produce" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-stuffed-squash",
    name: "Stuffed squash, farro & sage",
    course: "anchor",
    note: "Roasts unattended; the vegetarian anchor that still looks carved.",
    contains: ["gluten"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 55,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 40,
    season: ["autumn"],
    costPerGuest: 3.8,
    method: "roast",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Small squash", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Farro", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Sage", perGuest: 0.03, unit: "bunch", aisle: "produce" },
      { item: "Parmesan", perGuest: 15, unit: "g", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-rack-of-lamb",
    name: "Herb-crusted rack of lamb",
    course: "anchor",
    note: "Short hot roast; carve and serve within minutes or it overshoots.",
    contains: ["meat"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 25,
    burnerMin: 10,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 4,
    makeAheadDays: 0,
    holdMin: 10,
    season: ["spring"],
    costPerGuest: 15,
    method: "roast",
    tempBand: "hot",
    ingredients: [
      { item: "Lamb rack", perGuest: 0.3, unit: "kg", aisle: "protein" },
      { item: "Breadcrumbs", perGuest: 20, unit: "g", aisle: "bakery" },
      { item: "Rosemary", perGuest: 0.02, unit: "bunch", aisle: "produce" },
      { item: "Dijon mustard", perGuest: 6, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-cassoulet",
    name: "Cassoulet",
    course: "anchor",
    note: "Two-day build; the crust is the only thing you touch on the day.",
    contains: ["meat", "pork"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 120,
    burnerMin: 40,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 50,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 60,
    season: ["winter"],
    costPerGuest: 8,
    method: "braise",
    tempBand: "hot",
    ingredients: [
      { item: "White beans", perGuest: 0.15, unit: "kg", aisle: "pantry" },
      { item: "Duck confit leg", perGuest: 0.5, unit: "ea", aisle: "protein" },
      { item: "Toulouse sausage", perGuest: 0.1, unit: "kg", aisle: "protein" },
      { item: "Breadcrumbs", perGuest: 15, unit: "g", aisle: "bakery" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-eggplant-involtini",
    name: "Aubergine involtini, ricotta & basil",
    course: "anchor",
    note: "Rolled a day ahead, oven-only finish, holds well under foil.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 30,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    season: ["summer"],
    costPerGuest: 3.9,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Aubergine", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Ricotta", perGuest: 50, unit: "g", aisle: "dairy" },
      { item: "Basil", perGuest: 0.04, unit: "bunch", aisle: "produce" },
      { item: "Passata", perGuest: 0.1, unit: "kg", aisle: "pantry" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-salmon-en-croute",
    name: "Salmon en croûte",
    course: "anchor",
    note: "Assembled cold ahead of time, bakes in one uninterrupted window.",
    contains: ["fish", "gluten", "egg"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 35,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 20,
    season: ["spring"],
    costPerGuest: 8.6,
    method: "bake",
    tempBand: "hot",
    ingredients: [
      { item: "Salmon fillet", perGuest: 0.18, unit: "kg", aisle: "protein" },
      { item: "Puff pastry", perGuest: 0.1, unit: "kg", aisle: "bakery" },
      { item: "Spinach", perGuest: 0.05, unit: "kg", aisle: "produce" },
      { item: "Egg wash", perGuest: 0.1, unit: "ea", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-lentil-mushroom-wellington",
    name: "Lentil & mushroom loaf",
    course: "anchor",
    note: "Bakes low and steady; slices cleanly once fully cooled and reheated.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 50,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    season: ["autumn", "winter"],
    costPerGuest: 2.9,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Green lentils", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Mushrooms", perGuest: 0.1, unit: "kg", aisle: "produce" },
      { item: "Onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Oats", perGuest: 20, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },

  // ---- Sides ---------------------------------------------------------------
  {
    id: "tb-dauphinoise",
    name: "Potato dauphinoise, thin-sliced",
    course: "side",
    note: "Long slow bake; assembles a day ahead and only needs reheating.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 80,
    burnerMin: 5,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 50,
    season: ["winter"],
    costPerGuest: 2.2,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Potato", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Cream", perGuest: 60, unit: "ml", aisle: "dairy" },
      { item: "Garlic", perGuest: 0.5, unit: "clove", aisle: "produce" },
      { item: "Nutmeg", perGuest: 0.2, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-glazed-carrots",
    name: "Glazed baby carrots, brown butter",
    course: "side",
    note: "One pan, five minutes at service, forgiving of a distracted cook.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 30,
    season: ["spring"],
    costPerGuest: 1.5,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Baby carrots", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Butter", perGuest: 12, unit: "g", aisle: "dairy" },
      { item: "Honey", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-braised-red-cabbage",
    name: "Braised red cabbage, apple & clove",
    course: "side",
    note: "Improves over two days; arrives at the table already reheated once.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 60,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    season: ["autumn", "winter"],
    costPerGuest: 1.2,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Red cabbage", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Apple", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Red wine vinegar", perGuest: 6, unit: "ml", aisle: "pantry" },
    ],
    cuisine: "nordic",
  },
  {
    id: "tb-green-beans-almond",
    name: "Green beans, toasted almond",
    course: "side",
    note: "Blanched ahead, tossed hot with butter at the very last minute.",
    contains: ["dairy", "nut"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 20,
    season: ["summer"],
    costPerGuest: 1.6,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Green beans", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Flaked almonds", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Butter", perGuest: 10, unit: "g", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-celeriac-puree",
    name: "Celeriac & potato purée",
    course: "side",
    note: "Blended smooth ahead, holds in a low oven bain-marie without splitting.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["winter"],
    costPerGuest: 1.8,
    method: "boil",
    tempBand: "hot",
    ingredients: [
      { item: "Celeriac", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Potato", perGuest: 0.1, unit: "kg", aisle: "produce" },
      { item: "Butter", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Cream", perGuest: 20, unit: "ml", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-roast-cauliflower-tahini",
    name: "Roast cauliflower, tahini & pomegranate",
    course: "side",
    note: "One tray, shares oven space, dressed at the pass not before.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 35,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 18,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 30,
    season: ["autumn"],
    costPerGuest: 2.1,
    method: "roast",
    tempBand: "hot",
    ingredients: [
      { item: "Cauliflower", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Tahini", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Pomegranate seeds", perGuest: 10, unit: "g", aisle: "produce" },
    ],
    cuisine: "levantine",
  },
  {
    id: "tb-buttered-peas-lettuce",
    name: "Buttered peas & baby gem",
    course: "side",
    note: "French-style braise, five minutes flat, no equipment competition.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 8,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 15,
    season: ["spring"],
    costPerGuest: 1.4,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Frozen peas", perGuest: 0.1, unit: "kg", aisle: "frozen" },
      { item: "Baby gem lettuce", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Butter", perGuest: 10, unit: "g", aisle: "dairy" },
    ],
    cuisine: "house",
  },

  // ---- Breads ---------------------------------------------------------------
  {
    id: "tb-brioche-rolls",
    name: "Warm brioche rolls",
    course: "bread",
    note: "Proofed and shaped a day ahead, baked off in the last twenty minutes.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 18,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 40,
    season: ["year-round"],
    costPerGuest: 0.9,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    ingredients: [
      { item: "Brioche dough", perGuest: 0.08, unit: "kg", aisle: "bakery" },
      { item: "Butter", perGuest: 10, unit: "g", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-grissini",
    name: "Grissini, rosemary & sea salt",
    course: "bread",
    note: "Baked days ahead, stays crisp in a sealed tin, zero day-of load.",
    contains: ["gluten"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 20,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 300,
    season: ["year-round"],
    costPerGuest: 0.5,
    method: "bake",
    tempBand: "ambient",
    outdoorSafe: true,
    cuisine: "italian",
    ingredients: [
      { item: "Bread flour", perGuest: 30, unit: "g", aisle: "pantry" },
      { item: "Rosemary", perGuest: 0.02, unit: "bunch", aisle: "produce" },
      { item: "Olive oil", perGuest: 6, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "tb-gf-cornbread",
    name: "Gluten-free cornbread",
    course: "bread",
    note: "One tin, bakes while the anchor rests, cuts into neat wedges.",
    contains: ["dairy", "egg"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 30,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["autumn"],
    costPerGuest: 1.1,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    ingredients: [
      { item: "Cornmeal", perGuest: 35, unit: "g", aisle: "pantry" },
      { item: "Buttermilk", perGuest: 40, unit: "ml", aisle: "dairy" },
      { item: "Egg", perGuest: 0.2, unit: "ea", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-focaccia-rosemary",
    name: "Rosemary focaccia, torn",
    course: "bread",
    note: "Dimpled and oiled the morning of; bakes while the room fills up.",
    contains: ["gluten"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 25,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["year-round"],
    costPerGuest: 0.8,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "italian",
    ingredients: [
      { item: "Focaccia dough", perGuest: 0.12, unit: "kg", aisle: "bakery" },
      { item: "Rosemary", perGuest: 0.02, unit: "bunch", aisle: "produce" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Flaky salt", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
  },

  // ---- Sweets ---------------------------------------------------------------
  {
    id: "tb-panna-cotta",
    name: "Vanilla panna cotta, berry coulis",
    course: "sweet",
    note: "Set two days ahead; the fridge does all the remaining work.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 300,
    season: ["summer"],
    costPerGuest: 2.3,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    ingredients: [
      { item: "Cream", perGuest: 90, unit: "ml", aisle: "dairy" },
      { item: "Gelatine", perGuest: 1.5, unit: "g", aisle: "pantry" },
      { item: "Mixed berries", perGuest: 40, unit: "g", aisle: "produce" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-tarte-tatin",
    name: "Apple tarte tatin",
    course: "sweet",
    note: "Baked ahead, flipped and rewarmed just before it hits the table.",
    contains: ["gluten", "dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 40,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["autumn"],
    costPerGuest: 2.6,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    ingredients: [
      { item: "Apples", perGuest: 0.25, unit: "ea", aisle: "produce" },
      { item: "Puff pastry", perGuest: 0.06, unit: "kg", aisle: "bakery" },
      { item: "Butter", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Sugar", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-lemon-posset",
    name: "Lemon posset",
    course: "sweet",
    note: "Three ingredients, sets in the fridge overnight, no gelatine to manage.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 12,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 300,
    season: ["spring"],
    costPerGuest: 1.6,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    ingredients: [
      { item: "Cream", perGuest: 80, unit: "ml", aisle: "dairy" },
      { item: "Lemon", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Sugar", perGuest: 25, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-pavlova",
    name: "Pavlova, whipped cream & passionfruit",
    course: "sweet",
    note: "Base baked and dried a day ahead; assemble only after guests are seated.",
    contains: ["dairy", "egg", "nut"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 90,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    season: ["summer"],
    costPerGuest: 2.4,
    method: "bake",
    tempBand: "cold",
    kidFriendly: true,
    ingredients: [
      { item: "Egg whites", perGuest: 1, unit: "ea", aisle: "dairy" },
      { item: "Sugar", perGuest: 40, unit: "g", aisle: "pantry" },
      { item: "Cream", perGuest: 50, unit: "ml", aisle: "dairy" },
      { item: "Passionfruit", perGuest: 0.5, unit: "ea", aisle: "produce" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-gf-flourless-chocolate-cake",
    name: "Flourless chocolate cake",
    course: "sweet",
    note: "Bakes low and slow, no gluten anywhere near it, sits well overnight.",
    contains: ["dairy", "egg"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 45,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 120,
    season: ["winter"],
    costPerGuest: 2.8,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    ingredients: [
      { item: "Dark chocolate", perGuest: 45, unit: "g", aisle: "pantry" },
      { item: "Butter", perGuest: 30, unit: "g", aisle: "dairy" },
      { item: "Eggs", perGuest: 0.6, unit: "ea", aisle: "dairy" },
      { item: "Sugar", perGuest: 25, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-vegan-poached-pear",
    name: "Vegan poached pear, spiced red wine",
    course: "sweet",
    note: "Sits in its own syrup for days; the plant-only close with no substitutions needed.",
    contains: ["alcohol"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 240,
    season: ["autumn", "winter"],
    costPerGuest: 2,
    method: "boil",
    tempBand: "cold",
    ingredients: [
      { item: "Pears", perGuest: 1, unit: "ea", aisle: "produce" },
      { item: "Red wine", perGuest: 0.08, unit: "L", aisle: "drinks" },
      { item: "Cinnamon stick", perGuest: 0.2, unit: "ea", aisle: "pantry" },
      { item: "Sugar", perGuest: 20, unit: "g", aisle: "pantry" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-affogato",
    name: "Affogato, torn amaretti",
    course: "sweet",
    note: "Assembled to order in seconds; the only heat is a shot of espresso.",
    contains: ["dairy", "gluten", "nut"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 10,
    season: ["year-round"],
    costPerGuest: 1.7,
    method: "raw",
    tempBand: "cold",
    ingredients: [
      { item: "Vanilla ice cream", perGuest: 80, unit: "g", aisle: "frozen" },
      { item: "Espresso", perGuest: 30, unit: "ml", aisle: "pantry" },
      { item: "Amaretti biscuits", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
    cuisine: "italian",
  },

  // ---- More starters/sides/anchors for spread -------------------------------
  {
    id: "tb-french-onion-soup",
    name: "French onion soup, gruyère crust",
    course: "starter",
    note: "Onions cook down a day ahead; only the broiler moment happens live.",
    contains: ["dairy", "gluten"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 10,
    burnerMin: 60,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 30,
    season: ["winter"],
    costPerGuest: 2.5,
    method: "braise",
    tempBand: "hot",
    ingredients: [
      { item: "Onion", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Beef stock", perGuest: 0.3, unit: "L", aisle: "pantry" },
      { item: "Gruyère", perGuest: 30, unit: "g", aisle: "dairy" },
      { item: "Baguette", perGuest: 0.1, unit: "ea", aisle: "bakery" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-crab-avocado-starter",
    name: "Crab & avocado starter",
    course: "starter",
    note: "Stacked in rings just before guests sit; nothing about it holds well.",
    contains: ["shellfish"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    season: ["summer"],
    costPerGuest: 7.8,
    method: "raw",
    tempBand: "cold",
    ingredients: [
      { item: "White crab meat", perGuest: 60, unit: "g", aisle: "protein" },
      { item: "Avocado", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Lime", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-nogluten-risotto",
    name: "Wild mushroom risotto",
    course: "anchor",
    note: "Needs a standing stirrer for twenty minutes right before service.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 10,
    season: ["autumn"],
    costPerGuest: 4.5,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Arborio rice", perGuest: 0.09, unit: "kg", aisle: "pantry" },
      { item: "Mixed mushrooms", perGuest: 0.1, unit: "kg", aisle: "produce" },
      { item: "Parmesan", perGuest: 25, unit: "g", aisle: "dairy" },
      { item: "White wine", perGuest: 0.03, unit: "L", aisle: "drinks" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-nut-free-stuffed-peppers",
    name: "Stuffed peppers, rice & herbs",
    course: "anchor",
    note: "Fully assembled a day ahead; the oven is the only thing needed on the day.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 40,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    season: ["summer"],
    costPerGuest: 2.6,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Bell peppers", perGuest: 1, unit: "ea", aisle: "produce" },
      { item: "Rice", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Parsley", perGuest: 0.03, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "tb-fennel-orange-shaved",
    name: "Shaved fennel & orange starter",
    course: "starter",
    note: "Sliced and held under film; dressed at the pass in under a minute.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["winter"],
    costPerGuest: 1.5,
    method: "raw",
    tempBand: "cold",
    outdoorSafe: true,
    cuisine: "italian",
    ingredients: [
      { item: "Fennel bulb", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Orange", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "tb-clam-linguine",
    name: "Clam linguine",
    course: "anchor",
    note: "Pasta timed to the pot; clams open in one fast burner-only pass.",
    contains: ["shellfish", "gluten"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 10,
    season: ["summer"],
    costPerGuest: 6.4,
    method: "boil",
    tempBand: "hot",
    ingredients: [
      { item: "Clams", perGuest: 0.25, unit: "kg", aisle: "protein" },
      { item: "Linguine", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "White wine", perGuest: 0.03, unit: "L", aisle: "drinks" },
      { item: "Garlic", perGuest: 1, unit: "clove", aisle: "produce" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-gf-polenta-side",
    name: "Soft polenta, parmesan",
    course: "side",
    note: "Holds warm over a low burner far longer than rice will forgive.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 35,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 45,
    season: ["autumn", "winter"],
    costPerGuest: 1.3,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Polenta", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Parmesan", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Butter", perGuest: 10, unit: "g", aisle: "dairy" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-braised-fennel-side",
    name: "Braised fennel, parmesan crumb",
    course: "side",
    note: "Braises in advance, finished under heat only for the crumb topping.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 15,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 40,
    season: ["winter"],
    costPerGuest: 1.9,
    method: "braise",
    tempBand: "hot",
    ingredients: [
      { item: "Fennel bulb", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Parmesan", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Vegetable stock", perGuest: 0.1, unit: "L", aisle: "pantry" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-heirloom-tomato-tart",
    name: "Heirloom tomato tart",
    course: "starter",
    note: "Base baked ahead cold, tomatoes only go on within the hour of serving.",
    contains: ["gluten", "dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 30,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    season: ["summer"],
    costPerGuest: 2.8,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    ingredients: [
      { item: "Puff pastry", perGuest: 0.05, unit: "kg", aisle: "bakery" },
      { item: "Heirloom tomato", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Goat's cheese", perGuest: 30, unit: "g", aisle: "dairy" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-braised-short-rib-single",
    name: "Individually plated braised short rib",
    course: "anchor",
    note: "Portioned before service so plating is a lift-and-place motion only.",
    contains: ["meat", "alcohol"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 200,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 60,
    season: ["winter"],
    costPerGuest: 12,
    method: "braise",
    tempBand: "hot",
    ingredients: [
      { item: "Beef short rib", perGuest: 0.4, unit: "kg", aisle: "protein" },
      { item: "Red wine", perGuest: 0.1, unit: "L", aisle: "drinks" },
      { item: "Onion", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Thyme", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
    cuisine: "house",
  },
  {
    id: "tb-charred-corn-side",
    name: "Charred corn, lime & chilli",
    course: "side",
    note: "Fast burner work at the end; needs a hot pan free right before plating.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 12,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 20,
    season: ["summer"],
    costPerGuest: 1.4,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
    ingredients: [
      { item: "Corn kernels", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Lime", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Chilli flakes", perGuest: 0.5, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "tb-onion-focaccia-bread",
    name: "Caramelised onion flatbread",
    course: "bread",
    note: "Onions cook down well ahead; dough only needs a final short bake.",
    contains: ["gluten"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 15,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    season: ["autumn"],
    costPerGuest: 1.1,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    ingredients: [
      { item: "Flatbread dough", perGuest: 0.1, unit: "kg", aisle: "bakery" },
      { item: "Onion", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
    cuisine: "italian",
  },
  {
    id: "tb-vegan-mushroom-broth",
    name: "Vegan mushroom broth, herb oil",
    course: "starter",
    note: "Long steeped stock made two days out, poured hot at the table.",
    contains: [],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 60,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    season: ["autumn", "winter"],
    costPerGuest: 1.7,
    method: "boil",
    tempBand: "hot",
    ingredients: [
      { item: "Dried mushrooms", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Vegetable stock", perGuest: 0.3, unit: "L", aisle: "pantry" },
      { item: "Chives", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
    cuisine: "house",
  },
];
