import type { Dish } from "./types";

// Constrained-kitchen fixture menu: no oven, one burner, tiny fridge, no dishwasher,
// low budget, pantry-first, make-ahead-heavy. Not tested recipes, not costed.

export const CONSTRAINT_DISHES: Dish[] = [
  {
    id: "cn-lentil-soup",
    name: "One-pot red lentil soup",
    course: "anchor",
    note: "Single burner, single pot, improves overnight in a jug.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Red lentils", perGuest: 0.09, unit: "kg", aisle: "pantry" },
      { item: "Onion", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Stock cube", perGuest: 0.5, unit: "ea", aisle: "pantry" },
      { item: "Cumin", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 1.1,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-tinned-tomato-pasta",
    name: "Tinned tomato pasta",
    course: "anchor",
    note: "Pantry standard, one pan, no waiting on anything else.",
    contains: ["gluten"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 4,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Dry pasta", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Tinned tomatoes", perGuest: 0.18, unit: "kg", aisle: "pantry" },
      { item: "Garlic", perGuest: 1, unit: "clove", aisle: "produce" },
      { item: "Dried oregano", perGuest: 0.5, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1.4,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "italian",
  },
  {
    id: "cn-chickpea-curry",
    name: "Tinned chickpea curry",
    course: "anchor",
    note: "Freezes in single-serve bags, reheats on the one burner in ten minutes.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 5,
    makeAheadDays: 2,
    holdMin: 45,
    ingredients: [
      { item: "Tinned chickpeas", perGuest: 0.2, unit: "kg", aisle: "pantry" },
      { item: "Curry powder", perGuest: 3, unit: "g", aisle: "pantry" },
      { item: "Onion", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Tinned coconut milk", perGuest: 0.06, unit: "L", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1.6,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
  },
  {
    id: "cn-instant-noodle-upgrade",
    name: "Dressed instant noodles",
    course: "anchor",
    note: "Ten-minute floor, one pot, no fridge dependency at all.",
    contains: ["gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 4,
    makeAheadDays: 0,
    holdMin: 10,
    ingredients: [
      { item: "Instant noodle blocks", perGuest: 1, unit: "ea", aisle: "pantry" },
      { item: "Soy sauce", perGuest: 6, unit: "ml", aisle: "pantry" },
      { item: "Spring onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Fried shallot", perGuest: 3, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.8,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "cn-tuna-rice-bowl",
    name: "Tinned tuna rice bowl",
    course: "anchor",
    note: "Rice batch-cooks ahead; tin opens at the table.",
    contains: ["fish"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 4,
    makeAheadDays: 1,
    holdMin: 40,
    ingredients: [
      { item: "Rice", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Tinned tuna", perGuest: 0.09, unit: "kg", aisle: "pantry" },
      { item: "Sweetcorn tin", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Mayonnaise", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 1.5,
    method: "boil",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-egg-fried-rice",
    name: "Egg fried rice, single wok",
    course: "anchor",
    note: "Uses yesterday's rice; entire dish never touches the fridge again once plated.",
    contains: ["egg"],
    formats: ["buffet", "grazing"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 12,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 4,
    makeAheadDays: 1,
    holdMin: 20,
    ingredients: [
      { item: "Cooked rice", perGuest: 0.15, unit: "kg", aisle: "pantry" },
      { item: "Egg", perGuest: 1, unit: "ea", aisle: "dairy" },
      { item: "Frozen peas", perGuest: 0.03, unit: "kg", aisle: "frozen" },
      { item: "Soy sauce", perGuest: 5, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1.0,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "cn-bean-chilli",
    name: "Three-bean chilli, no oven",
    course: "anchor",
    note: "Freezer-stable, reheats in the same pot it was cooked in.",
    contains: [],
    formats: ["buffet"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 35,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Tinned mixed beans", perGuest: 0.2, unit: "kg", aisle: "pantry" },
      { item: "Tinned tomatoes", perGuest: 0.15, unit: "kg", aisle: "pantry" },
      { item: "Onion", perGuest: 0.25, unit: "ea", aisle: "produce" },
      { item: "Chilli powder", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 1.2,
    method: "boil",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "cn-tinned-fish-salad",
    name: "Tinned sardine salad, no cook",
    course: "starter",
    note: "Zero heat, zero dish beyond one bowl and one fork.",
    contains: ["fish"],
    formats: ["seated", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 4,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Tinned sardines", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Tinned white beans", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Red onion", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 1.3,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "italian",
  },
  {
    id: "cn-crackers-tinned-pate",
    name: "Crackers, tinned pâté & pickle",
    course: "board",
    note: "No prep beyond a knife; everything shelf-stable until served.",
    contains: ["gluten", "meat"],
    formats: ["grazing", "cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 8,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 90,
    ingredients: [
      { item: "Crackers", perGuest: 4, unit: "ea", aisle: "pantry" },
      { item: "Tinned pâté", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Jarred pickle", perGuest: 0.02, unit: "kg", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1.0,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-hummus-board",
    name: "Tinned chickpea hummus & crackers",
    course: "board",
    note: "Blended cold, holds all evening on a counter with no cooling.",
    contains: ["gluten"],
    formats: ["grazing", "cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Tinned chickpeas", perGuest: 0.09, unit: "kg", aisle: "pantry" },
      { item: "Tahini", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Crackers", perGuest: 3, unit: "ea", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.9,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "cn-peanut-noodles",
    name: "Cold peanut noodles",
    course: "side",
    note: "Boiled once, dressed cold, eats fine at room temperature after.",
    contains: ["gluten", "nut"],
    formats: ["buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Dry noodles", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Peanut butter", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Soy sauce", perGuest: 6, unit: "ml", aisle: "pantry" },
      { item: "Spring onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 1.1,
    method: "boil",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "chinese",
  },
  {
    id: "cn-pantry-slaw",
    name: "Cabbage slaw, jarred dressing",
    course: "side",
    note: "No cooking, no fridge draw beyond the cabbage itself.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "White cabbage", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Carrot", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Jarred mayonnaise", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Vinegar", perGuest: 5, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.5,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-tinned-corn-salad",
    name: "Tinned corn & bean salad",
    course: "side",
    note: "Two tins, one bowl, no heat required at any stage.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 8,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Tinned sweetcorn", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Tinned black beans", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Lime", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Coriander", perGuest: 0.05, unit: "bunch", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 0.7,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "cn-boiled-potato-salad",
    name: "Boiled potato salad, jarred mayo",
    course: "side",
    note: "One pot boil, cools on the counter, no fridge shelf needed until serving.",
    contains: ["egg"],
    formats: ["buffet", "seated"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Potato", perGuest: 0.22, unit: "kg", aisle: "produce" },
      { item: "Jarred mayonnaise", perGuest: 18, unit: "g", aisle: "pantry" },
      { item: "Egg", perGuest: 0.5, unit: "ea", aisle: "dairy" },
      { item: "Spring onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 0.9,
    method: "boil",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-lentil-salad",
    name: "Tinned lentil salad, mustard dressing",
    course: "side",
    note: "No cooking, holds well past the length of any single service.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 5,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Tinned lentils", perGuest: 0.12, unit: "kg", aisle: "pantry" },
      { item: "Mustard", perGuest: 4, unit: "g", aisle: "pantry" },
      { item: "Red onion", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
    season: ["autumn"],
    costPerGuest: 0.8,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-no-knead-flatbread",
    name: "No-knead pan flatbread",
    course: "bread",
    note: "Cooks in the single dry pan, no oven, no proving drawer needed.",
    contains: ["gluten"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Yoghurt", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Baking powder", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Salt", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.5,
    method: "fry",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "cn-shop-baguette",
    name: "Shop baguette, no reheat",
    course: "bread",
    note: "Bought same day; the plan simply avoids trying to warm it without an oven.",
    contains: ["gluten"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 0,
    activeMin: 2,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 240,
    ingredients: [
      { item: "Baguette", perGuest: 0.4, unit: "ea", aisle: "bakery" },
      { item: "Butter", perGuest: 10, unit: "g", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 0.5,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-tortilla-wraps",
    name: "Warm tortillas, dry pan",
    course: "bread",
    note: "Thirty seconds a side on the one burner, stacked under a cloth.",
    contains: ["gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 8,
    fridgeUnits: 0,
    counter: 0,
    activeMin: 8,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 45,
    ingredients: [
      { item: "Tortillas", perGuest: 1.5, unit: "ea", aisle: "bakery" },
    ],
    season: ["year-round"],
    costPerGuest: 0.4,
    method: "fry",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "cn-instant-mash-cake",
    name: "Instant mash cakes, pan-fried",
    course: "side",
    note: "Powdered mash rehydrates cold, then browns fast in the one pan.",
    contains: ["dairy"],
    formats: ["buffet", "seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 12,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 5,
    makeAheadDays: 1,
    holdMin: 40,
    ingredients: [
      { item: "Instant mash powder", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Milk", perGuest: 40, unit: "ml", aisle: "dairy" },
      { item: "Flour", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
    season: ["winter"],
    costPerGuest: 0.6,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-no-cook-gazpacho",
    name: "No-cook gazpacho, small pour",
    course: "starter",
    note: "Blends cold, needs only tiny fridge space in cups until service.",
    contains: [],
    formats: ["seated", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Tomato", perGuest: 0.25, unit: "kg", aisle: "produce" },
      { item: "Cucumber", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Bread heel", perGuest: 15, unit: "g", aisle: "bakery" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 0.9,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "cn-savoury-oats",
    name: "Savoury pantry porridge",
    course: "starter",
    note: "Rolled oats and stock, single pan, ready in the time it takes to set a table.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 5,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Rolled oats", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Stock cube", perGuest: 0.3, unit: "ea", aisle: "pantry" },
      { item: "Egg", perGuest: 0.5, unit: "ea", aisle: "dairy" },
    ],
    season: ["winter"],
    costPerGuest: 0.5,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-pantry-frittata-mug",
    name: "Single-pan mug omelette",
    course: "starter",
    note: "One egg dish at a time in the one pan, staggered rather than batched.",
    contains: ["egg"],
    formats: ["seated"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 6,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 8,
    servesPerBatch: 1,
    makeAheadDays: 0,
    holdMin: 5,
    ingredients: [
      { item: "Egg", perGuest: 2, unit: "ea", aisle: "dairy" },
      { item: "Milk", perGuest: 15, unit: "ml", aisle: "dairy" },
      { item: "Cheddar", perGuest: 15, unit: "g", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 0.8,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-tinned-fruit-cup",
    name: "Tinned fruit cup, no chill needed",
    course: "sweet",
    note: "Straight from the pantry shelf, no fridge draw at all.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["dinner", "brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 0,
    activeMin: 5,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 180,
    ingredients: [
      { item: "Tinned fruit", perGuest: 0.15, unit: "kg", aisle: "pantry" },
      { item: "Biscuit crumb", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
    season: ["winter"],
    costPerGuest: 0.5,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-no-bake-oat-bars",
    name: "No-bake oat & honey bars",
    course: "sweet",
    note: "Set in the tiny fridge overnight, sliced cold, no oven at any point.",
    contains: ["gluten"],
    formats: ["grazing", "buffet"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 8,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Rolled oats", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Honey", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Peanut butter", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.5,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-instant-pudding-cups",
    name: "Instant pudding cups",
    course: "sweet",
    note: "Whisks cold in single-serve cups, uses one thin fridge shelf overnight.",
    contains: ["dairy"],
    formats: ["seated", "grazing"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 240,
    ingredients: [
      { item: "Instant pudding powder", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Milk", perGuest: 100, unit: "ml", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 0.5,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-microwave-mug-cake",
    name: "Microwave mug cake",
    course: "sweet",
    note: "Bypasses the oven entirely; each cup cooks separately in under two minutes.",
    contains: ["gluten", "egg"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 6,
    servesPerBatch: 1,
    makeAheadDays: 0,
    holdMin: 10,
    ingredients: [
      { item: "Flour", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Cocoa powder", perGuest: 5, unit: "g", aisle: "pantry" },
      { item: "Sugar", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Egg", perGuest: 0.25, unit: "ea", aisle: "dairy" },
    ],
    season: ["winter"],
    costPerGuest: 0.4,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-frozen-yoghurt-bark",
    name: "Frozen yoghurt bark",
    course: "sweet",
    note: "Frozen flat then snapped, needs freezer not fridge space and stores thin.",
    contains: ["dairy"],
    formats: ["grazing", "buffet"],
    shapes: ["reception", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Yoghurt", perGuest: 60, unit: "g", aisle: "dairy" },
      { item: "Honey", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Frozen berries", perGuest: 20, unit: "g", aisle: "frozen" },
    ],
    season: ["summer"],
    costPerGuest: 0.7,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-jarred-tapenade-toast",
    name: "Jarred tapenade toast",
    course: "board",
    note: "Jar and toaster only; no burner and no oven touched.",
    contains: ["gluten"],
    formats: ["grazing", "cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 8,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 45,
    ingredients: [
      { item: "Bread slices", perGuest: 1.5, unit: "ea", aisle: "bakery" },
      { item: "Jarred tapenade", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.6,
    method: "raw",
    tempBand: "warm",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "cn-tinned-olives-crisps",
    name: "Olives, crisps & tinned nuts",
    course: "board",
    note: "No prep beyond opening the tins; the whole board sits at room temperature.",
    contains: ["nut"],
    formats: ["cocktail", "grazing"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 5,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 180,
    ingredients: [
      { item: "Jarred olives", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Crisps", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Tinned mixed nuts", perGuest: 0.02, unit: "kg", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.6,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-jarred-pepper-board",
    name: "Jarred pepper & feta board",
    course: "board",
    note: "Tiny fridge only holds the feta block; peppers keep on the shelf.",
    contains: ["dairy"],
    formats: ["grazing", "cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Jarred roasted peppers", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Feta", perGuest: 25, unit: "g", aisle: "dairy" },
      { item: "Olive oil", perGuest: 6, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 0.9,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "cn-single-burner-mussels",
    name: "One-pan mussels, pantry broth",
    course: "anchor",
    note: "One pot, five minutes over heat, served straight from the pan.",
    contains: ["shellfish"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 4,
    makeAheadDays: 0,
    holdMin: 15,
    ingredients: [
      { item: "Mussels", perGuest: 0.3, unit: "kg", aisle: "protein" },
      { item: "Tinned tomatoes", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Garlic", perGuest: 1, unit: "clove", aisle: "produce" },
    ],
    season: ["autumn"],
    costPerGuest: 2.2,
    method: "boil",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "italian",
  },
  {
    id: "cn-fridge-pickled-veg",
    name: "Quick-pickled pantry vegetables",
    course: "side",
    note: "Vinegar does the preserving; the tiny fridge only needs a single jar's space.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 5,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Carrot", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Cucumber", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Vinegar", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Sugar", perGuest: 4, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 0.4,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-couscous-steep",
    name: "No-cook steeped couscous",
    course: "side",
    note: "Boiling water and a lid; the burner is used for ninety seconds only.",
    contains: ["gluten"],
    formats: ["buffet", "seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 3,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Couscous", perGuest: 0.07, unit: "kg", aisle: "pantry" },
      { item: "Stock cube", perGuest: 0.3, unit: "ea", aisle: "pantry" },
      { item: "Sultana", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 0.5,
    method: "boil",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "cn-pantry-tabbouleh",
    name: "Bulgur pantry tabbouleh",
    course: "side",
    note: "Grain steeps off-heat; the herb load carries the whole dish.",
    contains: ["gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Bulgur wheat", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Parsley", perGuest: 0.15, unit: "bunch", aisle: "produce" },
      { item: "Tomato", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Lemon", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 0.7,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "cn-jarred-curry-sauce-rice",
    name: "Jarred curry sauce over rice",
    course: "anchor",
    note: "One jar, one pot of rice, minimal decision-making at service.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 5,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Jarred curry sauce", perGuest: 0.15, unit: "kg", aisle: "pantry" },
      { item: "Rice", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Tinned chickpeas", perGuest: 0.08, unit: "kg", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1.3,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
  },
  {
    id: "cn-store-bought-quiche-slice",
    name: "Shop-bought quiche, sliced cold",
    course: "anchor",
    note: "Bought finished specifically because there is no oven to reheat it in.",
    contains: ["egg", "dairy", "gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 5,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Shop-bought quiche", perGuest: 0.15, unit: "kg", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 1.8,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-tinned-soup-boost",
    name: "Doctored tinned soup",
    course: "starter",
    note: "One tin, one pot, dressed up with a pantry spice and a squeeze of lemon.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 8,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 8,
    servesPerBatch: 4,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Tinned soup", perGuest: 0.25, unit: "kg", aisle: "pantry" },
      { item: "Chilli flakes", perGuest: 0.3, unit: "g", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
    season: ["winter"],
    costPerGuest: 0.8,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-cold-brew-batch",
    name: "Batch cold brew concentrate",
    course: "drink",
    note: "Steeps overnight in the one available jug space, no equipment needed.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["brunch", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 0,
    activeMin: 5,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 480,
    ingredients: [
      { item: "Coarse coffee grounds", perGuest: 12, unit: "g", aisle: "pantry" },
      { item: "Water", perGuest: 150, unit: "ml", aisle: "drinks" },
    ],
    season: ["summer"],
    costPerGuest: 0.4,
    method: "chill",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-powdered-lemonade",
    name: "Powdered lemonade jug",
    course: "drink",
    note: "No-cost mix, no burner, no fridge beyond one jug.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 0,
    activeMin: 3,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 300,
    ingredients: [
      { item: "Lemonade powder", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Water", perGuest: 200, unit: "ml", aisle: "drinks" },
    ],
    season: ["summer"],
    costPerGuest: 0.2,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-tinned-tea-punch",
    name: "Spiced tea bag punch",
    course: "drink",
    note: "Brewed once on the single burner, then held cold in the small jug.",
    contains: [],
    formats: ["grazing", "buffet"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 8,
    fridgeUnits: 1,
    counter: 0,
    activeMin: 8,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 240,
    ingredients: [
      { item: "Tea bags", perGuest: 0.3, unit: "ea", aisle: "pantry" },
      { item: "Sugar", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Orange", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
    season: ["winter"],
    costPerGuest: 0.3,
    method: "boil",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-cheap-house-wine",
    name: "House wine, no chill required",
    course: "drink",
    note: "Bought at room temperature; the tiny fridge is not asked to cool it.",
    contains: ["alcohol"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 0,
    activeMin: 2,
    servesPerBatch: 5,
    makeAheadDays: 0,
    holdMin: 240,
    ingredients: [
      { item: "Red wine", perGuest: 0.1, unit: "L", aisle: "drinks" },
    ],
    season: ["year-round"],
    costPerGuest: 1.5,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-store-crisps-dip",
    name: "Shop crisps, jarred dip",
    course: "board",
    note: "No prep beyond decanting; the whole board never approaches the burner.",
    contains: ["dairy"],
    formats: ["cocktail", "grazing"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 5,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 90,
    ingredients: [
      { item: "Crisps", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Jarred dip", perGuest: 20, unit: "g", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 0.5,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-tinned-peach-yoghurt",
    name: "Tinned peach & yoghurt pot",
    course: "sweet",
    note: "Assembled cold in cups, uses a single thin fridge shelf.",
    contains: ["dairy"],
    formats: ["seated", "grazing"],
    shapes: ["brunch", "dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 8,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Tinned peaches", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Yoghurt", perGuest: 60, unit: "g", aisle: "dairy" },
      { item: "Granola", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 0.7,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-single-pan-rice-pudding",
    name: "One-pan rice pudding",
    course: "sweet",
    note: "Slow on the single burner, then eaten cold from the same tiny fridge shelf.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 35,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Rice", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Milk", perGuest: 150, unit: "ml", aisle: "dairy" },
      { item: "Sugar", perGuest: 12, unit: "g", aisle: "pantry" },
    ],
    season: ["winter"],
    costPerGuest: 0.6,
    method: "boil",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-pantry-flapjack-nobake",
    name: "No-bake pantry flapjack",
    course: "sweet",
    note: "Set flat in the small fridge overnight, sliced thin to fit the shelf.",
    contains: ["gluten"],
    formats: ["grazing", "buffet"],
    shapes: ["reception", "dinner"],
    ovenMin: 0,
    burnerMin: 8,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Rolled oats", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Golden syrup", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Butter", perGuest: 8, unit: "g", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 0.4,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-dry-cereal-bar",
    name: "Dry cereal & tinned milk bar",
    course: "starter",
    note: "Zero heat, zero real fridge draw beyond a small tin of condensed milk.",
    contains: ["gluten", "dairy"],
    formats: ["buffet"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 5,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Cereal", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Tinned evaporated milk", perGuest: 30, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.4,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
  },
  {
    id: "cn-toast-jam-spread",
    name: "Toast, jam & pantry spread bar",
    course: "starter",
    note: "Toaster only, no burner queue, guests self-serve from jars.",
    contains: ["gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 5,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Bread slices", perGuest: 2, unit: "ea", aisle: "bakery" },
      { item: "Jam", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Peanut butter", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 0.5,
    method: "raw",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
  },
  {
    id: "cn-tinned-corn-fritters",
    name: "Tinned corn fritters, one pan",
    course: "starter",
    note: "Batter mixes cold, fries in batches in the single pan.",
    contains: ["gluten", "egg"],
    formats: ["seated", "buffet"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 18,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Tinned sweetcorn", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Flour", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Egg", perGuest: 0.5, unit: "ea", aisle: "dairy" },
    ],
    season: ["summer"],
    costPerGuest: 0.6,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "mexican",
  },
  {
    id: "cn-cold-tofu-pantry",
    name: "Cold tofu, pantry soy dressing",
    course: "starter",
    note: "No cooking, silken tofu keeps in a single tiny fridge corner.",
    contains: [],
    formats: ["seated", "grazing"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 6,
    servesPerBatch: 4,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Silken tofu", perGuest: 0.1, unit: "kg", aisle: "protein" },
      { item: "Soy sauce", perGuest: 5, unit: "ml", aisle: "pantry" },
      { item: "Spring onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 0.9,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "cn-single-pot-dhal-toast",
    name: "Single-pot dhal with toast",
    course: "anchor",
    note: "One burner runs the pot while the toaster does the bread.",
    contains: ["gluten"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 5,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Split red lentils", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Turmeric", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Bread slices", perGuest: 1, unit: "ea", aisle: "bakery" },
    ],
    season: ["winter"],
    costPerGuest: 0.8,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
  }
];
