import type { Dish } from "./types";

// Third-wave fixture library: buffet, grazing, cocktail and cookout dishes
// built for scale — boards, trays, big-batch anchors, handheld food, drinks.
// Educational fixtures — not tested recipes, not live prices.

export const CROWD_DISHES: Dish[] = [
  // ---- Boards & grazing --------------------------------------------------
  {
    id: "cw-board-antipasti-long",
    name: "Long antipasti board",
    course: "board",
    note: "One trestle, no reheating, refills from the fridge as it empties.",
    contains: ["pork", "dairy", "gluten"],
    formats: ["grazing", "cocktail"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 3,
    counter: 3,
    activeMin: 35,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 150,
    season: ["year-round"],
    costPerGuest: 5.4,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "italian",
    ingredients: [
      { item: "Cured meats", perGuest: 0.05, unit: "kg", aisle: "protein" },
      { item: "Hard cheese", perGuest: 0.04, unit: "kg", aisle: "dairy" },
      { item: "Breadsticks", perGuest: 3, unit: "ea", aisle: "bakery" },
      { item: "Marinated artichokes", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Cornichons", perGuest: 20, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "cw-board-vegan-grazing",
    name: "No-animal grazing board",
    course: "board",
    note: "Assembles cold, no allergens hiding in the dairy case.",
    contains: [],
    formats: ["grazing", "cocktail"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 30,
    servesPerBatch: 18,
    makeAheadDays: 1,
    holdMin: 150,
    season: ["year-round"],
    costPerGuest: 3.6,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Hummus", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Mixed olives", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Cherry tomatoes", perGuest: 0.06, unit: "kg", aisle: "produce" },
      { item: "Flatbread crackers", perGuest: 4, unit: "ea", aisle: "bakery" },
      { item: "Roasted almonds", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "cw-board-pickle-tray",
    name: "Pickle and ferment tray",
    course: "board",
    note: "Holds indefinitely; the only board that improves left out.",
    contains: [],
    formats: ["grazing", "cocktail", "buffet"],
    shapes: ["reception", "aperitivo", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 20,
    makeAheadDays: 2,
    holdMin: 180,
    season: ["year-round"],
    costPerGuest: 1.4,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Mixed pickles", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Pickled onions", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Kimchi", perGuest: 0.03, unit: "kg", aisle: "pantry" },
    ],
  },
  {
    id: "cw-board-smoked-meat-tray",
    name: "Sliced brisket tray, self-serve",
    course: "board",
    note: "Rests wrapped for two hours, slices to order at the table.",
    contains: ["meat"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 3,
    counter: 3,
    activeMin: 40,
    servesPerBatch: 16,
    makeAheadDays: 1,
    holdMin: 120,
    season: ["summer"],
    costPerGuest: 8.8,
    method: "grill",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Beef brisket", perGuest: 0.3, unit: "kg", aisle: "protein" },
      { item: "Dry rub", perGuest: 4, unit: "g", aisle: "pantry" },
      { item: "Soft rolls", perGuest: 1, unit: "ea", aisle: "bakery" },
      { item: "BBQ sauce", perGuest: 20, unit: "ml", aisle: "pantry" },
    ],
  },

  // ---- Big-batch anchors --------------------------------------------------
  {
    id: "cw-anchor-pulled-jackfruit",
    name: "Pulled jackfruit, big pot",
    course: "anchor",
    note: "One pot feeds a crowd, no-meat and freezes in the base state.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 70,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 14,
    makeAheadDays: 2,
    holdMin: 120,
    season: ["summer", "autumn"],
    costPerGuest: 3.2,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Tinned jackfruit", perGuest: 0.18, unit: "kg", aisle: "pantry" },
      { item: "BBQ sauce", perGuest: 25, unit: "ml", aisle: "pantry" },
      { item: "Onion", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Soft rolls", perGuest: 1, unit: "ea", aisle: "bakery" },
    ],
  },
  {
    id: "cw-anchor-whole-hog-tray",
    name: "Tray-roast pork loin, sliceable",
    course: "anchor",
    note: "One tray reload, carves in strips for a moving line.",
    contains: ["pork"],
    formats: ["buffet"],
    shapes: ["cookout", "dinner"],
    ovenMin: 100,
    burnerMin: 0,
    fridgeUnits: 3,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 12,
    makeAheadDays: 0,
    holdMin: 60,
    season: ["autumn", "winter"],
    costPerGuest: 6.6,
    method: "roast",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
    ingredients: [
      { item: "Pork loin", perGuest: 0.28, unit: "kg", aisle: "protein" },
      { item: "Apple", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Sage", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "cw-anchor-vat-chilli",
    name: "Vat of beef chilli",
    course: "anchor",
    note: "Stovetop only, no oven contention, tastes better the next day.",
    contains: ["meat"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "dinner"],
    ovenMin: 0,
    burnerMin: 90,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 35,
    servesPerBatch: 18,
    makeAheadDays: 2,
    holdMin: 150,
    season: ["autumn", "winter"],
    costPerGuest: 3.9,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
    ingredients: [
      { item: "Beef mince", perGuest: 0.12, unit: "kg", aisle: "protein" },
      { item: "Kidney beans", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Tinned tomatoes", perGuest: 0.15, unit: "kg", aisle: "pantry" },
      { item: "Chipotle paste", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "cw-anchor-no-gluten-paella",
    name: "Paella, rice-based, gluten-free",
    course: "anchor",
    note: "One wide pan, no last stir needed once it's on the heat.",
    contains: ["shellfish"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 45,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 30,
    servesPerBatch: 14,
    makeAheadDays: 0,
    holdMin: 40,
    season: ["summer"],
    costPerGuest: 6.1,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Paella rice", perGuest: 0.09, unit: "kg", aisle: "pantry" },
      { item: "Prawns", perGuest: 0.08, unit: "kg", aisle: "protein" },
      { item: "Saffron", perGuest: 0.05, unit: "g", aisle: "pantry" },
      { item: "Peas", perGuest: 0.03, unit: "kg", aisle: "frozen" },
      { item: "Stock", perGuest: 0.2, unit: "L", aisle: "pantry" },
    ],
  },
  {
    id: "cw-anchor-mac-cheese-tray",
    name: "Baked mac and cheese, catering tray",
    course: "anchor",
    note: "Assembles the day before, bakes once, holds under foil.",
    contains: ["dairy", "gluten"],
    formats: ["buffet"],
    shapes: ["cookout", "dinner", "reception"],
    ovenMin: 50,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 16,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["autumn", "winter"],
    costPerGuest: 3.1,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
    ingredients: [
      { item: "Macaroni", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Cheddar", perGuest: 0.07, unit: "kg", aisle: "dairy" },
      { item: "Milk", perGuest: 0.1, unit: "L", aisle: "dairy" },
      { item: "Breadcrumbs", perGuest: 10, unit: "g", aisle: "bakery" },
    ],
  },
  {
    id: "cw-anchor-lentil-shepherds",
    name: "Lentil shepherd's pie, catering tray",
    course: "anchor",
    note: "Plant-only anchor that reheats without drying out.",
    contains: [],
    formats: ["buffet"],
    shapes: ["dinner", "reception"],
    ovenMin: 45,
    burnerMin: 25,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 14,
    makeAheadDays: 2,
    holdMin: 60,
    season: ["autumn", "winter"],
    costPerGuest: 2.6,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
    ingredients: [
      { item: "Green lentils", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Potato", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Carrot", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Butter", perGuest: 10, unit: "g", aisle: "dairy" },
    ],
  },

  // ---- Handheld / cocktail things -----------------------------------------
  {
    id: "cw-hand-mini-sliders",
    name: "Mini beef sliders",
    course: "starter",
    note: "Griddle in batches, dressed at the pass, never sits assembled long.",
    contains: ["meat", "gluten", "dairy"],
    formats: ["cocktail", "grazing"],
    shapes: ["reception", "cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 20,
    season: ["summer"],
    costPerGuest: 4.5,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Beef mince", perGuest: 0.07, unit: "kg", aisle: "protein" },
      { item: "Slider buns", perGuest: 1, unit: "ea", aisle: "bakery" },
      { item: "Cheddar slices", perGuest: 1, unit: "ea", aisle: "dairy" },
      { item: "Pickles", perGuest: 3, unit: "ea", aisle: "pantry" },
    ],
  },
  {
    id: "cw-hand-arancini",
    name: "Arancini, fried to order",
    course: "starter",
    note: "Formed and chilled ahead, fried fresh in short bursts.",
    contains: ["dairy", "gluten", "egg"],
    formats: ["cocktail", "grazing"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 24,
    makeAheadDays: 1,
    holdMin: 25,
    season: ["year-round"],
    costPerGuest: 1.9,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "italian",
    ingredients: [
      { item: "Cooked risotto rice", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Mozzarella", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Breadcrumbs", perGuest: 20, unit: "g", aisle: "bakery" },
      { item: "Egg", perGuest: 0.2, unit: "ea", aisle: "dairy" },
    ],
  },
  {
    id: "cw-hand-no-gluten-skewers",
    name: "Halloumi and pepper skewers, gluten-free",
    course: "starter",
    note: "Skewer the morning of, grill in the last twenty minutes.",
    contains: ["dairy"],
    formats: ["cocktail", "grazing", "buffet"],
    shapes: ["reception", "cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 30,
    season: ["summer"],
    costPerGuest: 2.7,
    method: "grill",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
    ingredients: [
      { item: "Halloumi", perGuest: 0.06, unit: "kg", aisle: "dairy" },
      { item: "Bell pepper", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Red onion", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "cw-hand-samosas",
    name: "Vegetable samosas, oven-finished",
    course: "starter",
    note: "Bought or made ahead frozen, finishes crisp on a tray.",
    contains: ["gluten"],
    formats: ["cocktail", "grazing", "buffet"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 25,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 24,
    makeAheadDays: 2,
    holdMin: 40,
    season: ["year-round"],
    costPerGuest: 1.2,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
    ingredients: [
      { item: "Frozen samosas", perGuest: 2, unit: "ea", aisle: "frozen" },
      { item: "Tamarind chutney", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "cw-hand-shrimp-cocktail-shooters",
    name: "Shrimp cocktail shooters",
    course: "starter",
    note: "Glasses build ahead and sit in the fridge door until the room fills.",
    contains: ["shellfish"],
    formats: ["cocktail"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["summer"],
    costPerGuest: 3.4,
    method: "chill",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "house",
    ingredients: [
      { item: "Cooked prawns", perGuest: 0.06, unit: "kg", aisle: "protein" },
      { item: "Cocktail sauce", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "cw-hand-no-meat-sausage-rolls",
    name: "No-meat sausage rolls",
    course: "starter",
    note: "Bakes in trays back to back, holds warm under a cloth.",
    contains: ["gluten"],
    formats: ["cocktail", "grazing", "buffet"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 30,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 24,
    makeAheadDays: 2,
    holdMin: 60,
    season: ["year-round"],
    costPerGuest: 1.6,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
    ingredients: [
      { item: "Puff pastry", perGuest: 0.05, unit: "kg", aisle: "frozen" },
      { item: "Meat-free mince", perGuest: 0.05, unit: "kg", aisle: "frozen" },
      { item: "Onion", perGuest: 0.05, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "cw-hand-corn-ribs",
    name: "Grilled corn ribs",
    course: "starter",
    note: "Cut before guests arrive, finishes on the grill in one pass.",
    contains: [],
    formats: ["cocktail", "grazing", "buffet"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 16,
    makeAheadDays: 1,
    holdMin: 30,
    season: ["summer"],
    costPerGuest: 1.5,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
    ingredients: [
      { item: "Corn on the cob", perGuest: 0.6, unit: "ea", aisle: "produce" },
      { item: "Chilli lime butter", perGuest: 10, unit: "g", aisle: "dairy" },
    ],
  },
  {
    id: "cw-hand-deviled-ham-biscuits",
    name: "Ham biscuits, split and filled",
    course: "starter",
    note: "Biscuits baked ahead, filled cold in a fast production line.",
    contains: ["pork", "gluten", "dairy"],
    formats: ["cocktail", "grazing"],
    shapes: ["reception"],
    ovenMin: 20,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 24,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["winter"],
    costPerGuest: 2.2,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
    ingredients: [
      { item: "Mini biscuits", perGuest: 2, unit: "ea", aisle: "bakery" },
      { item: "Sliced ham", perGuest: 0.03, unit: "kg", aisle: "protein" },
      { item: "Mustard butter", perGuest: 8, unit: "g", aisle: "dairy" },
    ],
  },

  // ---- Cookout sides & salads ---------------------------------------------
  {
    id: "cw-side-loaded-potato-salad",
    name: "Loaded potato salad, big bowl",
    course: "side",
    note: "One bowl, dressed ahead, sits at ambient without complaint.",
    contains: ["egg", "dairy"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 16,
    makeAheadDays: 1,
    holdMin: 120,
    season: ["summer"],
    costPerGuest: 1.3,
    method: "boil",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "New potatoes", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Mayonnaise", perGuest: 25, unit: "g", aisle: "pantry" },
      { item: "Egg", perGuest: 0.3, unit: "ea", aisle: "dairy" },
      { item: "Spring onion", perGuest: 0.05, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "cw-side-watermelon-feta",
    name: "Watermelon and feta, big platter",
    course: "side",
    note: "Cuts ahead, dresses at the last minute so it doesn't weep.",
    contains: ["dairy"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 18,
    makeAheadDays: 0,
    holdMin: 60,
    season: ["summer"],
    costPerGuest: 1.8,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
    ingredients: [
      { item: "Watermelon", perGuest: 0.25, unit: "kg", aisle: "produce" },
      { item: "Feta", perGuest: 0.03, unit: "kg", aisle: "dairy" },
      { item: "Mint", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "cw-side-charred-corn-salad",
    name: "Charred corn and black bean salad",
    course: "side",
    note: "No-animal, no-gluten, holds at ambient through a long service.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 16,
    makeAheadDays: 1,
    holdMin: 120,
    season: ["summer"],
    costPerGuest: 1.6,
    method: "grill",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
    ingredients: [
      { item: "Corn kernels", perGuest: 0.1, unit: "kg", aisle: "frozen" },
      { item: "Black beans", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Lime", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Coriander", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "cw-side-bulk-coleslaw",
    name: "Bulk coleslaw, catering bag",
    course: "side",
    note: "The cheapest cold side on the table, dresses in minutes.",
    contains: ["egg"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 120,
    season: ["year-round"],
    costPerGuest: 0.9,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Shredded cabbage mix", perGuest: 0.09, unit: "kg", aisle: "produce" },
      { item: "Mayonnaise", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Cider vinegar", perGuest: 5, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "cw-side-no-gluten-rice-salad",
    name: "Herbed rice salad, gluten-free",
    course: "side",
    note: "Cooks the day before, comes to room temperature on the buffet.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["reception", "cookout"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 18,
    makeAheadDays: 1,
    holdMin: 120,
    season: ["spring", "summer"],
    costPerGuest: 1.1,
    method: "boil",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
    ingredients: [
      { item: "Basmati rice", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Parsley", perGuest: 0.03, unit: "bunch", aisle: "produce" },
      { item: "Lemon", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Pine nuts", perGuest: 8, unit: "g", aisle: "pantry" },
    ],
  },

  // ---- Bread & sweet -------------------------------------------------------
  {
    id: "cw-bread-cornbread-tray",
    name: "Cornbread, catering tray, sliced",
    course: "bread",
    note: "One tray bakes and cuts into squares, no individual portioning.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    ovenMin: 35,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 120,
    season: ["autumn"],
    costPerGuest: 0.8,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Cornmeal", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Butter", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Egg", perGuest: 0.15, unit: "ea", aisle: "dairy" },
    ],
  },
  {
    id: "cw-sweet-lemon-bar-tray",
    name: "Lemon bars, catering tray",
    course: "sweet",
    note: "Bakes flat, cuts cold, travels well to an outdoor table.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["reception", "cookout"],
    ovenMin: 40,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 24,
    makeAheadDays: 2,
    holdMin: 180,
    season: ["summer"],
    costPerGuest: 0.9,
    method: "bake",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Lemon", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Butter", perGuest: 10, unit: "g", aisle: "dairy" },
      { item: "Flour", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Egg", perGuest: 0.2, unit: "ea", aisle: "dairy" },
    ],
  },
  {
    id: "cw-sweet-no-gluten-brownie-tray",
    name: "Gluten-free brownie tray",
    course: "sweet",
    note: "One tin, one bake, cuts into small squares for a long table.",
    contains: ["dairy", "egg", "nut"],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["reception", "cookout"],
    ovenMin: 30,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 24,
    makeAheadDays: 2,
    holdMin: 180,
    season: ["year-round"],
    costPerGuest: 1.2,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Ground almonds", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Dark chocolate", perGuest: 25, unit: "g", aisle: "pantry" },
      { item: "Butter", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Egg", perGuest: 0.2, unit: "ea", aisle: "dairy" },
    ],
  },
  {
    id: "cw-sweet-smores-bar",
    name: "S'mores bar, fire-side",
    course: "sweet",
    note: "No cooking indoors; the fire pit does the work at the end of the night.",
    contains: ["gluten", "dairy"],
    formats: ["cocktail", "grazing", "buffet"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 20,
    makeAheadDays: 0,
    holdMin: 180,
    season: ["summer", "autumn"],
    costPerGuest: 1.0,
    method: "grill",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Marshmallows", perGuest: 2, unit: "ea", aisle: "pantry" },
      { item: "Digestive biscuits", perGuest: 2, unit: "ea", aisle: "bakery" },
      { item: "Chocolate squares", perGuest: 2, unit: "ea", aisle: "pantry" },
    ],
  },
  {
    id: "cw-sweet-fruit-skewers",
    name: "Fruit skewers, no-animal",
    course: "sweet",
    note: "Cut and skewer ahead, the coolest thing on a hot buffet table.",
    contains: [],
    formats: ["grazing", "cocktail", "buffet"],
    shapes: ["reception", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["summer"],
    costPerGuest: 1.3,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Melon", perGuest: 0.1, unit: "kg", aisle: "produce" },
      { item: "Pineapple", perGuest: 0.08, unit: "kg", aisle: "produce" },
      { item: "Grapes", perGuest: 0.06, unit: "kg", aisle: "produce" },
    ],
  },

  // ---- Drinks ---------------------------------------------------------------
  {
    id: "cw-drink-batched-punch",
    name: "Batched rum punch, dispenser",
    course: "drink",
    note: "Mixes the morning of, pours from a single dispenser all night.",
    contains: ["alcohol"],
    formats: ["cocktail", "grazing"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 240,
    season: ["summer"],
    costPerGuest: 2.4,
    method: "chill",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "caribbean",
    ingredients: [
      { item: "Dark rum", perGuest: 40, unit: "ml", aisle: "drinks" },
      { item: "Pineapple juice", perGuest: 80, unit: "ml", aisle: "drinks" },
      { item: "Lime", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "cw-drink-no-alcohol-cooler",
    name: "Alcohol-free berry cooler, dispenser",
    course: "drink",
    note: "One jug covers the whole afternoon, kid-safe by design.",
    contains: [],
    formats: ["cocktail", "grazing", "buffet"],
    shapes: ["reception", "cookout", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 240,
    season: ["summer"],
    costPerGuest: 1.0,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Mixed berries", perGuest: 0.03, unit: "kg", aisle: "produce" },
      { item: "Sparkling water", perGuest: 0.2, unit: "L", aisle: "drinks" },
      { item: "Mint", perGuest: 0.01, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "cw-drink-iced-tea-urn",
    name: "Iced tea, big urn",
    course: "drink",
    note: "Brews ahead and lives in a cooler, no ice dilution problem.",
    contains: [],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 24,
    makeAheadDays: 1,
    holdMin: 240,
    season: ["summer"],
    costPerGuest: 0.5,
    method: "boil",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Black tea bags", perGuest: 0.5, unit: "ea", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Sugar", perGuest: 8, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "cw-drink-frozen-margarita-batch",
    name: "Frozen margarita, big-batch mix",
    course: "drink",
    note: "Freezes solid overnight, blends to order at a single station.",
    contains: ["alcohol"],
    formats: ["cocktail"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 16,
    makeAheadDays: 2,
    holdMin: 180,
    season: ["summer"],
    costPerGuest: 3.0,
    method: "chill",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "mexican",
    ingredients: [
      { item: "Tequila", perGuest: 40, unit: "ml", aisle: "drinks" },
      { item: "Lime juice", perGuest: 30, unit: "ml", aisle: "drinks" },
      { item: "Triple sec", perGuest: 15, unit: "ml", aisle: "drinks" },
    ],
  },
  {
    id: "cw-drink-mulled-wine-pot",
    name: "Mulled wine, one pot",
    course: "drink",
    note: "Simmers low all evening on a single burner, tops itself up.",
    contains: ["alcohol"],
    formats: ["grazing", "buffet", "cocktail"],
    shapes: ["reception", "cookout"],
    ovenMin: 0,
    burnerMin: 180,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 16,
    makeAheadDays: 0,
    holdMin: 180,
    season: ["winter"],
    costPerGuest: 2.2,
    method: "boil",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Red wine", perGuest: 0.15, unit: "L", aisle: "drinks" },
      { item: "Orange", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Cinnamon stick", perGuest: 0.1, unit: "ea", aisle: "pantry" },
    ],
  },
  {
    id: "cw-drink-hot-cider-urn",
    name: "Hot spiced cider, urn",
    course: "drink",
    note: "Alcohol-free, keeps warm in an urn through a cold outdoor service.",
    contains: [],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 60,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 20,
    makeAheadDays: 0,
    holdMin: 180,
    season: ["autumn", "winter"],
    costPerGuest: 0.9,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Apple cider", perGuest: 0.2, unit: "L", aisle: "drinks" },
      { item: "Cinnamon stick", perGuest: 0.1, unit: "ea", aisle: "pantry" },
      { item: "Clove", perGuest: 1, unit: "ea", aisle: "pantry" },
    ],
  },
  {
    id: "cw-drink-spritz-station",
    name: "Spritz station, build-your-own",
    course: "drink",
    note: "Guests build their own from three bottles, no bartender required.",
    contains: ["alcohol"],
    formats: ["cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 15,
    servesPerBatch: 20,
    makeAheadDays: 0,
    holdMin: 180,
    season: ["spring", "summer"],
    costPerGuest: 3.6,
    method: "chill",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "italian",
    ingredients: [
      { item: "Aperitif liqueur", perGuest: 60, unit: "ml", aisle: "drinks" },
      { item: "Prosecco", perGuest: 90, unit: "ml", aisle: "drinks" },
      { item: "Soda water", perGuest: 30, unit: "ml", aisle: "drinks" },
      { item: "Orange", perGuest: 0.15, unit: "ea", aisle: "produce" },
    ],
  },

  // ---- More boards / grazing / cookout to round out coverage ---------------
  {
    id: "cw-board-breakfast-buffet",
    name: "Breakfast buffet board",
    course: "board",
    note: "Sets out cold, replenishes from a warming tray of eggs only.",
    contains: ["dairy", "gluten", "egg"],
    formats: ["buffet", "grazing"],
    shapes: ["brunch"],
    ovenMin: 20,
    burnerMin: 10,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 30,
    servesPerBatch: 18,
    makeAheadDays: 0,
    holdMin: 90,
    season: ["year-round"],
    costPerGuest: 3.8,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
    ingredients: [
      { item: "Pastries", perGuest: 1, unit: "ea", aisle: "bakery" },
      { item: "Scrambled eggs", perGuest: 0.12, unit: "kg", aisle: "dairy" },
      { item: "Yoghurt", perGuest: 0.08, unit: "kg", aisle: "dairy" },
      { item: "Berries", perGuest: 0.05, unit: "kg", aisle: "produce" },
    ],
  },
  {
    id: "cw-board-cheese-and-crackers-large",
    name: "Cheese and cracker wall, large format",
    course: "board",
    note: "Assembles once, three hours of grazing with no reset.",
    contains: ["dairy", "gluten"],
    formats: ["grazing", "cocktail"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 3,
    counter: 3,
    activeMin: 30,
    servesPerBatch: 24,
    makeAheadDays: 1,
    holdMin: 180,
    season: ["year-round"],
    costPerGuest: 4.9,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Assorted cheese", perGuest: 0.06, unit: "kg", aisle: "dairy" },
      { item: "Crackers", perGuest: 4, unit: "ea", aisle: "bakery" },
      { item: "Honey", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Dried apricots", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "cw-board-no-nut-crudite",
    name: "No-nut crudité wall with three dips",
    course: "board",
    note: "Safe for a nut-free room, cuts ahead and holds crisp in ice water.",
    contains: [],
    formats: ["grazing", "cocktail", "buffet"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 35,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 150,
    season: ["spring", "summer"],
    costPerGuest: 2.0,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Carrot", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Cucumber", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Radish", perGuest: 0.05, unit: "kg", aisle: "produce" },
      { item: "Ranch dip", perGuest: 30, unit: "g", aisle: "dairy" },
    ],
  },
  {
    id: "cw-anchor-veggie-burgers",
    name: "Veggie burger patties, griddled",
    course: "anchor",
    note: "Frozen patties, griddled in relays alongside the meat station.",
    contains: ["gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 16,
    makeAheadDays: 0,
    holdMin: 30,
    season: ["summer"],
    costPerGuest: 2.4,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Veggie patties", perGuest: 1, unit: "ea", aisle: "frozen" },
      { item: "Burger buns", perGuest: 1, unit: "ea", aisle: "bakery" },
      { item: "Lettuce", perGuest: 0.05, unit: "ea", aisle: "produce" },
      { item: "Tomato", perGuest: 0.15, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "cw-anchor-hot-dog-station",
    name: "Hot dog station, self-build",
    course: "anchor",
    note: "One grill zone, guests build their own, minimal plating hands.",
    contains: ["meat", "pork", "gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 20,
    makeAheadDays: 0,
    holdMin: 40,
    season: ["summer"],
    costPerGuest: 2.6,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Hot dogs", perGuest: 1.2, unit: "ea", aisle: "protein" },
      { item: "Hot dog buns", perGuest: 1.2, unit: "ea", aisle: "bakery" },
      { item: "Onion relish", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Mustard", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "cw-anchor-jerk-chicken-thighs",
    name: "Jerk chicken thighs, grill batch",
    course: "anchor",
    note: "Marinates two days ahead, grill line moves fast once it's hot.",
    contains: ["meat"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 3,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 16,
    makeAheadDays: 2,
    holdMin: 60,
    season: ["summer"],
    costPerGuest: 4.4,
    method: "grill",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "caribbean",
    ingredients: [
      { item: "Chicken thighs", perGuest: 0.3, unit: "kg", aisle: "protein" },
      { item: "Jerk marinade", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Lime", perGuest: 0.15, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "cw-anchor-no-dairy-curry-vat",
    name: "Coconut vegetable curry, big pot, no dairy",
    course: "anchor",
    note: "One pot, dairy-free base, holds hot on a low burner for hours.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["reception", "dinner"],
    ovenMin: 0,
    burnerMin: 60,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 16,
    makeAheadDays: 2,
    holdMin: 150,
    season: ["autumn", "winter"],
    costPerGuest: 2.9,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "indian",
    ingredients: [
      { item: "Coconut milk", perGuest: 0.1, unit: "L", aisle: "pantry" },
      { item: "Mixed vegetables", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Curry paste", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Basmati rice", perGuest: 0.08, unit: "kg", aisle: "pantry" },
    ],
  },
  {
    id: "cw-hand-caprese-skewers",
    name: "Caprese skewers, one bite",
    course: "starter",
    note: "No cooking at all, skewers ahead and sits at ambient briefly.",
    contains: ["dairy"],
    formats: ["cocktail", "grazing"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 24,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["summer"],
    costPerGuest: 1.7,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "italian",
    ingredients: [
      { item: "Cherry tomatoes", perGuest: 0.06, unit: "kg", aisle: "produce" },
      { item: "Mini mozzarella", perGuest: 0.04, unit: "kg", aisle: "dairy" },
      { item: "Basil leaves", perGuest: 0.01, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "cw-hand-fried-chicken-bites",
    name: "Fried chicken bites, bucket-style",
    course: "starter",
    note: "Fries in relays, holds in a lined basket under a heat lamp.",
    contains: ["meat", "gluten"],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 40,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 45,
    season: ["summer"],
    costPerGuest: 3.3,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Chicken thigh pieces", perGuest: 0.12, unit: "kg", aisle: "protein" },
      { item: "Seasoned flour", perGuest: 30, unit: "g", aisle: "pantry" },
      { item: "Buttermilk", perGuest: 30, unit: "ml", aisle: "dairy" },
    ],
  },
  {
    id: "cw-side-baked-beans-pot",
    name: "Baked beans, one big pot",
    course: "side",
    note: "Cooks low and slow beside the grill, needs almost no attention.",
    contains: ["pork"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    ovenMin: 0,
    burnerMin: 90,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 20,
    makeAheadDays: 2,
    holdMin: 150,
    season: ["summer", "autumn"],
    costPerGuest: 1.1,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Tinned haricot beans", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Bacon lardons", perGuest: 0.02, unit: "kg", aisle: "protein" },
      { item: "Brown sugar", perGuest: 6, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "cw-side-grilled-veg-platter",
    name: "Grilled vegetable platter, no-animal",
    course: "side",
    note: "Shares grill space with the meat but finishes first and holds.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 16,
    makeAheadDays: 0,
    holdMin: 90,
    season: ["summer"],
    costPerGuest: 1.9,
    method: "grill",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
    ingredients: [
      { item: "Courgette", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Aubergine", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Bell pepper", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "cw-hand-mini-quiches",
    name: "Mini quiches, oven tray",
    course: "starter",
    note: "Bakes in a single tray, reheats without drying if covered.",
    contains: ["dairy", "gluten", "egg"],
    formats: ["cocktail", "grazing", "buffet"],
    shapes: ["reception", "brunch", "aperitivo"],
    ovenMin: 25,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 24,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["year-round"],
    costPerGuest: 1.4,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "house",
    ingredients: [
      { item: "Frozen mini quiche shells", perGuest: 2, unit: "ea", aisle: "frozen" },
      { item: "Egg", perGuest: 0.2, unit: "ea", aisle: "dairy" },
      { item: "Cream", perGuest: 15, unit: "ml", aisle: "dairy" },
    ],
  },
  {
    id: "cw-hand-bruschetta-bar",
    name: "Bruschetta bar, toast and toppings",
    course: "starter",
    note: "Toasts ahead, toppings self-serve so nothing goes soggy early.",
    contains: ["gluten"],
    formats: ["grazing", "cocktail"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 15,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["summer"],
    costPerGuest: 1.5,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "italian",
    ingredients: [
      { item: "Baguette", perGuest: 0.3, unit: "ea", aisle: "bakery" },
      { item: "Chopped tomato", perGuest: 0.08, unit: "kg", aisle: "produce" },
      { item: "Garlic", perGuest: 0.5, unit: "clove", aisle: "produce" },
      { item: "Basil", perGuest: 0.01, unit: "bunch", aisle: "produce" },
    ],
  },
  {
    id: "cw-drink-lemonade-stand",
    name: "Fresh lemonade, big batch, no alcohol",
    course: "drink",
    note: "Squeezes ahead, sits in a cooler jug, tops up with ice as needed.",
    contains: [],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 20,
    makeAheadDays: 1,
    holdMin: 240,
    season: ["summer"],
    costPerGuest: 0.7,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Lemon", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Sugar", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Still water", perGuest: 0.25, unit: "L", aisle: "drinks" },
    ],
  },
  {
    id: "cw-side-no-pork-baked-beans",
    name: "No-pork baked beans, smoky",
    course: "side",
    note: "Same slow pot as its meaty cousin, smoked paprika does the work instead.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    ovenMin: 0,
    burnerMin: 90,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 20,
    makeAheadDays: 2,
    holdMin: 150,
    season: ["summer", "autumn"],
    costPerGuest: 0.9,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "house",
    ingredients: [
      { item: "Tinned haricot beans", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Smoked paprika", perGuest: 2, unit: "g", aisle: "pantry" },
      { item: "Brown sugar", perGuest: 6, unit: "g", aisle: "pantry" },
    ],
  },
];
