import type { Dish } from "./types";

// Second-wave fixture library. Broadens coverage per occasion shape and service
// style so grazing, cocktail and cookout routes stop borrowing seated-dinner logic.
// Educational fixtures — not tested recipes, not live prices.

export const EXTRA_DISHES: Dish[] = [
  // ---- Anchors ---------------------------------------------------------
  {
    id: "porchetta-shoulder",
    name: "Slow pork shoulder, fennel & orange",
    course: "anchor",
    note: "Overnight oven, pulls apart, feeds a crowd from one tray.",
    contains: ["pork"],
    formats: ["buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 300,
    burnerMin: 0,
    fridgeUnits: 3,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["autumn", "winter"],
    costPerGuest: 7.5,
    method: "roast",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Pork shoulder", perGuest: 0.35, unit: "kg", aisle: "protein" },
      { item: "Fennel seed", perGuest: 2, unit: "g", aisle: "pantry" },
      { item: "Orange", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "whole-fish-tray",
    name: "Whole fish baked on potatoes",
    course: "anchor",
    note: "One tray, twenty-five minutes, dramatic at the table.",
    contains: ["fish"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 35,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 4,
    makeAheadDays: 0,
    holdMin: 20,
    season: ["spring", "summer"],
    costPerGuest: 9,
    method: "bake",
    tempBand: "hot",
    ingredients: [
      { item: "Whole sea bream", perGuest: 0.4, unit: "kg", aisle: "protein" },
      { item: "Waxy potatoes", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Lemon", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "aubergine-parmigiana",
    name: "Aubergine parmigiana",
    course: "anchor",
    note: "Better on day two; oven-only reheat, no last-minute hands.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 55,
    burnerMin: 25,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 55,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 60,
    season: ["summer", "autumn"],
    costPerGuest: 4.2,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Aubergine", perGuest: 0.9, unit: "ea", aisle: "produce" },
      { item: "Passata", perGuest: 0.18, unit: "kg", aisle: "pantry" },
      { item: "Parmesan", perGuest: 25, unit: "g", aisle: "dairy" },
    ],
  },
  {
    id: "dal-makhani",
    name: "Black dal, long-simmered",
    course: "anchor",
    note: "Plant-only, cheap per head, improves for two days.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 150,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 120,
    season: ["year-round"],
    costPerGuest: 2.1,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Black urad dal", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Tinned tomatoes", perGuest: 0.12, unit: "kg", aisle: "pantry" },
      { item: "Ginger", perGuest: 10, unit: "g", aisle: "produce" },
    ],
  },
  {
    id: "grill-butterflied-lamb",
    name: "Butterflied lamb over coals",
    course: "anchor",
    note: "Marinates a day ahead, cooks in twenty minutes outdoors.",
    contains: ["meat"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    ovenMin: 0,
    burnerMin: 0,
    grill: true,
    fridgeUnits: 3,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 7,
    makeAheadDays: 1,
    holdMin: 25,
    season: ["spring", "summer"],
    costPerGuest: 10,
    method: "grill",
    tempBand: "hot",
    outdoorSafe: true,
    ingredients: [
      { item: "Butterflied lamb leg", perGuest: 0.28, unit: "kg", aisle: "protein" },
      { item: "Yoghurt", perGuest: 40, unit: "g", aisle: "dairy" },
      { item: "Cumin", perGuest: 2, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "grill-chicken-skewers",
    name: "Charred chicken skewers",
    course: "anchor",
    note: "Skewered the day before; cooks in batches without a pause.",
    contains: ["meat"],
    formats: ["grazing", "cocktail", "buffet"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    grill: true,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 20,
    season: ["summer"],
    costPerGuest: 5,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    ingredients: [
      { item: "Chicken thigh", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Skewers", perGuest: 2, unit: "ea", aisle: "non-food" },
      { item: "Paprika", perGuest: 2, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "shakshuka-tray",
    name: "Tray shakshuka",
    course: "anchor",
    note: "Brunch anchor; sauce made ahead, eggs cracked at the last minute.",
    contains: ["egg"],
    formats: ["buffet", "seated"],
    shapes: ["brunch"],
    ovenMin: 25,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 15,
    season: ["year-round"],
    costPerGuest: 2.8,
    method: "bake",
    tempBand: "hot",
    ingredients: [
      { item: "Eggs", perGuest: 1.5, unit: "ea", aisle: "dairy" },
      { item: "Peppers", perGuest: 0.6, unit: "ea", aisle: "produce" },
      { item: "Tinned tomatoes", perGuest: 0.15, unit: "kg", aisle: "pantry" },
    ],
  },
  {
    id: "porridge-bar",
    name: "Slow-cooked grain bowl bar",
    course: "anchor",
    note: "Brunch without heat pressure; toppings do the work.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 40,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["autumn", "winter"],
    costPerGuest: 1.8,
    method: "boil",
    tempBand: "warm",
    kidFriendly: true,
    ingredients: [
      { item: "Steel-cut oats", perGuest: 70, unit: "g", aisle: "pantry" },
      { item: "Seasonal fruit", perGuest: 0.7, unit: "ea", aisle: "produce" },
      { item: "Honey", perGuest: 12, unit: "g", aisle: "pantry" },
    ],
  },

  // ---- Boards & starters ----------------------------------------------
  {
    id: "board-cheese-autumn",
    name: "Cheese board with quince & walnut",
    course: "board",
    note: "Zero heat; plated straight from cold thirty minutes before.",
    contains: ["dairy", "nut"],
    formats: ["grazing", "cocktail", "buffet"],
    shapes: ["reception", "aperitivo", "dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 120,
    season: ["autumn", "winter"],
    costPerGuest: 6,
    method: "raw",
    tempBand: "ambient",
    ingredients: [
      { item: "Assorted cheese", perGuest: 70, unit: "g", aisle: "dairy" },
      { item: "Quince paste", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Walnuts", perGuest: 20, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "board-crudite",
    name: "Crudités with two dips",
    course: "board",
    note: "Cold, plant-only, and the one board children reliably eat.",
    contains: [],
    formats: ["grazing", "cocktail", "buffet"],
    shapes: ["reception", "aperitivo", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 150,
    season: ["spring", "summer"],
    costPerGuest: 2.4,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    ingredients: [
      { item: "Raw vegetables", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Tahini", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "board-smoked-fish",
    name: "Smoked fish plate, rye & pickles",
    course: "board",
    note: "Bought in, assembled cold, reads far more expensive than it is.",
    contains: ["fish", "gluten"],
    formats: ["grazing", "cocktail", "seated"],
    shapes: ["brunch", "reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["year-round"],
    costPerGuest: 7,
    method: "raw",
    tempBand: "cold",
    ingredients: [
      { item: "Hot-smoked trout", perGuest: 60, unit: "g", aisle: "protein" },
      { item: "Rye bread", perGuest: 0.15, unit: "ea", aisle: "bakery" },
      { item: "Cornichons", perGuest: 20, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "olives-almonds",
    name: "Warm olives & fried almonds",
    course: "board",
    note: "Five minutes on one burner; the cheapest way to signal a start.",
    contains: ["nut"],
    formats: ["cocktail", "grazing"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["year-round"],
    costPerGuest: 1.6,
    method: "fry",
    tempBand: "warm",
    outdoorSafe: true,
    ingredients: [
      { item: "Olives", perGuest: 40, unit: "g", aisle: "pantry" },
      { item: "Almonds", perGuest: 25, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "gougeres",
    name: "Gougères",
    course: "starter",
    note: "Frozen raw weeks ahead, baked from frozen in twelve minutes.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["cocktail", "grazing"],
    shapes: ["reception", "aperitivo"],
    ovenMin: 14,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 30,
    season: ["autumn", "winter"],
    costPerGuest: 1.5,
    method: "bake",
    tempBand: "hot",
    ingredients: [
      { item: "Gruyère", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Plain flour", perGuest: 25, unit: "g", aisle: "pantry" },
      { item: "Eggs", perGuest: 0.4, unit: "ea", aisle: "dairy" },
    ],
  },
  {
    id: "chilled-soup",
    name: "Chilled tomato & almond soup",
    course: "starter",
    note: "Made two days out, served straight from the fridge in glasses.",
    contains: ["nut"],
    formats: ["seated", "cocktail"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 120,
    season: ["summer"],
    costPerGuest: 2,
    method: "chill",
    tempBand: "cold",
    ingredients: [
      { item: "Ripe tomatoes", perGuest: 0.25, unit: "kg", aisle: "produce" },
      { item: "Blanched almonds", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Sherry vinegar", perGuest: 6, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "citrus-fennel-salad",
    name: "Citrus, fennel & olive salad",
    course: "starter",
    note: "Cuts through a heavy anchor; dressed at the last minute only.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 18,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 30,
    season: ["winter", "spring"],
    costPerGuest: 1.9,
    method: "raw",
    tempBand: "cold",
    ingredients: [
      { item: "Oranges", perGuest: 0.6, unit: "ea", aisle: "produce" },
      { item: "Fennel bulb", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Olives", perGuest: 20, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "devilled-eggs",
    name: "Devilled eggs, crisp shallot",
    course: "starter",
    note: "Boiled a day ahead, filled two hours out, eaten standing.",
    contains: ["egg"],
    formats: ["cocktail", "grazing"],
    shapes: ["reception", "aperitivo", "brunch"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["year-round"],
    costPerGuest: 1.2,
    method: "boil",
    tempBand: "cold",
    kidFriendly: true,
    ingredients: [
      { item: "Eggs", perGuest: 1, unit: "ea", aisle: "dairy" },
      { item: "Shallots", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Mustard", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
  },

  // ---- Sides -----------------------------------------------------------
  {
    id: "roast-roots-extra",
    name: "Roast roots with honey & thyme",
    course: "side",
    note: "Cut the day before; one shelf, one temperature.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 45,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 40,
    season: ["autumn", "winter"],
    costPerGuest: 1.4,
    method: "roast",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Root vegetables", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Honey", perGuest: 8, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "charred-greens",
    name: "Charred greens, chilli & lemon",
    course: "side",
    note: "Two minutes a batch; needs a burner free at service.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 14,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    season: ["spring", "autumn"],
    costPerGuest: 1.6,
    method: "fry",
    tempBand: "hot",
    ingredients: [
      { item: "Greens", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Chilli", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "grain-herb-salad",
    name: "Cracked grain & herb salad",
    course: "side",
    note: "Fully make-ahead, travels outdoors, no cold chain anxiety.",
    contains: ["gluten"],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["cookout", "reception", "brunch"],
    ovenMin: 0,
    burnerMin: 18,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 180,
    season: ["summer"],
    costPerGuest: 1.5,
    method: "boil",
    tempBand: "ambient",
    outdoorSafe: true,
    ingredients: [
      { item: "Bulgur wheat", perGuest: 60, unit: "g", aisle: "pantry" },
      { item: "Herbs", perGuest: 0.3, unit: "bunch", aisle: "produce" },
      { item: "Cucumber", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "potato-gratin-extra",
    name: "Potato gratin",
    course: "side",
    note: "Assembled a day ahead; holds hot for an hour without harm.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 70,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 70,
    season: ["autumn", "winter"],
    costPerGuest: 1.7,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Potatoes", perGuest: 0.25, unit: "kg", aisle: "produce" },
      { item: "Cream", perGuest: 70, unit: "ml", aisle: "dairy" },
    ],
  },
  {
    id: "slaw-vinegar",
    name: "Sharp vinegar slaw",
    course: "side",
    note: "Better after four hours; no fridge panic, no wilting.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 240,
    season: ["summer", "autumn"],
    costPerGuest: 0.9,
    method: "raw",
    tempBand: "cold",
    outdoorSafe: true,
    ingredients: [
      { item: "Cabbage", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Cider vinegar", perGuest: 12, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "white-bean-braise",
    name: "White beans braised with greens",
    course: "side",
    note: "Cheap, plant-only, doubles as an anchor when the budget is tight.",
    contains: [],
    formats: ["buffet", "seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 45,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 18,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    season: ["year-round"],
    costPerGuest: 1.1,
    method: "braise",
    tempBand: "hot",
    ingredients: [
      { item: "Dried white beans", perGuest: 70, unit: "g", aisle: "pantry" },
      { item: "Greens", perGuest: 0.1, unit: "kg", aisle: "produce" },
    ],
  },

  // ---- Bread -----------------------------------------------------------
  {
    id: "flatbread-griddle",
    name: "Griddled flatbreads",
    course: "bread",
    note: "Dough rests overnight; one burner, three minutes a round.",
    contains: ["gluten"],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["dinner", "cookout", "reception"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 3,
    activeMin: 35,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 40,
    season: ["year-round"],
    costPerGuest: 0.7,
    method: "fry",
    tempBand: "warm",
    kidFriendly: true,
    ingredients: [
      { item: "Strong flour", perGuest: 80, unit: "g", aisle: "pantry" },
      { item: "Yoghurt", perGuest: 30, unit: "g", aisle: "dairy" },
    ],
  },
  {
    id: "bought-sourdough",
    name: "Bought sourdough, cultured butter",
    course: "bread",
    note: "Deliberately outsourced. Buys back forty minutes of the day.",
    contains: ["gluten", "dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "brunch", "aperitivo"],
    ovenMin: 8,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 6,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    season: ["year-round"],
    costPerGuest: 1.3,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    ingredients: [
      { item: "Sourdough loaf", perGuest: 0.18, unit: "ea", aisle: "bakery" },
      { item: "Cultured butter", perGuest: 20, unit: "g", aisle: "dairy" },
    ],
  },

  // ---- Sweets ----------------------------------------------------------
  {
    id: "olive-oil-cake",
    name: "Olive oil & citrus cake",
    course: "sweet",
    note: "Baked two days out; keeps better than it does fresh.",
    contains: ["gluten", "egg"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "brunch"],
    ovenMin: 45,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 240,
    season: ["year-round"],
    costPerGuest: 1.2,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    ingredients: [
      { item: "Plain flour", perGuest: 45, unit: "g", aisle: "pantry" },
      { item: "Olive oil", perGuest: 25, unit: "ml", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.25, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "poached-fruit",
    name: "Poached fruit in spiced syrup",
    course: "sweet",
    note: "Cold, plant-only, and the only sweet that needs no oven.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "brunch"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 18,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 240,
    season: ["autumn", "winter"],
    costPerGuest: 1.4,
    method: "boil",
    tempBand: "cold",
    ingredients: [
      { item: "Pears", perGuest: 0.8, unit: "ea", aisle: "produce" },
      { item: "Sugar", perGuest: 30, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "berries-cream",
    name: "Macerated berries, thick cream",
    course: "sweet",
    note: "Fifteen minutes total. Summer does the work.",
    contains: ["dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "cookout", "brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 90,
    season: ["summer"],
    costPerGuest: 2.6,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    ingredients: [
      { item: "Berries", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Double cream", perGuest: 50, unit: "ml", aisle: "dairy" },
    ],
  },
  {
    id: "chocolate-pots",
    name: "Dark chocolate pots",
    course: "sweet",
    note: "Set in the fridge overnight in the serving vessel — no plating.",
    contains: ["dairy", "egg"],
    formats: ["seated", "cocktail"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 3,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 180,
    season: ["autumn", "winter"],
    costPerGuest: 2.2,
    method: "chill",
    tempBand: "cold",
    ingredients: [
      { item: "Dark chocolate", perGuest: 45, unit: "g", aisle: "pantry" },
      { item: "Double cream", perGuest: 60, unit: "ml", aisle: "dairy" },
    ],
  },

  // ---- Drinks ----------------------------------------------------------
  {
    id: "drink-batched-negroni",
    name: "Batched aperitivo, bottled",
    course: "drink",
    note: "Batched and chilled a day ahead; poured, never mixed to order.",
    contains: ["alcohol"],
    formats: ["cocktail", "grazing"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 12,
    makeAheadDays: 2,
    holdMin: 300,
    season: ["year-round"],
    costPerGuest: 3.5,
    method: "chill",
    tempBand: "cold",
    ingredients: [
      { item: "Bitter aperitif", perGuest: 40, unit: "ml", aisle: "drinks" },
      { item: "Vermouth", perGuest: 40, unit: "ml", aisle: "drinks" },
    ],
  },
  {
    id: "drink-shrub",
    name: "Vinegar shrub & soda",
    course: "drink",
    note: "Zero-proof with structure. Syrup keeps for weeks.",
    contains: [],
    formats: ["cocktail", "grazing", "buffet", "seated"],
    shapes: ["aperitivo", "reception", "cookout", "brunch"],
    ovenMin: 0,
    burnerMin: 12,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 12,
    makeAheadDays: 2,
    holdMin: 300,
    season: ["summer"],
    costPerGuest: 1,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    ingredients: [
      { item: "Seasonal fruit", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Soda water", perGuest: 0.25, unit: "bottle", aisle: "drinks" },
      { item: "Cider vinegar", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "drink-hot-punch",
    name: "Warm spiced punch",
    course: "drink",
    note: "One pot on low; refills itself and warms the room.",
    contains: [],
    formats: ["grazing", "buffet", "cocktail"],
    shapes: ["reception", "dinner"],
    ovenMin: 0,
    burnerMin: 40,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 180,
    season: ["winter"],
    costPerGuest: 1.1,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    ingredients: [
      { item: "Apple juice", perGuest: 0.25, unit: "L", aisle: "drinks" },
      { item: "Whole spices", perGuest: 3, unit: "g", aisle: "pantry" },
    ],
  },
];
