import type { Dish } from "./types";

// World cuisines, batch B. Educational planning fixtures — not tested recipes.

export const WORLD_B_DISHES: Dish[] = [
  // ---------- Chinese (zh-) ----------
  {
    id: "zh-red-braised-pork",
    name: "Hong shao rou",
    course: "anchor",
    note: "Simmers covered on one burner; reheats better the next day.",
    contains: ["meat", "pork"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 90,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Pork belly", perGuest: 0.28, unit: "kg", aisle: "protein" },
      { item: "Shaoxing wine", perGuest: 15, unit: "ml", aisle: "pantry" },
      { item: "Dark soy sauce", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Rock sugar", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Ginger", perGuest: 5, unit: "g", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 6,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-mapo-tofu",
    name: "Mapo doufu",
    course: "anchor",
    note: "Finishes in under ten minutes once aromatics are prepped; serve immediately.",
    contains: ["meat", "dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 5,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Silken tofu", perGuest: 0.18, unit: "kg", aisle: "dairy" },
      { item: "Minced pork", perGuest: 0.06, unit: "kg", aisle: "protein" },
      { item: "Doubanjiang", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Sichuan peppercorn", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Spring onion", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 5,
    method: "fry",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-whole-steamed-fish",
    name: "Qing zheng yu",
    course: "anchor",
    note: "Steams flat in a wok insert; carry to table on the steaming plate.",
    contains: ["fish"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 18,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    ingredients: [
      { item: "Whole white fish", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Ginger", perGuest: 6, unit: "g", aisle: "produce" },
      { item: "Light soy sauce", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Spring onion", perGuest: 0.4, unit: "ea", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 8,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-stir-fried-greens",
    name: "Suan chao qingcai",
    course: "side",
    note: "Needs a screaming-hot wok; do this last, right before plating.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 6,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 10,
    ingredients: [
      { item: "Choy sum", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Garlic", perGuest: 2, unit: "clove", aisle: "produce" },
      { item: "Vegetable oil", perGuest: 6, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-egg-fried-rice-classic",
    name: "Dan chao fan",
    course: "side",
    note: "Best made from cold day-old rice; single wok, quick turnover.",
    contains: ["egg"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Cooked rice", perGuest: 0.18, unit: "kg", aisle: "pantry" },
      { item: "Egg", perGuest: 0.5, unit: "ea", aisle: "dairy" },
      { item: "Spring onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Light soy sauce", perGuest: 5, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-hot-sour-soup",
    name: "Suan la tang",
    course: "starter",
    note: "Holds warm on low heat; cornstarch slurry loosens if held too long.",
    contains: ["egg", "gluten"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Wood ear mushroom", perGuest: 4, unit: "g", aisle: "pantry" },
      { item: "Tofu", perGuest: 0.05, unit: "kg", aisle: "dairy" },
      { item: "Egg", perGuest: 0.2, unit: "ea", aisle: "dairy" },
      { item: "Black vinegar", perGuest: 8, unit: "ml", aisle: "pantry" },
      { item: "Cornstarch", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 3,
    method: "boil",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-cucumber-smashed-salad",
    name: "Pai huang gua",
    course: "starter",
    note: "Salts and drains for twenty minutes before dressing; serve cold.",
    contains: [],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Cucumber", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Garlic", perGuest: 1, unit: "clove", aisle: "produce" },
      { item: "Black vinegar", perGuest: 6, unit: "ml", aisle: "pantry" },
      { item: "Sesame oil", perGuest: 3, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 1,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "chinese",
  },
  {
    id: "zh-jiaozi-board",
    name: "Shui jiao",
    course: "board",
    note: "Fold ahead and freeze on a floured tray; boil to order in batches.",
    contains: ["meat", "gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 60,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 30,
    ingredients: [
      { item: "Dumpling wrappers", perGuest: 6, unit: "ea", aisle: "frozen" },
      { item: "Minced pork", perGuest: 0.08, unit: "kg", aisle: "protein" },
      { item: "Napa cabbage", perGuest: 0.06, unit: "kg", aisle: "produce" },
      { item: "Ginger", perGuest: 3, unit: "g", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-scallion-pancake-board",
    name: "Cong you bing",
    course: "bread",
    note: "Dough rests an hour before rolling; pan-fry to order, holds poorly once cold.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 20,
    ingredients: [
      { item: "Plain flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Spring onion", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Vegetable oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-char-siu-bao-board",
    name: "Char siu bao",
    course: "bread",
    note: "Steam in batches in a bamboo stack; do not open the lid mid-steam.",
    contains: ["meat", "gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 40,
    ingredients: [
      { item: "Steamed bun dough", perGuest: 0.08, unit: "kg", aisle: "frozen" },
      { item: "Char siu pork", perGuest: 0.05, unit: "kg", aisle: "protein" },
      { item: "Oyster sauce", perGuest: 5, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-sesame-balls-sweet",
    name: "Jian dui",
    course: "sweet",
    note: "Deep-fries in small batches; oil temperature drops fast, watch recovery time.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 40,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Glutinous rice flour", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Red bean paste", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Sesame seeds", perGuest: 6, unit: "g", aisle: "pantry" },
      { item: "Vegetable oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "chinese",
  },
  {
    id: "zh-osmanthus-jelly",
    name: "Guihua gao",
    course: "sweet",
    note: "Sets in the fridge for at least three hours; unmould just before serving.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 8,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Agar agar", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Osmanthus syrup", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Rock sugar", perGuest: 8, unit: "g", aisle: "pantry" },
    ],
    season: ["summer", "autumn"],
    costPerGuest: 1,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "chinese",
  },
  {
    id: "zh-chrysanthemum-tea-drink",
    name: "Ju hua cha",
    course: "drink",
    note: "Steeps off the heat for five minutes; strain before serving warm or over ice.",
    contains: [],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 8,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Dried chrysanthemum", perGuest: 2, unit: "g", aisle: "pantry" },
      { item: "Rock sugar", perGuest: 6, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1,
    method: "boil",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "chinese",
  },

  // ---------- Persian (fa-) ----------
  {
    id: "fa-ghormeh-sabzi",
    name: "Ghormeh sabzi",
    course: "anchor",
    note: "Herbs fry down slowly first; the stew itself improves after a day in the fridge.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 150,
    fridgeUnits: 3,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Lamb shoulder", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Mixed fresh herbs", perGuest: 0.06, unit: "kg", aisle: "produce" },
      { item: "Dried limes", perGuest: 0.5, unit: "ea", aisle: "pantry" },
      { item: "Red kidney beans", perGuest: 0.05, unit: "kg", aisle: "pantry" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 7,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "persian",
  },
  {
    id: "fa-zereshk-polo-chicken",
    name: "Zereshk polo ba morgh",
    course: "anchor",
    note: "Rice steams covered on low heat for the tahdig; do not lift lid early.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 60,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Basmati rice", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Chicken thighs", perGuest: 0.25, unit: "kg", aisle: "protein" },
      { item: "Barberries", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Saffron", perGuest: 0.05, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 6,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "persian",
  },
  {
    id: "fa-joojeh-kabab",
    name: "Joojeh kabab",
    course: "anchor",
    note: "Marinates a day ahead; needs live fire and turns fast on skewers.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    grill: true,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Chicken thighs", perGuest: 0.24, unit: "kg", aisle: "protein" },
      { item: "Yoghurt", perGuest: 30, unit: "g", aisle: "dairy" },
      { item: "Saffron", perGuest: 0.05, unit: "g", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 6,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "persian",
  },
  {
    id: "fa-mast-o-khiar",
    name: "Mast-o khiar",
    course: "side",
    note: "Best made a couple of hours ahead so flavours settle; keep chilled.",
    contains: ["dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Yoghurt", perGuest: 0.08, unit: "kg", aisle: "dairy" },
      { item: "Cucumber", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Dried mint", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Walnut", perGuest: 6, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "persian",
  },
  {
    id: "fa-sabzi-polo",
    name: "Sabzi polo",
    course: "side",
    note: "Herb-rice steams alongside the main pot; needs its own burner for the final hold.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 40,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 45,
    ingredients: [
      { item: "Basmati rice", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Dill", perGuest: 0.03, unit: "bunch", aisle: "produce" },
      { item: "Parsley", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
    season: ["spring", "summer"],
    costPerGuest: 2,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "persian",
  },
  {
    id: "fa-kashke-bademjan",
    name: "Kashke bademjan",
    course: "starter",
    note: "Aubergine fries and mashes ahead; reheats gently in a low pan before topping.",
    contains: ["dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Aubergine", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Kashk", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Fried onion", perGuest: 15, unit: "g", aisle: "produce" },
      { item: "Dried mint", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["autumn"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "warm",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "persian",
  },
  {
    id: "fa-ash-e-reshteh",
    name: "Ash-e reshteh",
    course: "starter",
    note: "A slow one-pot soup; portion into a warm carrier for a moving buffet line.",
    contains: ["gluten", "dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 90,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Reshteh noodles", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Mixed beans", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Mixed herbs", perGuest: 0.05, unit: "kg", aisle: "produce" },
      { item: "Kashk", perGuest: 15, unit: "g", aisle: "dairy" },
    ],
    season: ["winter"],
    costPerGuest: 3,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "persian",
  },
  {
    id: "fa-sangak-board",
    name: "Sangak",
    course: "bread",
    note: "Best from a bakery same day; warm briefly in the oven before the board goes out.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 8,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 5,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Flatbread", perGuest: 0.6, unit: "ea", aisle: "bakery" },
      { item: "Feta", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Walnut", perGuest: 8, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "persian",
  },
  {
    id: "fa-sabzi-khordan-board",
    name: "Sabzi khordan",
    course: "board",
    note: "Assembles cold with no cooking; wash and dry herbs well ahead to avoid a soggy board.",
    contains: ["dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Radish", perGuest: 2, unit: "ea", aisle: "produce" },
      { item: "Spring onion", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Feta", perGuest: 25, unit: "g", aisle: "dairy" },
      { item: "Walnut", perGuest: 8, unit: "g", aisle: "pantry" },
    ],
    season: ["spring", "summer"],
    costPerGuest: 2,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "persian",
  },
  {
    id: "fa-baklava-sweet",
    name: "Baghlava",
    course: "sweet",
    note: "Bakes a day ahead so syrup can fully soak in before slicing.",
    contains: ["gluten", "nut", "dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 35,
    burnerMin: 8,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 16,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Filo pastry", perGuest: 0.03, unit: "kg", aisle: "frozen" },
      { item: "Pistachio", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Butter", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Sugar syrup", perGuest: 20, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "persian",
  },
  {
    id: "fa-faloodeh-sweet",
    name: "Faloodeh",
    course: "sweet",
    note: "Freezes solid overnight; scrape into cups just before serving so it doesn't slump.",
    contains: [],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 5,
    fridgeUnits: 3,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Vermicelli noodles", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Rosewater", perGuest: 8, unit: "ml", aisle: "pantry" },
      { item: "Lime juice", perGuest: 10, unit: "ml", aisle: "produce" },
      { item: "Sugar", perGuest: 15, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "persian",
  },
  {
    id: "fa-doogh-drink",
    name: "Doogh",
    course: "drink",
    note: "Whisks together minutes before serving; separates if it sits too long unstirred.",
    contains: ["dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 8,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Yoghurt", perGuest: 0.1, unit: "kg", aisle: "dairy" },
      { item: "Sparkling water", perGuest: 0.1, unit: "L", aisle: "drinks" },
      { item: "Dried mint", perGuest: 0.5, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 1,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "persian",
  },

  // ---------- Aegean (ae-) ----------
  {
    id: "ae-whole-grilled-sea-bream",
    name: "Tsipoura sti schara",
    course: "anchor",
    note: "Needs a hot open grill and a fish basket to turn cleanly.",
    contains: ["fish"],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    grill: true,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 4,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Whole sea bream", perGuest: 0.35, unit: "kg", aisle: "protein" },
      { item: "Lemon", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 12, unit: "ml", aisle: "pantry" },
      { item: "Oregano", perGuest: 1, unit: "g", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 9,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "ae-moussaka",
    name: "Moussaka",
    course: "anchor",
    note: "Layers assemble a day ahead; long bake sets the béchamel top for clean slicing.",
    contains: ["meat", "dairy", "egg"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 60,
    burnerMin: 30,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 50,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Aubergine", perGuest: 0.25, unit: "ea", aisle: "produce" },
      { item: "Minced lamb", perGuest: 0.15, unit: "kg", aisle: "protein" },
      { item: "Milk", perGuest: 0.08, unit: "L", aisle: "dairy" },
      { item: "Parmesan", perGuest: 15, unit: "g", aisle: "dairy" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 6,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "aegean",
  },
  {
    id: "ae-souvlaki-skewers",
    name: "Souvlaki",
    course: "anchor",
    note: "Marinates overnight; skewer ahead and store flat on a tray for a fast grill session.",
    contains: ["meat"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    grill: true,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Pork shoulder", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Lemon", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Oregano", perGuest: 1, unit: "g", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 5,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "ae-horiatiki-salad",
    name: "Horiatiki",
    course: "side",
    note: "Cut and dress no more than an hour before service or the vegetables weep.",
    contains: ["dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Tomato", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Cucumber", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Feta", perGuest: 40, unit: "g", aisle: "dairy" },
      { item: "Kalamata olives", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "ae-gigantes-plaki",
    name: "Gigantes plaki",
    course: "side",
    note: "Bakes low and slow; tastes better rested and reheated the next day.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 75,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Giant butter beans", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Tinned tomatoes", perGuest: 0.12, unit: "kg", aisle: "pantry" },
      { item: "Olive oil", perGuest: 12, unit: "ml", aisle: "pantry" },
      { item: "Dill", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "aegean",
  },
  {
    id: "ae-tzatziki-starter",
    name: "Tzatziki",
    course: "starter",
    note: "Best made the night before so garlic and cucumber flavours settle.",
    contains: ["dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Greek yoghurt", perGuest: 0.06, unit: "kg", aisle: "dairy" },
      { item: "Cucumber", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Garlic", perGuest: 0.5, unit: "clove", aisle: "produce" },
      { item: "Olive oil", perGuest: 5, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "ae-spanakopita-triangles",
    name: "Spanakopita",
    course: "starter",
    note: "Folds ahead and freezes raw; bake straight from frozen, adding extra oven time.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 30,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 12,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Filo pastry", perGuest: 0.03, unit: "kg", aisle: "frozen" },
      { item: "Spinach", perGuest: 0.08, unit: "kg", aisle: "produce" },
      { item: "Feta", perGuest: 25, unit: "g", aisle: "dairy" },
      { item: "Egg", perGuest: 0.2, unit: "ea", aisle: "dairy" },
    ],
    season: ["spring", "autumn"],
    costPerGuest: 3,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "ae-pita-board",
    name: "Pita & dips",
    course: "board",
    note: "Warm bread just before the board goes out; dips can sit chilled for hours.",
    contains: ["gluten", "dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 8,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Pita bread", perGuest: 0.7, unit: "ea", aisle: "bakery" },
      { item: "Tzatziki", perGuest: 40, unit: "g", aisle: "dairy" },
      { item: "Hummus", perGuest: 40, unit: "g", aisle: "pantry" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "raw",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "ae-olive-bread-board",
    name: "Eliopsomo",
    course: "bread",
    note: "Bakes best the morning of; a warm oven revives day-old loaves for ten minutes.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 35,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Bread flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Kalamata olives", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "ae-baklava-sweet",
    name: "Baklava",
    course: "sweet",
    note: "Bakes and syrups a day ahead; slices cleaner once fully cooled and set.",
    contains: ["gluten", "nut", "dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 35,
    burnerMin: 8,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 16,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Filo pastry", perGuest: 0.03, unit: "kg", aisle: "frozen" },
      { item: "Walnut", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Butter", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Honey syrup", perGuest: 20, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "aegean",
  },
  {
    id: "ae-loukoumades",
    name: "Loukoumades",
    course: "sweet",
    note: "Fries in small batches to order; honey syrup goes on right before serving so they stay crisp.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 35,
    servesPerBatch: 12,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Plain flour", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Honey", perGuest: 20, unit: "ml", aisle: "pantry" },
      { item: "Cinnamon", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Vegetable oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "aegean",
  },
  {
    id: "ae-ouzo-spritz-drink",
    name: "Ouzo spritz",
    course: "drink",
    note: "Build over ice to order; ouzo clouds fast, mix just before handing over.",
    contains: ["alcohol"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Ouzo", perGuest: 30, unit: "ml", aisle: "drinks" },
      { item: "Sparkling water", perGuest: 60, unit: "ml", aisle: "drinks" },
      { item: "Lemon", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "aegean",
  },

  // ---------- Italian (it-) ----------
  {
    id: "it-osso-buco",
    name: "Osso buco",
    course: "anchor",
    note: "Braises for two hours covered; improves substantially made a day ahead.",
    contains: ["meat"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 120,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Veal shanks", perGuest: 0.35, unit: "kg", aisle: "protein" },
      { item: "White wine", perGuest: 40, unit: "ml", aisle: "drinks" },
      { item: "Carrot", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Celery", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 9,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "italian",
  },
  {
    id: "it-porcini-risotto",
    name: "Risotto ai porcini",
    course: "anchor",
    note: "Needs standing attendance at the burner; cook this last, right before service.",
    contains: ["dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    ingredients: [
      { item: "Arborio rice", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Dried porcini", perGuest: 5, unit: "g", aisle: "pantry" },
      { item: "Parmesan", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "White wine", perGuest: 20, unit: "ml", aisle: "drinks" },
    ],
    season: ["autumn"],
    costPerGuest: 6,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "italian",
  },
  {
    id: "it-margherita-grilled-pizza",
    name: "Pizza margherita alla griglia",
    course: "anchor",
    note: "Dough proves the day before; needs a very hot covered grill to blister the crust.",
    contains: ["gluten", "dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    grill: true,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 4,
    makeAheadDays: 1,
    holdMin: 15,
    ingredients: [
      { item: "Pizza dough", perGuest: 0.15, unit: "kg", aisle: "bakery" },
      { item: "Tomato passata", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Mozzarella", perGuest: 60, unit: "g", aisle: "dairy" },
      { item: "Basil", perGuest: 0.1, unit: "bunch", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 4,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "italian",
  },
  {
    id: "it-caponata-side",
    name: "Caponata",
    course: "side",
    note: "Tastes better a day after cooking, served at room temperature.",
    contains: [],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 180,
    ingredients: [
      { item: "Aubergine", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Celery", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Capers", perGuest: 5, unit: "g", aisle: "pantry" },
      { item: "Red wine vinegar", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "ambient",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "italian",
  },
  {
    id: "it-panzanella-side",
    name: "Panzanella",
    course: "side",
    note: "Bread needs thirty minutes to soften in the dressing before serving; do not over-soak.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Stale bread", perGuest: 0.08, unit: "kg", aisle: "bakery" },
      { item: "Tomato", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Red onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "italian",
  },
  {
    id: "it-burrata-starter",
    name: "Burrata e pomodori",
    course: "starter",
    note: "Assembles cold to order; burrata sits at room temperature for twenty minutes first.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Burrata", perGuest: 0.08, unit: "kg", aisle: "dairy" },
      { item: "Tomato", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
      { item: "Basil", perGuest: 0.05, unit: "bunch", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 4,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "italian",
  },
  {
    id: "it-arancini-starter",
    name: "Arancini",
    course: "starter",
    note: "Shapes ahead from cold risotto and fries to order in small batches.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Cooked risotto rice", perGuest: 0.12, unit: "kg", aisle: "pantry" },
      { item: "Mozzarella", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Breadcrumbs", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Egg", perGuest: 0.3, unit: "ea", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "italian",
  },
  {
    id: "it-antipasto-board",
    name: "Tagliere di antipasti",
    course: "board",
    note: "Assembles cold up to two hours ahead; keep cured meats covered until service.",
    contains: ["meat", "dairy", "gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 120,
    ingredients: [
      { item: "Prosciutto", perGuest: 30, unit: "g", aisle: "protein" },
      { item: "Salami", perGuest: 25, unit: "g", aisle: "protein" },
      { item: "Pecorino", perGuest: 25, unit: "g", aisle: "dairy" },
      { item: "Grissini", perGuest: 2, unit: "ea", aisle: "bakery" },
      { item: "Marinated olives", perGuest: 20, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 5,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "italian",
  },
  {
    id: "it-focaccia-board",
    name: "Focaccia",
    course: "bread",
    note: "Dough rests overnight in the fridge; bakes in one tray and holds well at room temperature.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 25,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 240,
    ingredients: [
      { item: "Bread flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Rosemary", perGuest: 1, unit: "g", aisle: "produce" },
      { item: "Sea salt", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "italian",
  },
  {
    id: "it-tiramisu-sweet",
    name: "Tiramisù",
    course: "sweet",
    note: "Assembles a day ahead; needs a fridge shelf overnight to set the layers properly.",
    contains: ["dairy", "egg", "gluten", "alcohol"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Mascarpone", perGuest: 60, unit: "g", aisle: "dairy" },
      { item: "Ladyfingers", perGuest: 3, unit: "ea", aisle: "bakery" },
      { item: "Espresso", perGuest: 30, unit: "ml", aisle: "drinks" },
      { item: "Cocoa powder", perGuest: 3, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "italian",
  },
  {
    id: "it-panna-cotta-sweet",
    name: "Panna cotta",
    course: "sweet",
    note: "Sets overnight in individual moulds; unmould by briefly dipping in warm water.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Double cream", perGuest: 0.1, unit: "L", aisle: "dairy" },
      { item: "Gelatine", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Sugar", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Mixed berries", perGuest: 30, unit: "g", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "italian",
  },
  {
    id: "it-negroni-drink",
    name: "Negroni",
    course: "drink",
    note: "Batch and chill the spirits ahead; add ice and garnish only at the moment of pouring.",
    contains: ["alcohol"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Gin", perGuest: 25, unit: "ml", aisle: "drinks" },
      { item: "Campari", perGuest: 25, unit: "ml", aisle: "drinks" },
      { item: "Sweet vermouth", perGuest: 25, unit: "ml", aisle: "drinks" },
      { item: "Orange", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "italian",
  },

  // ---------- Nordic (no-) ----------
  {
    id: "no-slow-roast-salmon",
    name: "Ovnsbakt laks",
    course: "anchor",
    note: "Low oven temperature keeps the fish moist; carries well on a single tray.",
    contains: ["fish"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 35,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Salmon side", perGuest: 0.18, unit: "kg", aisle: "protein" },
      { item: "Dill", perGuest: 0.02, unit: "bunch", aisle: "produce" },
      { item: "Lemon", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Butter", perGuest: 8, unit: "g", aisle: "dairy" },
    ],
    season: ["spring", "summer"],
    costPerGuest: 6,
    method: "roast",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "nordic",
  },
  {
    id: "no-braised-reindeer",
    name: "Finnbiff",
    course: "anchor",
    note: "Simmers gently on one burner; the sauce tightens further on standing.",
    contains: ["meat", "dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 60,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 6,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Reindeer or beef strips", perGuest: 0.18, unit: "kg", aisle: "protein" },
      { item: "Double cream", perGuest: 30, unit: "ml", aisle: "dairy" },
      { item: "Juniper berries", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Lingonberry jam", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
    season: ["winter"],
    costPerGuest: 8,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "nordic",
  },
  {
    id: "no-open-fire-mackerel",
    name: "Grillet makrell",
    course: "anchor",
    note: "Needs direct fire and a fish grate to prevent sticking; turns once only.",
    contains: ["fish"],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    grill: true,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    ingredients: [
      { item: "Whole mackerel", perGuest: 0.3, unit: "kg", aisle: "protein" },
      { item: "Butter", perGuest: 8, unit: "g", aisle: "dairy" },
      { item: "Lemon", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 5,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "nordic",
  },
  {
    id: "no-pickled-cucumber-side",
    name: "Agurksalat",
    course: "side",
    note: "Pickles for at least an hour before serving; keeps for several days chilled.",
    contains: [],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Cucumber", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "White vinegar", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Sugar", perGuest: 6, unit: "g", aisle: "pantry" },
      { item: "Dill", perGuest: 0.01, unit: "bunch", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 1,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "nordic",
  },
  {
    id: "no-roasted-root-vegetables",
    name: "Ovnsbakte rotgrønnsaker",
    course: "side",
    note: "Roasts on one tray; toss halfway through for even colour.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 45,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 45,
    ingredients: [
      { item: "Parsnip", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Carrot", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
      { item: "Thyme", perGuest: 1, unit: "g", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 2,
    method: "roast",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "nordic",
  },
  {
    id: "no-gravlax-starter",
    name: "Gravlax",
    course: "starter",
    note: "Cures under weight in the fridge for two days; slice thinly right before serving.",
    contains: ["fish"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 120,
    ingredients: [
      { item: "Salmon side", perGuest: 0.1, unit: "kg", aisle: "protein" },
      { item: "Dill", perGuest: 0.03, unit: "bunch", aisle: "produce" },
      { item: "Sugar", perGuest: 5, unit: "g", aisle: "pantry" },
      { item: "Sea salt", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "nordic",
  },
  {
    id: "no-pea-soup-starter",
    name: "Ärtsoppa",
    course: "starter",
    note: "Simmers a long time on one burner; freezes well and reheats gently.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 90,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Dried yellow peas", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Smoked ham hock", perGuest: 0.05, unit: "kg", aisle: "protein" },
      { item: "Onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Thyme", perGuest: 1, unit: "g", aisle: "produce" },
    ],
    season: ["winter"],
    costPerGuest: 3,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "nordic",
  },
  {
    id: "no-rye-cracker-board",
    name: "Knäckebröd med pålägg",
    course: "board",
    note: "Assembles cold at the last minute; crackers go soft quickly once topped.",
    contains: ["gluten", "dairy", "fish"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Rye crackers", perGuest: 3, unit: "ea", aisle: "bakery" },
      { item: "Cream cheese", perGuest: 30, unit: "g", aisle: "dairy" },
      { item: "Smoked fish", perGuest: 25, unit: "g", aisle: "protein" },
      { item: "Pickled red onion", perGuest: 10, unit: "g", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "nordic",
  },
  {
    id: "no-rye-bread-board",
    name: "Rugbrød",
    course: "bread",
    note: "Bakes a day or two ahead; flavour and texture improve after a rest wrapped in a cloth.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 55,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Rye flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Sunflower seeds", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Molasses", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "nordic",
  },
  {
    id: "no-cardamom-buns-sweet",
    name: "Kardemummabullar",
    course: "sweet",
    note: "Dough proves twice; bake in one tray shortly before guests arrive for the smell alone.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "brunch", "reception"],
    ovenMin: 18,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Plain flour", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Butter", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Ground cardamom", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Pearl sugar", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "nordic",
  },
  {
    id: "no-cloudberry-cream-sweet",
    name: "Multekrem",
    course: "sweet",
    note: "Whips just before serving; cloudberries can be folded in a few hours ahead and chilled.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Double cream", perGuest: 0.08, unit: "L", aisle: "dairy" },
      { item: "Cloudberries", perGuest: 40, unit: "g", aisle: "frozen" },
      { item: "Sugar", perGuest: 10, unit: "g", aisle: "pantry" },
    ],
    season: ["autumn"],
    costPerGuest: 4,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "nordic",
  },
  {
    id: "no-glogg-drink",
    name: "Glögg",
    course: "drink",
    note: "Warms gently on one burner; do not let it boil or the alcohol cooks off harshly.",
    contains: ["alcohol"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Red wine", perGuest: 0.12, unit: "L", aisle: "drinks" },
      { item: "Cinnamon stick", perGuest: 0.2, unit: "ea", aisle: "pantry" },
      { item: "Orange", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Almonds", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
    season: ["winter"],
    costPerGuest: 3,
    method: "boil",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "nordic",
  },

  // ---------- Caribbean (cb-) ----------
  {
    id: "cb-jerk-chicken",
    name: "Jerk chicken",
    course: "anchor",
    note: "Marinates at least a day ahead; needs indirect heat on the grill to cook through without charring.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    grill: true,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Chicken thighs", perGuest: 0.28, unit: "kg", aisle: "protein" },
      { item: "Scotch bonnet", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Allspice", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Lime", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 5,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "caribbean",
  },
  {
    id: "cb-curry-goat",
    name: "Curry goat",
    course: "anchor",
    note: "Simmers slowly on one burner for over two hours; better the next day.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 150,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Goat shoulder", perGuest: 0.25, unit: "kg", aisle: "protein" },
      { item: "Curry powder", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Scotch bonnet", perGuest: 0.05, unit: "ea", aisle: "produce" },
      { item: "Thyme", perGuest: 1, unit: "g", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 7,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "caribbean",
  },
  {
    id: "cb-escovitch-fish",
    name: "Escovitch fish",
    course: "anchor",
    note: "Fries whole and tops with hot pickled vegetables; best served within the hour.",
    contains: ["fish"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Whole snapper", perGuest: 0.3, unit: "kg", aisle: "protein" },
      { item: "Scotch bonnet", perGuest: 0.05, unit: "ea", aisle: "produce" },
      { item: "Carrot", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "White vinegar", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 7,
    method: "fry",
    tempBand: "warm",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "caribbean",
  },
  {
    id: "cb-rice-and-peas",
    name: "Rice and peas",
    course: "side",
    note: "Cooks in coconut milk on one burner; holds warm covered for a while without drying out.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 35,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Rice", perGuest: 0.09, unit: "kg", aisle: "pantry" },
      { item: "Kidney beans", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Coconut milk", perGuest: 60, unit: "ml", aisle: "pantry" },
      { item: "Thyme", perGuest: 1, unit: "g", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "caribbean",
  },
  {
    id: "cb-fried-plantain-side",
    name: "Fried sweet plantain",
    course: "side",
    note: "Fries in batches to order; ripe plantains char fast, watch the pan closely.",
    contains: [],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Ripe plantain", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Vegetable oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "caribbean",
  },
  {
    id: "cb-saltfish-fritters",
    name: "Stamp and go",
    course: "starter",
    note: "Fritter batter can rest ahead; fry to order so they stay crisp.",
    contains: ["fish", "gluten", "egg"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 20,
    ingredients: [
      { item: "Salt cod", perGuest: 0.05, unit: "kg", aisle: "protein" },
      { item: "Plain flour", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Scotch bonnet", perGuest: 0.03, unit: "ea", aisle: "produce" },
      { item: "Egg", perGuest: 0.2, unit: "ea", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "caribbean",
  },
  {
    id: "cb-callaloo-starter",
    name: "Callaloo",
    course: "starter",
    note: "Simmers quickly on one burner; holds warm but greens darken if left too long.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Callaloo greens", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Coconut milk", perGuest: 40, unit: "ml", aisle: "pantry" },
      { item: "Scotch bonnet", perGuest: 0.03, unit: "ea", aisle: "produce" },
      { item: "Onion", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "caribbean",
  },
  {
    id: "cb-festival-board",
    name: "Festival & fried fish board",
    course: "board",
    note: "Fries in two stages; festival dough proves for thirty minutes before frying.",
    contains: ["gluten", "fish"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Cornmeal", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Plain flour", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Fried fish fillet", perGuest: 0.1, unit: "kg", aisle: "protein" },
      { item: "Vegetable oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 4,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "caribbean",
  },
  {
    id: "cb-coco-bread-board",
    name: "Coco bread",
    course: "bread",
    note: "Bakes fast in a hot oven; best served warm within the hour.",
    contains: ["gluten", "dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 15,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Bread flour", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Coconut milk", perGuest: 20, unit: "ml", aisle: "pantry" },
      { item: "Butter", perGuest: 8, unit: "g", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "caribbean",
  },
  {
    id: "cb-rum-cake-sweet",
    name: "Black cake",
    course: "sweet",
    note: "Fruit soaks in rum for weeks ahead if possible; bakes slowly and keeps for days wrapped.",
    contains: ["gluten", "egg", "dairy", "alcohol"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 90,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 14,
    makeAheadDays: 2,
    holdMin: 480,
    ingredients: [
      { item: "Dried mixed fruit", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Dark rum", perGuest: 20, unit: "ml", aisle: "drinks" },
      { item: "Butter", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Egg", perGuest: 0.3, unit: "ea", aisle: "dairy" },
    ],
    season: ["winter"],
    costPerGuest: 3,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "caribbean",
  },
  {
    id: "cb-fried-dumpling-sweet",
    name: "Sweet fried dumplings",
    course: "sweet",
    note: "Fries in batches to order; oil temperature matters for even browning without raw centres.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Plain flour", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Sugar", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Vegetable oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "caribbean",
  },
  {
    id: "cb-rum-punch-drink",
    name: "Rum punch",
    course: "drink",
    note: "Batches ahead and chills for hours; add ice and a grate of nutmeg only at service.",
    contains: ["alcohol"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "reception", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Dark rum", perGuest: 40, unit: "ml", aisle: "drinks" },
      { item: "Orange juice", perGuest: 60, unit: "ml", aisle: "drinks" },
      { item: "Grenadine", perGuest: 10, unit: "ml", aisle: "drinks" },
      { item: "Lime", perGuest: 0.15, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "caribbean",
  },
];
