import type { Dish } from "./types";

// World cuisine set A. Educational planning fixtures — not tested recipes,
// not costed, not certified for food-service use.

export const WORLD_A_DISHES: Dish[] = [
  // ===== Mexican (mx-) =====
  {
    id: "mx-tinga-pollo",
    name: "Tinga de pollo",
    course: "anchor",
    note: "Simmers on one burner and holds warm without drying out.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 45,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Chicken thigh", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Chipotle in adobo", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Tomato", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "White onion", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 6,
    method: "braise",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "mx-carne-asada",
    name: "Carne asada",
    course: "anchor",
    note: "Needs live fire; cooks in minutes right before service.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 15,
    ingredients: [
      { item: "Skirt steak", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Lime", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Garlic", perGuest: 1, unit: "clove", aisle: "produce" },
      { item: "Cilantro", perGuest: 0.05, unit: "bunch", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 9,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "mx-mole-negro",
    name: "Mole negro con pollo",
    course: "anchor",
    note: "Sauce base can be made two days ahead; oven only for finishing chicken.",
    contains: ["nut"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 40,
    burnerMin: 60,
    fridgeUnits: 3,
    counter: 2,
    activeMin: 60,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 60,
    ingredients: [
      { item: "Chicken leg", perGuest: 0.3, unit: "kg", aisle: "protein" },
      { item: "Dried chiles, mixed", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Chocolate, dark", perGuest: 6, unit: "g", aisle: "pantry" },
      { item: "Almonds", perGuest: 6, unit: "g", aisle: "pantry" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 8,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "mexican",
  },
  {
    id: "mx-elote-asado",
    name: "Elote asado",
    course: "side",
    note: "Grills alongside a main protein; finishes in under ten minutes.",
    contains: ["dairy"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Corn on the cob", perGuest: 1, unit: "ea", aisle: "produce" },
      { item: "Mayonnaise", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Cotija cheese", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Chile powder", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "mx-frijoles-charros",
    name: "Frijoles charros",
    course: "side",
    note: "Single pot simmer, holds well on low heat through service.",
    contains: ["pork"],
    formats: ["buffet"],
    shapes: ["cookout", "dinner"],
    ovenMin: 0,
    burnerMin: 90,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Pinto beans, dried", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Bacon", perGuest: 0.03, unit: "kg", aisle: "protein" },
      { item: "Tomato", perGuest: 0.08, unit: "kg", aisle: "produce" },
      { item: "Jalapeño", perGuest: 0.1, unit: "ea", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "braise",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "mx-ceviche-verde",
    name: "Ceviche verde",
    course: "starter",
    note: "Fish cures in citrus for thirty minutes; must stay cold until serving.",
    contains: ["fish"],
    formats: ["seated", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 45,
    ingredients: [
      { item: "White fish fillet", perGuest: 0.09, unit: "kg", aisle: "protein" },
      { item: "Lime", perGuest: 1, unit: "ea", aisle: "produce" },
      { item: "Serrano chile", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Cilantro", perGuest: 0.03, unit: "bunch", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 7,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "mexican",
  },
  {
    id: "mx-esquites",
    name: "Esquites",
    course: "starter",
    note: "Cooked in one pan and served warm in cups; no oven needed.",
    contains: ["dairy"],
    formats: ["grazing", "buffet"],
    shapes: ["cookout", "aperitivo"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Corn kernels", perGuest: 0.15, unit: "kg", aisle: "frozen" },
      { item: "Crema", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Cotija cheese", perGuest: 10, unit: "g", aisle: "dairy" },
      { item: "Lime", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "mx-tortillas-board",
    name: "Tortillas y salsas",
    course: "board",
    note: "Warmed in batches on the burner just before guests arrive.",
    contains: ["gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Corn tortillas", perGuest: 3, unit: "ea", aisle: "bakery" },
      { item: "Salsa roja", perGuest: 30, unit: "g", aisle: "pantry" },
      { item: "Salsa verde", perGuest: 30, unit: "g", aisle: "pantry" },
      { item: "Pickled onion", perGuest: 20, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "grill",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },
  {
    id: "mx-queso-fundido",
    name: "Queso fundido",
    course: "board",
    note: "Bakes in one dish and must be served within minutes of leaving the oven.",
    contains: ["dairy", "pork"],
    formats: ["grazing"],
    shapes: ["aperitivo"],
    ovenMin: 15,
    burnerMin: 5,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    ingredients: [
      { item: "Oaxaca cheese", perGuest: 0.08, unit: "kg", aisle: "dairy" },
      { item: "Chorizo", perGuest: 0.04, unit: "kg", aisle: "protein" },
      { item: "Corn tortillas", perGuest: 2, unit: "ea", aisle: "bakery" },
    ],
    season: ["year-round"],
    costPerGuest: 5,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "mexican",
  },
  {
    id: "mx-tres-leches",
    name: "Pastel de tres leches",
    course: "sweet",
    note: "Bakes a day ahead and needs an overnight soak in the fridge.",
    contains: ["dairy", "egg", "gluten"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 35,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Flour", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Eggs", perGuest: 0.5, unit: "ea", aisle: "dairy" },
      { item: "Evaporated milk", perGuest: 30, unit: "ml", aisle: "pantry" },
      { item: "Condensed milk", perGuest: 30, unit: "ml", aisle: "pantry" },
      { item: "Cream, whipping", perGuest: 20, unit: "ml", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "bake",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "mexican",
  },
  {
    id: "mx-churros",
    name: "Churros con chocolate",
    course: "sweet",
    note: "Fried to order in small batches; does not hold once cooled.",
    contains: ["gluten", "egg"],
    formats: ["grazing"],
    shapes: ["cookout", "aperitivo"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 10,
    ingredients: [
      { item: "Flour", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Sugar", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Dark chocolate", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Frying oil", perGuest: 20, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "mexican",
  },
  {
    id: "mx-agua-fresca",
    name: "Agua fresca de sandía",
    course: "drink",
    note: "Blended and chilled ahead; no cooking equipment required.",
    contains: [],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["cookout", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Watermelon", perGuest: 0.3, unit: "kg", aisle: "produce" },
      { item: "Lime", perGuest: 0.2, unit: "ea", aisle: "produce" },
      { item: "Sugar", perGuest: 0.01, unit: "kg", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "mexican",
  },

  // ===== Levantine (lv-) =====
  {
    id: "lv-shish-taouk",
    name: "Shish taouk",
    course: "anchor",
    note: "Marinates a day ahead; needs direct fire for eight minutes.",
    contains: ["dairy"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 20,
    ingredients: [
      { item: "Chicken thigh", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Yoghurt", perGuest: 30, unit: "g", aisle: "dairy" },
      { item: "Garlic", perGuest: 1, unit: "clove", aisle: "produce" },
      { item: "Lemon", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 6,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "lv-lamb-kofta",
    name: "Kofta bil siniyeh",
    course: "anchor",
    note: "Bakes in one tray with the sauce; holds well covered on low heat.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 40,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Lamb, minced", perGuest: 0.18, unit: "kg", aisle: "protein" },
      { item: "Tahini", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Tomato", perGuest: 0.1, unit: "kg", aisle: "produce" },
      { item: "Pine nuts", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 7,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "levantine",
  },
  {
    id: "lv-maqluba",
    name: "Maqluba",
    course: "anchor",
    note: "Layers cook slowly then invert onto a platter; assemble a day ahead if flipping day-of.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 75,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Rice", perGuest: 0.09, unit: "kg", aisle: "pantry" },
      { item: "Eggplant", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Chicken thigh", perGuest: 0.18, unit: "kg", aisle: "protein" },
      { item: "Cauliflower", perGuest: 0.1, unit: "kg", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 7,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "levantine",
  },
  {
    id: "lv-fattoush",
    name: "Fattoush",
    course: "side",
    note: "Assembled cold; toss the fried bread in only just before serving.",
    contains: ["gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Pita bread", perGuest: 0.3, unit: "ea", aisle: "bakery" },
      { item: "Cucumber", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Tomato", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Sumac", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "lv-mujadara",
    name: "Mujaddara",
    course: "side",
    note: "One-pot lentils and rice; onions fry separately and top just before serving.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 45,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Green lentils", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Rice", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Onion", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 2,
    method: "boil",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "lv-hummus-topped",
    name: "Hummus bi lahme",
    course: "starter",
    note: "Hummus base holds refrigerated for two days; topping fried to order.",
    contains: ["meat"],
    formats: ["seated", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 45,
    ingredients: [
      { item: "Chickpeas, cooked", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Tahini", perGuest: 25, unit: "g", aisle: "pantry" },
      { item: "Lamb, minced", perGuest: 0.05, unit: "kg", aisle: "protein" },
      { item: "Pine nuts", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "raw",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "levantine",
  },
  {
    id: "lv-labneh-zaatar",
    name: "Labneh bi zaatar",
    course: "starter",
    note: "Yoghurt strains overnight in the fridge; assemble cold at the last minute.",
    contains: ["dairy"],
    formats: ["grazing", "buffet"],
    shapes: ["aperitivo", "brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Yoghurt, full-fat", perGuest: 0.08, unit: "kg", aisle: "dairy" },
      { item: "Za'atar", perGuest: 3, unit: "g", aisle: "pantry" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "lv-mezze-board",
    name: "Mezze board",
    course: "board",
    note: "Fully cold assembly; needs a large counter footprint to lay out.",
    contains: ["gluten", "dairy"],
    formats: ["grazing", "cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 30,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Pita bread", perGuest: 0.5, unit: "ea", aisle: "bakery" },
      { item: "Olives", perGuest: 30, unit: "g", aisle: "pantry" },
      { item: "Feta", perGuest: 30, unit: "g", aisle: "dairy" },
      { item: "Stuffed grape leaves", perGuest: 2, unit: "ea", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 5,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "lv-manakish-zaatar",
    name: "Manakish za'atar",
    course: "bread",
    note: "Dough proves ahead; bakes in a hot oven in batches just before guests arrive.",
    contains: ["gluten"],
    formats: ["buffet", "grazing"],
    shapes: ["brunch", "aperitivo"],
    ovenMin: 20,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Za'atar", perGuest: 6, unit: "g", aisle: "pantry" },
      { item: "Olive oil", perGuest: 12, unit: "ml", aisle: "pantry" },
      { item: "Yeast", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "levantine",
  },
  {
    id: "lv-lahm-baajin",
    name: "Lahm b'ajeen",
    course: "bread",
    note: "Small flatbreads bake in short batches; freezer-friendly ahead of time.",
    contains: ["meat", "gluten"],
    formats: ["grazing", "buffet"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 25,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 40,
    ingredients: [
      { item: "Lamb, minced", perGuest: 0.06, unit: "kg", aisle: "protein" },
      { item: "Flour", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Tomato paste", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Pomegranate molasses", perGuest: 3, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "levantine",
  },
  {
    id: "lv-baklava",
    name: "Baklava",
    course: "sweet",
    note: "Baked and syruped a day ahead; improves once fully rested.",
    contains: ["nut", "gluten", "dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 35,
    burnerMin: 10,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 16,
    makeAheadDays: 2,
    holdMin: 300,
    ingredients: [
      { item: "Filo pastry", perGuest: 0.04, unit: "kg", aisle: "frozen" },
      { item: "Walnuts", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Butter", perGuest: 0.02, unit: "kg", aisle: "dairy" },
      { item: "Sugar syrup", perGuest: 20, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },
  {
    id: "lv-atayef",
    name: "Atayef bil ashta",
    course: "sweet",
    note: "Pancakes cook on a flat pan and are filled cold; do not stack while warm.",
    contains: ["gluten", "dairy", "nut"],
    formats: ["grazing"],
    shapes: ["aperitivo"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Flour", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Ashta cream", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Pistachios", perGuest: 5, unit: "g", aisle: "pantry" },
      { item: "Sugar syrup", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "levantine",
  },
  {
    id: "lv-jallab",
    name: "Jallab",
    course: "drink",
    note: "Syrup dilutes to order over ice; keep the syrup cold and separate until service.",
    contains: ["nut"],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Jallab syrup", perGuest: 30, unit: "ml", aisle: "pantry" },
      { item: "Pine nuts", perGuest: 3, unit: "g", aisle: "pantry" },
      { item: "Ice", perGuest: 0.1, unit: "kg", aisle: "non-food" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "levantine",
  },

  // ===== West African (wa-) =====
  {
    id: "wa-jollof-rice",
    name: "Jollof rice",
    course: "anchor",
    note: "One large pot; needs a wide burner and patience for the base sauce.",
    contains: [],
    formats: ["buffet"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 60,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Long-grain rice", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Tomato", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Red bell pepper", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Scotch bonnet", perGuest: 0.05, unit: "ea", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "west-african",
  },
  {
    id: "wa-suya-skewers",
    name: "Suya",
    course: "anchor",
    note: "Grilled fast over live heat; spice mix must be prepared well ahead.",
    contains: ["nut"],
    formats: ["grazing", "buffet"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 20,
    ingredients: [
      { item: "Beef, sliced thin", perGuest: 0.18, unit: "kg", aisle: "protein" },
      { item: "Suya spice (yaji)", perGuest: 6, unit: "g", aisle: "pantry" },
      { item: "Peanuts, ground", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Onion", perGuest: 0.15, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 6,
    method: "grill",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "west-african",
  },
  {
    id: "wa-egusi-stew",
    name: "Egusi soup",
    course: "anchor",
    note: "Long stovetop simmer; thickens further on standing, thin with stock to serve.",
    contains: ["meat", "fish"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 75,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Egusi (ground melon seed)", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Goat meat", perGuest: 0.15, unit: "kg", aisle: "protein" },
      { item: "Smoked fish", perGuest: 0.05, unit: "kg", aisle: "protein" },
      { item: "Spinach", perGuest: 0.08, unit: "kg", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 7,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "west-african",
  },
  {
    id: "wa-fried-plantain",
    name: "Dodo",
    course: "side",
    note: "Fried to order in small batches; loses texture if held too long.",
    contains: [],
    formats: ["buffet", "grazing"],
    shapes: ["dinner", "cookout"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Ripe plantain", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Frying oil", perGuest: 20, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "west-african",
  },
  {
    id: "wa-moin-moin",
    name: "Moin moin",
    course: "side",
    note: "Steams in individual wraps or ramekins; can be steamed a day ahead and reheated.",
    contains: ["fish", "egg"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 60,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Black-eyed peas", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Red bell pepper", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Egg, boiled", perGuest: 0.3, unit: "ea", aisle: "dairy" },
      { item: "Palm oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "boil",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "west-african",
  },
  {
    id: "wa-akara",
    name: "Akara",
    course: "starter",
    note: "Batter rests before frying; serve hot straight from the pan.",
    contains: [],
    formats: ["grazing", "buffet"],
    shapes: ["brunch", "aperitivo"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Black-eyed peas", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Onion", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Frying oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "west-african",
  },
  {
    id: "wa-pepper-soup",
    name: "Pepper soup",
    course: "starter",
    note: "Light broth simmers quickly; serve hot in small cups as a starter.",
    contains: ["meat"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 40,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Goat meat", perGuest: 0.1, unit: "kg", aisle: "protein" },
      { item: "Pepper soup spice", perGuest: 3, unit: "g", aisle: "pantry" },
      { item: "Scent leaf", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
    season: ["winter"],
    costPerGuest: 4,
    method: "boil",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "west-african",
  },
  {
    id: "wa-chin-chin-board",
    name: "Chin chin & small chops",
    course: "board",
    note: "Fried snacks made well ahead; stores at room temperature in a sealed tin.",
    contains: ["gluten", "egg"],
    formats: ["grazing", "cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 0,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 16,
    makeAheadDays: 2,
    holdMin: 480,
    ingredients: [
      { item: "Flour", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Sugar", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Nutmeg", perGuest: 0.2, unit: "g", aisle: "pantry" },
      { item: "Frying oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "west-african",
  },
  {
    id: "wa-puff-puff",
    name: "Puff-puff",
    course: "bread",
    note: "Dough proves for an hour, then fries in batches; best eaten warm.",
    contains: ["gluten"],
    formats: ["grazing"],
    shapes: ["aperitivo", "brunch"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 12,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Flour", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Yeast", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Sugar", perGuest: 0.01, unit: "kg", aisle: "pantry" },
      { item: "Frying oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 1,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "west-african",
  },
  {
    id: "wa-agege-bread",
    name: "Agege bread & butter",
    course: "bread",
    note: "Store-bought or baked ahead; slices and toasts to order on the burner.",
    contains: ["gluten", "dairy"],
    formats: ["buffet"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Agege bread", perGuest: 0.1, unit: "kg", aisle: "bakery" },
      { item: "Butter", perGuest: 15, unit: "g", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 1,
    method: "grill",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "west-african",
  },
  {
    id: "wa-chinchin-cake",
    name: "Puff-puff donut cake",
    course: "sweet",
    note: "Bakes as a single tray cake; cools before slicing to hold shape.",
    contains: ["gluten", "egg", "dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "brunch"],
    ovenMin: 45,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Flour", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Eggs", perGuest: 0.4, unit: "ea", aisle: "dairy" },
      { item: "Butter", perGuest: 0.02, unit: "kg", aisle: "dairy" },
      { item: "Sugar", perGuest: 0.03, unit: "kg", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "west-african",
  },
  {
    id: "wa-zobo-drink",
    name: "Zobo",
    course: "drink",
    note: "Steeped and chilled a day ahead; serve cold over ice.",
    contains: [],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 240,
    ingredients: [
      { item: "Dried hibiscus (zobo leaves)", perGuest: 0.01, unit: "kg", aisle: "pantry" },
      { item: "Ginger", perGuest: 3, unit: "g", aisle: "produce" },
      { item: "Sugar", perGuest: 0.015, unit: "kg", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 1,
    method: "boil",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "west-african",
  },

  // ===== Japanese (jp-) =====
  {
    id: "jp-teriyaki-salmon",
    name: "Sake no teriyaki",
    course: "anchor",
    note: "Pan-glazes in minutes; do not walk away once the sauce reduces.",
    contains: ["fish", "gluten"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    ingredients: [
      { item: "Salmon fillet", perGuest: 0.16, unit: "kg", aisle: "protein" },
      { item: "Soy sauce", perGuest: 15, unit: "ml", aisle: "pantry" },
      { item: "Mirin", perGuest: 10, unit: "ml", aisle: "pantry" },
      { item: "Sugar", perGuest: 5, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 8,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-yakitori",
    name: "Yakitori",
    course: "anchor",
    note: "Grills directly over charcoal; small batches keep the fire manageable.",
    contains: ["gluten"],
    formats: ["grazing", "buffet"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 15,
    ingredients: [
      { item: "Chicken thigh", perGuest: 0.15, unit: "kg", aisle: "protein" },
      { item: "Scallion", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Tare sauce", perGuest: 20, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 5,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "japanese",
  },
  {
    id: "jp-katsu-curry",
    name: "Katsu karē",
    course: "anchor",
    note: "Curry base cooks ahead; cutlets fry fresh at the last moment.",
    contains: ["gluten", "egg"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 40,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Pork loin", perGuest: 0.15, unit: "kg", aisle: "protein" },
      { item: "Curry roux blocks", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Panko breadcrumbs", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Carrot", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 6,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-agedashi-tofu",
    name: "Agedashi dōfu",
    course: "side",
    note: "Fried just before serving; sauce is made ahead and reheated gently.",
    contains: ["gluten", "fish"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 10,
    ingredients: [
      { item: "Silken tofu", perGuest: 0.1, unit: "kg", aisle: "protein" },
      { item: "Potato starch", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Dashi", perGuest: 40, unit: "ml", aisle: "pantry" },
      { item: "Bonito flakes", perGuest: 2, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-sunomono",
    name: "Sunomono",
    course: "side",
    note: "Cold vinegared salad; dress no more than thirty minutes before serving.",
    contains: ["shellfish"],
    formats: ["seated", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Cucumber", perGuest: 0.15, unit: "ea", aisle: "produce" },
      { item: "Cooked shrimp", perGuest: 0.04, unit: "kg", aisle: "protein" },
      { item: "Rice vinegar", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "japanese",
  },
  {
    id: "jp-gyoza",
    name: "Gyōza",
    course: "starter",
    note: "Fold ahead and freeze; pan-fry with a steam lid just before serving.",
    contains: ["gluten", "pork"],
    formats: ["seated", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 15,
    ingredients: [
      { item: "Pork, minced", perGuest: 0.06, unit: "kg", aisle: "protein" },
      { item: "Gyoza wrappers", perGuest: 4, unit: "ea", aisle: "frozen" },
      { item: "Cabbage", perGuest: 0.05, unit: "kg", aisle: "produce" },
      { item: "Garlic", perGuest: 0.5, unit: "clove", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-chawanmushi",
    name: "Chawanmushi",
    course: "starter",
    note: "Steamed gently in individual cups; overcooking splits the custard.",
    contains: ["egg", "fish", "shellfish"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 20,
    ingredients: [
      { item: "Eggs", perGuest: 1, unit: "ea", aisle: "dairy" },
      { item: "Dashi", perGuest: 80, unit: "ml", aisle: "pantry" },
      { item: "Shrimp", perGuest: 0.02, unit: "kg", aisle: "protein" },
      { item: "Shiitake mushroom", perGuest: 0.5, unit: "ea", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "boil",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-sashimi-board",
    name: "Sashimi moriawase",
    course: "board",
    note: "Cut cold to order; must stay refrigerated until minutes before serving.",
    contains: ["fish"],
    formats: ["seated", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Sashimi-grade tuna", perGuest: 0.06, unit: "kg", aisle: "protein" },
      { item: "Sashimi-grade salmon", perGuest: 0.06, unit: "kg", aisle: "protein" },
      { item: "Daikon", perGuest: 0.03, unit: "kg", aisle: "produce" },
      { item: "Wasabi", perGuest: 2, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 14,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-onigiri-board",
    name: "Onigiri board",
    course: "board",
    note: "Shape while rice is warm, wrap in nori just before serving so it stays crisp.",
    contains: ["fish"],
    formats: ["grazing", "buffet"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Short-grain rice", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Nori sheets", perGuest: 1, unit: "ea", aisle: "pantry" },
      { item: "Salted salmon flake", perGuest: 15, unit: "g", aisle: "protein" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "boil",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "japanese",
  },
  {
    id: "jp-milk-bread",
    name: "Shokupan",
    course: "bread",
    note: "Enriched loaf proves twice; bake the morning of and slice once cooled.",
    contains: ["gluten", "dairy", "egg"],
    formats: ["seated", "buffet"],
    shapes: ["brunch", "dinner"],
    ovenMin: 30,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 240,
    ingredients: [
      { item: "Bread flour", perGuest: 0.05, unit: "kg", aisle: "pantry" },
      { item: "Milk", perGuest: 20, unit: "ml", aisle: "dairy" },
      { item: "Butter", perGuest: 10, unit: "g", aisle: "dairy" },
      { item: "Eggs", perGuest: 0.2, unit: "ea", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-dorayaki",
    name: "Dorayaki",
    course: "sweet",
    note: "Pancakes cook on a flat griddle and are filled once fully cooled.",
    contains: ["gluten", "egg"],
    formats: ["grazing"],
    shapes: ["aperitivo", "brunch"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 240,
    ingredients: [
      { item: "Flour", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Eggs", perGuest: 0.3, unit: "ea", aisle: "dairy" },
      { item: "Red bean paste", perGuest: 30, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-mochi-icecream",
    name: "Mochi aisu",
    course: "sweet",
    note: "Store-bought or shaped ahead and frozen solid; plate straight from the freezer.",
    contains: ["dairy", "gluten"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 12,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Mochi ice cream", perGuest: 1, unit: "ea", aisle: "frozen" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "japanese",
  },
  {
    id: "jp-umeshu-soda",
    name: "Umeshu soda",
    course: "drink",
    note: "Poured to order over ice; keep bottle chilled ahead of service.",
    contains: ["alcohol"],
    formats: ["cocktail", "seated"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 5,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 120,
    ingredients: [
      { item: "Umeshu (plum liqueur)", perGuest: 40, unit: "ml", aisle: "drinks" },
      { item: "Soda water", perGuest: 60, unit: "ml", aisle: "drinks" },
      { item: "Ice", perGuest: 0.1, unit: "kg", aisle: "non-food" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "chill",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "japanese",
  },

  // ===== Indian (in-) =====
  {
    id: "in-butter-chicken",
    name: "Murgh makhani",
    course: "anchor",
    note: "Sauce base freezes well; simmer gently to avoid splitting the cream.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 20,
    burnerMin: 40,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Chicken thigh", perGuest: 0.2, unit: "kg", aisle: "protein" },
      { item: "Tomato purée", perGuest: 0.1, unit: "kg", aisle: "pantry" },
      { item: "Cream", perGuest: 30, unit: "ml", aisle: "dairy" },
      { item: "Garam masala", perGuest: 2, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 6,
    method: "braise",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
  },
  {
    id: "in-lamb-rogan-josh",
    name: "Rogan josh",
    course: "anchor",
    note: "Long braise, tastes better the next day; hold covered on low heat.",
    contains: ["meat", "dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 120,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Lamb shoulder", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Yoghurt", perGuest: 30, unit: "g", aisle: "dairy" },
      { item: "Kashmiri chile powder", perGuest: 3, unit: "g", aisle: "pantry" },
      { item: "Onion", perGuest: 0.4, unit: "ea", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 8,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "indian",
  },
  {
    id: "in-tandoori-chicken",
    name: "Tandoori murgh",
    course: "anchor",
    note: "Marinates overnight; oven or grill finish needs high heat for char.",
    contains: ["dairy"],
    formats: ["buffet", "grazing"],
    shapes: ["cookout", "dinner"],
    grill: true,
    ovenMin: 30,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Chicken leg", perGuest: 0.3, unit: "kg", aisle: "protein" },
      { item: "Yoghurt", perGuest: 40, unit: "g", aisle: "dairy" },
      { item: "Tandoori masala", perGuest: 5, unit: "g", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.3, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 6,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "indian",
  },
  {
    id: "in-aloo-gobi",
    name: "Aloo gobi",
    course: "side",
    note: "Single pan, dry-style vegetable side; reheats without losing texture.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Potato", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Cauliflower", perGuest: 0.15, unit: "kg", aisle: "produce" },
      { item: "Cumin seed", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Turmeric", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "indian",
  },
  {
    id: "in-dal-tadka",
    name: "Dal tadka",
    course: "side",
    note: "Lentils simmer unattended; the tempered oil topping is added right before serving.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 40,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Yellow lentils", perGuest: 0.07, unit: "kg", aisle: "pantry" },
      { item: "Ghee", perGuest: 8, unit: "g", aisle: "dairy" },
      { item: "Cumin seed", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Garlic", perGuest: 1, unit: "clove", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "indian",
  },
  {
    id: "in-samosas",
    name: "Samosa",
    course: "starter",
    note: "Fold and freeze ahead; fry in batches so oil temperature stays steady.",
    contains: ["gluten"],
    formats: ["grazing", "buffet"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 45,
    servesPerBatch: 12,
    makeAheadDays: 2,
    holdMin: 30,
    ingredients: [
      { item: "Potato", perGuest: 0.1, unit: "kg", aisle: "produce" },
      { item: "Peas", perGuest: 0.03, unit: "kg", aisle: "frozen" },
      { item: "Flour", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Frying oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "indian",
  },
  {
    id: "in-pani-puri",
    name: "Pani puri",
    course: "starter",
    note: "Assembled by guests to order; shells go soft within minutes of filling.",
    contains: ["gluten"],
    formats: ["grazing", "cocktail"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Puri shells", perGuest: 4, unit: "ea", aisle: "pantry" },
      { item: "Tamarind water", perGuest: 40, unit: "ml", aisle: "pantry" },
      { item: "Potato", perGuest: 0.05, unit: "kg", aisle: "produce" },
      { item: "Chickpeas, cooked", perGuest: 0.03, unit: "kg", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "indian",
  },
  {
    id: "in-thali-board",
    name: "Thali board",
    course: "board",
    note: "Composed from several components made ahead; assemble plates just before service.",
    contains: ["dairy", "gluten"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Rice", perGuest: 0.08, unit: "kg", aisle: "pantry" },
      { item: "Raita", perGuest: 40, unit: "g", aisle: "dairy" },
      { item: "Pickle", perGuest: 10, unit: "g", aisle: "pantry" },
      { item: "Papadum", perGuest: 1, unit: "ea", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "boil",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
  },
  {
    id: "in-naan",
    name: "Naan",
    course: "bread",
    note: "Needs very high, dry heat; a domestic oven with a stone gets closest.",
    contains: ["gluten", "dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 15,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Yoghurt", perGuest: 15, unit: "g", aisle: "dairy" },
      { item: "Yeast", perGuest: 1, unit: "g", aisle: "pantry" },
      { item: "Butter", perGuest: 5, unit: "g", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
  },
  {
    id: "in-paratha",
    name: "Paratha",
    course: "bread",
    note: "Cooked in batches on a flat pan; keep warm stacked under a cloth.",
    contains: ["gluten", "dairy"],
    formats: ["buffet"],
    shapes: ["brunch", "dinner"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Whole wheat flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Ghee", perGuest: 10, unit: "g", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 1,
    method: "fry",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
  },
  {
    id: "in-gulab-jamun",
    name: "Gulab jamun",
    course: "sweet",
    note: "Fried dumplings soak in syrup for hours; serve warm or at room temperature.",
    contains: ["dairy", "gluten"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 30,
    servesPerBatch: 12,
    makeAheadDays: 2,
    holdMin: 240,
    ingredients: [
      { item: "Milk powder", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Sugar syrup", perGuest: 40, unit: "ml", aisle: "pantry" },
      { item: "Cardamom", perGuest: 0.2, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "indian",
  },
  {
    id: "in-kheer",
    name: "Kheer",
    course: "sweet",
    note: "Rice pudding simmers slowly and thickens further as it cools; serve chilled or warm.",
    contains: ["dairy", "nut"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 45,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 10,
    makeAheadDays: 2,
    holdMin: 180,
    ingredients: [
      { item: "Rice", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Milk", perGuest: 150, unit: "ml", aisle: "dairy" },
      { item: "Sugar", perGuest: 0.02, unit: "kg", aisle: "pantry" },
      { item: "Pistachios", perGuest: 3, unit: "g", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "boil",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "indian",
  },
  {
    id: "in-masala-chai",
    name: "Masala chai",
    course: "drink",
    note: "Simmered with milk on one burner; keep warm on the lowest setting for service.",
    contains: ["dairy"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "brunch"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 60,
    ingredients: [
      { item: "Black tea leaves", perGuest: 2, unit: "g", aisle: "pantry" },
      { item: "Milk", perGuest: 80, unit: "ml", aisle: "dairy" },
      { item: "Cardamom, ginger, cinnamon mix", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["winter"],
    costPerGuest: 1,
    method: "boil",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "indian",
  },

  // ===== Southeast Asian (sa-) =====
  {
    id: "sa-green-curry",
    name: "Gaeng keow wan gai",
    course: "anchor",
    note: "Curry paste can be made ahead; coconut milk simmers gently to avoid splitting.",
    contains: ["fish"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Chicken breast", perGuest: 0.16, unit: "kg", aisle: "protein" },
      { item: "Coconut milk", perGuest: 100, unit: "ml", aisle: "pantry" },
      { item: "Green curry paste", perGuest: 15, unit: "g", aisle: "pantry" },
      { item: "Thai eggplant", perGuest: 0.05, unit: "kg", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 5,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "seasia",
  },
  {
    id: "sa-satay-ayam",
    name: "Satay ayam",
    course: "anchor",
    note: "Marinated skewers grill fast; peanut sauce is made well ahead and reheated.",
    contains: ["nut"],
    formats: ["grazing", "buffet"],
    shapes: ["cookout"],
    grill: true,
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 20,
    ingredients: [
      { item: "Chicken thigh", perGuest: 0.18, unit: "kg", aisle: "protein" },
      { item: "Peanuts, ground", perGuest: 20, unit: "g", aisle: "pantry" },
      { item: "Coconut milk", perGuest: 20, unit: "ml", aisle: "pantry" },
      { item: "Turmeric", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 5,
    method: "grill",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "seasia",
  },
  {
    id: "sa-beef-rendang",
    name: "Rendang daging",
    course: "anchor",
    note: "Very long slow simmer until the liquid reduces to a dry coating; freezes well.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 180,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 90,
    ingredients: [
      { item: "Beef chuck", perGuest: 0.2, unit: "kg", aisle: "protein" },
      { item: "Coconut milk", perGuest: 120, unit: "ml", aisle: "pantry" },
      { item: "Lemongrass", perGuest: 0.3, unit: "stalk", aisle: "produce" },
      { item: "Galangal", perGuest: 3, unit: "g", aisle: "produce" },
    ],
    season: ["autumn", "winter"],
    costPerGuest: 7,
    method: "braise",
    tempBand: "hot",
    kidFriendly: false,
    outdoorSafe: false,
    cuisine: "seasia",
  },
  {
    id: "sa-som-tam",
    name: "Som tam",
    course: "side",
    note: "Pounded fresh to order; does not hold, dresses within minutes of serving.",
    contains: ["shellfish", "fish"],
    formats: ["seated", "grazing"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 15,
    ingredients: [
      { item: "Green papaya", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Dried shrimp", perGuest: 5, unit: "g", aisle: "pantry" },
      { item: "Fish sauce", perGuest: 8, unit: "ml", aisle: "pantry" },
      { item: "Lime", perGuest: 0.4, unit: "ea", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "raw",
    tempBand: "cold",
    kidFriendly: false,
    outdoorSafe: true,
    cuisine: "seasia",
  },
  {
    id: "sa-gado-gado",
    name: "Gado-gado",
    course: "side",
    note: "Vegetables cook and cool ahead; peanut sauce warms on one burner just before plating.",
    contains: ["nut", "egg"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 45,
    ingredients: [
      { item: "Mixed vegetables", perGuest: 0.2, unit: "kg", aisle: "produce" },
      { item: "Peanuts, ground", perGuest: 25, unit: "g", aisle: "pantry" },
      { item: "Egg, boiled", perGuest: 0.5, unit: "ea", aisle: "dairy" },
      { item: "Tempeh", perGuest: 0.05, unit: "kg", aisle: "protein" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "boil",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "seasia",
  },
  {
    id: "sa-spring-rolls",
    name: "Gỏi cuốn",
    course: "starter",
    note: "Rolled cold to order; wrappers dry out if prepared too far ahead.",
    contains: ["shellfish"],
    formats: ["grazing", "seated"],
    shapes: ["aperitivo", "dinner"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 35,
    servesPerBatch: 10,
    makeAheadDays: 0,
    holdMin: 30,
    ingredients: [
      { item: "Rice paper", perGuest: 2, unit: "ea", aisle: "pantry" },
      { item: "Cooked shrimp", perGuest: 0.04, unit: "kg", aisle: "protein" },
      { item: "Rice vermicelli", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Herbs, mixed", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
    season: ["summer"],
    costPerGuest: 4,
    method: "raw",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "seasia",
  },
  {
    id: "sa-chicken-satay-skewers",
    name: "Lumpia goreng",
    course: "starter",
    note: "Fried in batches; keep oil at a steady temperature to avoid greasy shells.",
    contains: ["gluten", "meat"],
    formats: ["grazing"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 12,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Spring roll wrappers", perGuest: 2, unit: "ea", aisle: "frozen" },
      { item: "Pork, minced", perGuest: 0.05, unit: "kg", aisle: "protein" },
      { item: "Carrot", perGuest: 0.1, unit: "ea", aisle: "produce" },
      { item: "Frying oil", perGuest: 15, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 3,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "seasia",
  },
  {
    id: "sa-banh-mi-board",
    name: "Bánh mì board",
    course: "board",
    note: "Components made ahead and assembled to order so the bread stays crisp.",
    contains: ["gluten", "meat"],
    formats: ["grazing", "buffet"],
    shapes: ["aperitivo", "reception"],
    ovenMin: 10,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 3,
    activeMin: 30,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 60,
    ingredients: [
      { item: "Baguette", perGuest: 0.5, unit: "ea", aisle: "bakery" },
      { item: "Pork pâté", perGuest: 20, unit: "g", aisle: "protein" },
      { item: "Pickled daikon and carrot", perGuest: 30, unit: "g", aisle: "produce" },
      { item: "Cilantro", perGuest: 0.02, unit: "bunch", aisle: "produce" },
    ],
    season: ["year-round"],
    costPerGuest: 4,
    method: "raw",
    tempBand: "ambient",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "seasia",
  },
  {
    id: "sa-roti-canai",
    name: "Roti canai",
    course: "bread",
    note: "Dough rests and laminates ahead; cooks fast on a hot flat pan per order.",
    contains: ["gluten", "dairy"],
    formats: ["grazing", "buffet"],
    shapes: ["brunch", "aperitivo"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 40,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Flour", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Ghee", perGuest: 10, unit: "g", aisle: "dairy" },
      { item: "Condensed milk", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "fry",
    tempBand: "hot",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "seasia",
  },
  {
    id: "sa-pandan-waffles",
    name: "Kuih waffle pandan",
    course: "bread",
    note: "Batter rests overnight; irons cook in batches, best served warm.",
    contains: ["gluten", "egg", "dairy"],
    formats: ["grazing", "buffet"],
    shapes: ["brunch"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 30,
    ingredients: [
      { item: "Flour", perGuest: 0.04, unit: "kg", aisle: "pantry" },
      { item: "Coconut milk", perGuest: 30, unit: "ml", aisle: "pantry" },
      { item: "Pandan extract", perGuest: 1, unit: "ml", aisle: "pantry" },
      { item: "Eggs", perGuest: 0.2, unit: "ea", aisle: "dairy" },
    ],
    season: ["year-round"],
    costPerGuest: 2,
    method: "bake",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: false,
    cuisine: "seasia",
  },
  {
    id: "sa-mango-sticky-rice",
    name: "Khao niew mamuang",
    course: "sweet",
    note: "Rice steams ahead and holds warm wrapped in cloth; assemble with mango just before serving.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 30,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 90,
    ingredients: [
      { item: "Glutinous rice", perGuest: 0.06, unit: "kg", aisle: "pantry" },
      { item: "Coconut milk", perGuest: 60, unit: "ml", aisle: "pantry" },
      { item: "Mango", perGuest: 0.5, unit: "ea", aisle: "produce" },
      { item: "Sugar", perGuest: 0.01, unit: "kg", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 3,
    method: "boil",
    tempBand: "warm",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "seasia",
  },
  {
    id: "sa-che-ba-mau",
    name: "Chè ba màu",
    course: "sweet",
    note: "Layered dessert assembled cold; keep components separate until just before serving.",
    contains: [],
    formats: ["grazing", "buffet"],
    shapes: ["aperitivo"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 25,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 120,
    ingredients: [
      { item: "Mung bean, split", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Red kidney beans, cooked", perGuest: 0.03, unit: "kg", aisle: "pantry" },
      { item: "Coconut milk", perGuest: 40, unit: "ml", aisle: "pantry" },
      { item: "Grass jelly", perGuest: 0.03, unit: "kg", aisle: "pantry" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "seasia",
  },
  {
    id: "sa-thai-iced-tea",
    name: "Cha yen",
    course: "drink",
    note: "Brewed ahead and chilled; layer the milk in the glass right before serving.",
    contains: ["dairy"],
    formats: ["buffet", "grazing", "cocktail"],
    shapes: ["cookout", "reception"],
    ovenMin: 0,
    burnerMin: 10,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 10,
    servesPerBatch: 10,
    makeAheadDays: 1,
    holdMin: 180,
    ingredients: [
      { item: "Thai tea mix", perGuest: 6, unit: "g", aisle: "pantry" },
      { item: "Condensed milk", perGuest: 20, unit: "ml", aisle: "pantry" },
      { item: "Ice", perGuest: 0.1, unit: "kg", aisle: "non-food" },
    ],
    season: ["summer"],
    costPerGuest: 2,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    outdoorSafe: true,
    cuisine: "seasia",
  },
];
