import type { Dish } from "./types";

/**
 * Pairing-forward fixtures from Seeds 4–6.
 * Educational planning dishes — not tested recipes, not allergen guarantees.
 */
export const PAIRING_DISHES: Dish[] = [
  {
    id: "pairing-sausage-peppers",
    name: "Sausage, peppers & onions",
    course: "anchor",
    note: "One pan, one burner. Soft peppers, browned sausage, bread or polenta to catch the fat.",
    contains: ["meat", "pork"],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 40,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 6,
    makeAheadDays: 1,
    holdMin: 40,
    season: ["autumn", "winter"],
    costPerGuest: 4.8,
    method: "fry",
    tempBand: "hot",
    cuisine: "italian",
    winePairing:
      "Gamay or a light Pinot, served cool. Red-fruit lift without tannin fighting sausage fat. Bottle math: one for three guests; keep a dry cider as fallback.",
    leftoverNote:
      "Reheat gently. Stuff leftover bread or fold through polenta. Do not recrisp the sausage to dry.",
    pairingWhy: "Acid and fruit cut sausage fat",
    ingredients: [
      { item: "Italian sausage", perGuest: 0.18, unit: "kg", aisle: "protein" },
      { item: "Peppers", perGuest: 0.8, unit: "ea", aisle: "produce" },
      { item: "Onion", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Olive oil", perGuest: 10, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "pairing-seared-tuna",
    name: "Sesame-seared tuna",
    course: "anchor",
    note: "Short, hot pan. Cucumber and sesame against clean fish. Do not cook through.",
    contains: ["fish"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 12,
    fridgeUnits: 2,
    counter: 2,
    activeMin: 20,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 10,
    season: ["summer", "spring"],
    costPerGuest: 8.5,
    method: "fry",
    tempBand: "warm",
    cuisine: "japanese",
    winePairing:
      "Dry Riesling or Muscadet. Acid cuts the sesame oil and amplifies clean fish. Nothing oaky, nothing sweet unless the Riesling is truly dry.",
    leftoverNote:
      "Leftover tuna becomes next-day rice bowls, cold, with cucumber and leftover sesame. Do not re-sear.",
    pairingWhy: "Acid cuts oil; clean fish wants a dry white",
    ingredients: [
      { item: "Tuna loin", perGuest: 0.14, unit: "kg", aisle: "protein" },
      { item: "Sesame seeds", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Cucumber", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Soy or tamari", perGuest: 8, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "pairing-sage-gnocchi",
    name: "Sage brown-butter gnocchi",
    course: "anchor",
    note: "Pan-seared gnocchi, sage, brown butter. Attention-heavy at the stove — only when the host can stay put.",
    contains: ["gluten", "dairy"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 25,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 30,
    servesPerBatch: 4,
    makeAheadDays: 1,
    holdMin: 15,
    season: ["autumn", "winter"],
    costPerGuest: 3.6,
    method: "fry",
    tempBand: "hot",
    cuisine: "italian",
    winePairing:
      "Cool-climate Pinot or Gamay. Softens brown-butter richness without tannin. A quiet white (Soave) if the table prefers.",
    leftoverNote:
      "Leftover gnocchi pan-fries beautifully the next morning. Do not re-sauce; brown the edges in a dry pan.",
    pairingWhy: "Acid and red fruit cut brown butter",
    ingredients: [
      { item: "Potato gnocchi", perGuest: 0.18, unit: "kg", aisle: "pantry" },
      { item: "Butter", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Sage", perGuest: 4, unit: "g", aisle: "produce" },
      { item: "Parmesan", perGuest: 15, unit: "g", aisle: "dairy" },
    ],
  },
  {
    id: "pairing-hanger-steak",
    name: "Hanger steak, charred greens",
    course: "anchor",
    note: "One hot pan or grill. Rest is part of the method. Slice against the grain.",
    contains: ["meat"],
    formats: ["seated"],
    shapes: ["dinner"],
    ovenMin: 0,
    burnerMin: 20,
    fridgeUnits: 1,
    counter: 2,
    activeMin: 25,
    servesPerBatch: 4,
    makeAheadDays: 0,
    holdMin: 20,
    season: ["autumn", "winter", "summer"],
    costPerGuest: 7.2,
    method: "grill",
    tempBand: "hot",
    grill: true,
    cuisine: "house",
    winePairing:
      "Northern Rhône or cool-climate Syrah. Pepper and acid against the beef — not a tannic block. One bottle for three hungry seats.",
    leftoverNote:
      "Leftover steak makes excellent cold sandwiches with mustard and sharp greens. Do not recook past warm.",
    pairingWhy: "Pepper and acid against beef fat",
    ingredients: [
      { item: "Hanger steak", perGuest: 0.22, unit: "kg", aisle: "protein" },
      { item: "Seasonal greens", perGuest: 0.08, unit: "kg", aisle: "produce" },
      { item: "Mustard", perGuest: 8, unit: "g", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "pairing-rhubarb-fool",
    name: "Rhubarb fool",
    course: "sweet",
    note: "Folded cream and sharp fruit. Fully make-ahead. The spring close.",
    contains: ["dairy"],
    formats: ["seated", "buffet"],
    shapes: ["dinner", "brunch"],
    ovenMin: 0,
    burnerMin: 15,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 20,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 240,
    season: ["spring"],
    costPerGuest: 1.8,
    method: "chill",
    tempBand: "cold",
    cuisine: "house",
    winePairing:
      "Dry Riesling or nothing. The rhubarb is the acid. Coffee is an honest close. If pouring: leftover white from the main.",
    leftoverNote:
      "Keeps overnight and softens. Spoon over leftover cake or eat colder. Do not whip it again.",
    pairingWhy: "Season fit; fruit acid is the pairing",
    ingredients: [
      { item: "Rhubarb", perGuest: 0.1, unit: "kg", aisle: "produce" },
      { item: "Cream", perGuest: 60, unit: "ml", aisle: "dairy" },
      { item: "Sugar", perGuest: 18, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "pairing-gin-tonic",
    name: "Gin & tonic (or equal tonic)",
    course: "drink",
    note: "Classic highball. Zero-proof tonic with citrus is equal status, same glass.",
    contains: ["alcohol"],
    formats: ["cocktail", "grazing", "seated"],
    shapes: ["aperitivo", "dinner", "reception"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 8,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 10,
    season: ["summer", "year-round"],
    costPerGuest: 2.4,
    method: "chill",
    tempBand: "cold",
    cuisine: "house",
    winePairing:
      "The highball is the pairing. Ice and citrus are the constraint. Keep a zero-proof tonic build in the same glassware. Do not batch gin — build to order, ice last.",
    leftoverNote:
      "Opened tonic dies. Citrus keeps. There is no leftover cocktail. Fail closed.",
    pairingWhy: "Bitter and bubbles against a salty board",
    ingredients: [
      { item: "Gin or zero-proof spirit", perGuest: 50, unit: "ml", aisle: "drinks" },
      { item: "Tonic", perGuest: 0.15, unit: "L", aisle: "drinks" },
      { item: "Citrus", perGuest: 0.3, unit: "ea", aisle: "produce" },
      { item: "Ice", perGuest: 0.25, unit: "kg", aisle: "frozen" },
    ],
  },
  {
    id: "pairing-bitter-orange",
    name: "Bitter-orange spritz, zero-proof",
    course: "drink",
    note: "Equal-status house pour. Batched, chilled, poured like wine. Not a fallback.",
    contains: [],
    formats: ["seated", "cocktail", "grazing", "buffet"],
    shapes: ["dinner", "aperitivo", "reception"],
    ovenMin: 0,
    burnerMin: 5,
    fridgeUnits: 2,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 8,
    makeAheadDays: 2,
    holdMin: 300,
    season: ["year-round"],
    costPerGuest: 1.4,
    method: "chill",
    tempBand: "cold",
    kidFriendly: true,
    cuisine: "house",
    winePairing:
      "This is the pairing. Bitter orange, tonic or soda, ice, citrus wheel. Same glass as the wine service. Batch the bitter base; add bubbles at pour.",
    leftoverNote:
      "Bitter base keeps a week cold. Do not recarbonate leftover spritz.",
    pairingWhy: "Bitter structure stands in for wine",
    ingredients: [
      { item: "Bitter orange base", perGuest: 40, unit: "ml", aisle: "drinks" },
      { item: "Sparkling water", perGuest: 0.18, unit: "L", aisle: "drinks" },
      { item: "Ice", perGuest: 0.3, unit: "kg", aisle: "frozen" },
      { item: "Orange", perGuest: 0.2, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "pairing-radish-butter",
    name: "Radishes, butter & flaky salt",
    course: "board",
    note: "Cold welcome. No heat. Butter cool, radishes in ice water until the door.",
    contains: ["dairy"],
    formats: ["seated", "grazing", "cocktail"],
    shapes: ["dinner", "aperitivo"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 1,
    counter: 1,
    activeMin: 12,
    servesPerBatch: 8,
    makeAheadDays: 0,
    holdMin: 90,
    season: ["spring", "summer"],
    costPerGuest: 1.2,
    method: "raw",
    tempBand: "cold",
    cuisine: "house",
    winePairing:
      "Muscadet, dry cider, or a gin & tonic. Salt, fat, and crunch want acid and bubbles — not a still heavy white.",
    leftoverNote:
      "Radishes keep in water. Butter recooks nothing. Next day: leftover bread, same salt.",
    pairingWhy: "Salt and fat want acid and bubbles",
    ingredients: [
      { item: "Bunch radishes", perGuest: 0.4, unit: "ea", aisle: "produce" },
      { item: "Cultured butter", perGuest: 20, unit: "g", aisle: "dairy" },
      { item: "Flaky salt", perGuest: 1, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "pairing-brussels-char",
    name: "Hard-charred Brussels sprouts",
    course: "side",
    note: "High heat, bitter-sweet. Sausage or white beans if you need more. They wait 15 minutes, not an hour.",
    contains: [],
    formats: ["seated", "buffet"],
    shapes: ["dinner"],
    ovenMin: 18,
    burnerMin: 0,
    fridgeUnits: 0,
    counter: 1,
    activeMin: 15,
    servesPerBatch: 6,
    makeAheadDays: 0,
    holdMin: 20,
    season: ["autumn", "winter"],
    costPerGuest: 1.5,
    method: "roast",
    tempBand: "hot",
    cuisine: "house",
    winePairing:
      "Light red or dry cider. Bitter + sweet + fat. Nothing heavy, nothing sweet.",
    leftoverNote:
      "Reheat in a hot pan. They improve. A squeeze of lemon if they dull.",
    pairingWhy: "Bitter against fat; cider or light red",
    ingredients: [
      { item: "Brussels sprouts", perGuest: 0.12, unit: "kg", aisle: "produce" },
      { item: "Olive oil", perGuest: 8, unit: "ml", aisle: "pantry" },
      { item: "Lemon", perGuest: 0.15, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "pairing-dry-cider",
    name: "Dry cider service",
    course: "drink",
    note: "Counted like wine. Chill like a white. The honest pour for pork, bird, and charred greens.",
    contains: ["alcohol"],
    formats: ["seated", "buffet", "grazing"],
    shapes: ["dinner", "cookout", "brunch"],
    ovenMin: 0,
    burnerMin: 0,
    fridgeUnits: 2,
    counter: 0,
    activeMin: 6,
    servesPerBatch: 8,
    makeAheadDays: 1,
    holdMin: 300,
    season: ["autumn", "winter", "year-round"],
    costPerGuest: 2.2,
    method: "chill",
    tempBand: "cold",
    cuisine: "house",
    winePairing:
      "Dry cider is the pairing — treat it as a white wine. Fridge or ice is the constraint. 0.4 bottle/head seated. Keep a still white as fallback, not a sweet cider.",
    leftoverNote:
      "Opened cider keeps one day, cold. Cook with it or drink it. Do not recork for a second party.",
    pairingWhy: "Season fit; acid and apple against pork and bird",
    ingredients: [
      { item: "Dry cider", perGuest: 0.4, unit: "bottle", aisle: "drinks" },
      { item: "Glassware", perGuest: 1.2, unit: "glass", aisle: "non-food" },
    ],
  },
];
