/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ShareRouteImport } from './routes/share'
import { Route as RecipesDishIdRouteImport } from './routes/recipes.$dishId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesDishIdRoute = RecipesDishIdRouteImport.update({
  id: '/recipes/$dishId',
  path: '/recipes/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/library': typeof LibraryRoute
  '/menu': typeof MenuRoute
  '/share': typeof ShareRoute
  '/recipes/$dishId': typeof RecipesDishIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/library': typeof LibraryRoute
  '/menu': typeof MenuRoute
  '/share': typeof ShareRoute
  '/recipes/$dishId': typeof RecipesDishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/library': typeof LibraryRoute
  '/menu': typeof MenuRoute
  '/share': typeof ShareRoute
  '/recipes/$dishId': typeof RecipesDishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/architecture' | '/library' | '/menu' | '/share' | '/recipes/$dishId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/architecture' | '/library' | '/menu' | '/share' | '/recipes/$dishId'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/library'
    | '/menu'
    | '/share'
    | '/recipes/$dishId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  LibraryRoute: typeof LibraryRoute
  MenuRoute: typeof MenuRoute
  ShareRoute: typeof ShareRoute
  RecipesDishIdRoute: typeof RecipesDishIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$dishId': {
      id: '/recipes/$dishId'
      path: '/recipes/$dishId'
      fullPath: '/recipes/$dishId'
      preLoaderRoute: typeof RecipesDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  LibraryRoute: LibraryRoute,
  MenuRoute: MenuRoute,
  ShareRoute: ShareRoute,
  RecipesDishIdRoute: RecipesDishIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
