/** Drink planning recipes for Architecture beverage route. Educational — not kitchen certification. */

import type { Recipe } from "./recipes";

function r(
  dishId: string,
  yieldText: string,
  activeMinutes: number,
  totalMinutes: number,
  difficulty: Recipe["difficulty"],
  headnote: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  makeAhead: string,
  equipment: string[],
  dietary: string[],
  scalingNote: string,
): Recipe {
  return {
    dishId,
    yield: yieldText,
    activeMinutes,
    totalMinutes,
    difficulty,
    headnote,
    ingredients,
    steps,
    makeAhead,
    equipment,
    dietary,
    scalingNote,
  };
}

export const DRINK_RECIPES: Record<string, Recipe> = {
  "drink-zero": r(
    "drink-zero",
    "Serves 12 as equal-status house pour",
    20,
    20,
    "easy",
    "The zero-proof peer that must read as intentional, not a consolation. Acid, bitterness, aroma, dilution, and temperature — not sweetness alone.",
    [
      { item: "Chilled sparkling water or soda", amount: "3 liters", aisle: "beverages" },
      { item: "Fresh citrus (lemon, lime, or grapefruit)", amount: "4", aisle: "produce" },
      { item: "Bitters or non-alcoholic bitter aperitif", amount: "4 oz", aisle: "beverages" },
      { item: "Simple syrup or honey syrup", amount: "1/2 cup", aisle: "pantry" },
      { item: "Fresh herb (rosemary, thyme, or mint)", amount: "1 small bunch", aisle: "produce" },
      { item: "Ice", amount: "plenty", aisle: "other" },
    ],
    [
      "Chill the sparkling base fully — warm bubbles read as an afterthought.",
      "Build in a pitcher: juice of 2 citrus, syrup, bitters, then top with sparkling water.",
      "Taste for acid and bitterness before service; adjust so it stands next to any wine or spirit pour.",
      "Garnish glasses with citrus peel and herb. Keep a second pitcher cold so the Equal never runs dry.",
    ],
    "Base mix (juice, syrup, bitters) up to 1 day ahead. Add sparkling water and ice at service.",
    ["Pitcher", "Citrus juicer", "Ice bucket"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 8-10 oz finished pour per guest when this is the Equal.",
  ),
  "drink-shrub": r(
    "drink-shrub",
    "Serves 12 as cut or arrival",
    25,
    25 + 24 * 60,
    "easy",
    "Vinegar-forward fruit syrup cut with soda. High acid, low sugar — a true contrast pour.",
    [
      { item: "Seasonal fruit (berries, stone fruit, or apple)", amount: "2 cups chopped", aisle: "produce" },
      { item: "Sugar", amount: "1 cup", aisle: "pantry" },
      { item: "Apple cider vinegar or white wine vinegar", amount: "1 cup", aisle: "pantry" },
      { item: "Sparkling water", amount: "2 liters", aisle: "beverages" },
      { item: "Ice and citrus wheels", amount: "for service", aisle: "other" },
    ],
    [
      "Macerate fruit with sugar 4-12 hours until juicy.",
      "Strain, stir in vinegar, and bottle. Rest cold at least overnight.",
      "At service: 1 oz shrub to 4-5 oz sparkling water over ice.",
      "Label clearly so guests know it is acid-forward, not a soft drink.",
    ],
    "Shrub concentrate keeps 2-3 weeks refrigerated. Build each glass or a small pitcher at service.",
    ["Jar or bottle", "Fine strainer"],
    ["vegetarian", "vegan", "gluten_free"],
    "Plan 1-1.25 oz concentrate per guest for a cut pour.",
  ),
  "pairing-bitter-orange": r(
    "pairing-bitter-orange",
    "Serves 10-12 as zero-proof cut or equal",
    15,
    15,
    "easy",
    "Bitter-orange and tonic structure without alcohol. Visual and aromatic peer to a spritz.",
    [
      { item: "Non-alcoholic bitter aperitif or orange bitters", amount: "8 oz", aisle: "beverages" },
      { item: "Chilled tonic water", amount: "2 liters", aisle: "beverages" },
      { item: "Orange", amount: "2, peels and wheels", aisle: "produce" },
      { item: "Ice", amount: "plenty", aisle: "other" },
      { item: "Optional: splash of grapefruit juice", amount: "1/2 cup", aisle: "produce" },
    ],
    [
      "Chill glasses or a small pitcher.",
      "Build 1 part bitter to 3-4 parts tonic over ice.",
      "Express orange peel over the surface and drop it in.",
      "Serve in the same glassware family as any alcoholic spritz so Equal status is visible.",
    ],
    "No advance mix required. Stage bottles, ice, and peels at the station.",
    ["Wine glasses or tumblers", "Ice bucket", "Peeler"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 6-8 oz finished drink per guest.",
  ),
  "cn-cold-brew-batch": r(
    "cn-cold-brew-batch",
    "Serves 12 as arrival or volume",
    15,
    15 + 12 * 60,
    "easy",
    "Concentrate that dilutes cleanly. Low host attention at the door once the urn is set.",
    [
      { item: "Coarsely ground coffee", amount: "12 oz (about 4 cups)", aisle: "pantry" },
      { item: "Cold filtered water", amount: "8 cups for concentrate", aisle: "other" },
      { item: "Additional cold water or milk for service", amount: "as needed", aisle: "dairy-eggs" },
      { item: "Ice", amount: "for service", aisle: "other" },
    ],
    [
      "Stir grounds with cold water. Steep refrigerated 12-18 hours.",
      "Strain through a fine filter or cloth. Do not press hard or it turns muddy.",
      "Serve 1 part concentrate to 1-2 parts cold water or milk over ice.",
      "Label strength so guests can dilute further.",
    ],
    "Concentrate keeps 5 days cold. Dilute at service only.",
    ["Large jar", "Fine strainer or cloth", "Dispenser or pitcher"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 3/4-1 cup finished cold brew per guest.",
  ),
  "mx-agua-fresca": r(
    "mx-agua-fresca",
    "Serves 12 as arrival or equal",
    25,
    25,
    "easy",
    "Watermelon (or seasonal fruit) blended thin, strained, lightly sweetened. Cold and visible on the table.",
    [
      { item: "Seedless watermelon (or melon/pineapple)", amount: "4 lb cubed", aisle: "produce" },
      { item: "Lime", amount: "3, juiced", aisle: "produce" },
      { item: "Sugar or agave", amount: "3-5 tbsp, to taste", aisle: "pantry" },
      { item: "Cold water", amount: "2-3 cups", aisle: "other" },
      { item: "Ice and lime wheels", amount: "for service", aisle: "other" },
    ],
    [
      "Blend fruit with a splash of water until smooth.",
      "Strain if you want a cleaner pour; leave pulp for a rustic texture.",
      "Season with lime and just enough sweetener — it should stay bright, not syrupy.",
      "Chill hard. Serve from a clear dispenser so the Equal is obvious.",
    ],
    "Blend morning-of. Holds 1 day cold; stir before service as it separates.",
    ["Blender", "Strainer", "Clear dispenser"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 8 oz per guest as an arrival or equal pour.",
  ),
  "cw-drink-lemonade-stand": r(
    "cw-drink-lemonade-stand",
    "Serves 16 as equal or arrival",
    30,
    30,
    "easy",
    "Big-batch lemonade with real juice. Scales without last-minute squeezing at the door.",
    [
      { item: "Lemons", amount: "12-14, juiced (about 2 cups)", aisle: "produce" },
      { item: "Sugar", amount: "1-1.25 cups", aisle: "pantry" },
      { item: "Cold water", amount: "8-10 cups", aisle: "other" },
      { item: "Ice", amount: "plenty", aisle: "other" },
      { item: "Lemon wheels and optional mint", amount: "for garnish", aisle: "produce" },
    ],
    [
      "Warm 1 cup water with sugar until dissolved; cool.",
      "Combine syrup, lemon juice, and remaining cold water. Taste for balance.",
      "Chill. Serve over ice from a labeled dispenser.",
      "Keep a second batch cold so the station never looks empty.",
    ],
    "Syrup and juice base up to 2 days ahead. Add water and ice at service.",
    ["Pitcher or dispenser", "Citrus juicer"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 8 oz per guest; more in heat.",
  ),
  "cw-drink-batched-punch": r(
    "cw-drink-batched-punch",
    "Serves 16 as volume pour",
    30,
    30,
    "moderate",
    "Dispenser punch with a clear spirit backbone, citrus, and dilution already built in. Host stays out of continuous stirring.",
    [
      { item: "Rum, brandy, or preferred spirit", amount: "750 ml", aisle: "beverages" },
      { item: "Citrus juice (lemon/lime/orange mix)", amount: "2 cups", aisle: "produce" },
      { item: "Tea, juice, or light mixer", amount: "4 cups", aisle: "beverages" },
      { item: "Sugar or rich syrup", amount: "0.75-1 cup", aisle: "pantry" },
      { item: "Sparkling water to lengthen", amount: "1 liter", aisle: "beverages" },
      { item: "Ice block or large cubes", amount: "1 block", aisle: "other" },
      { item: "Citrus wheels and nutmeg optional", amount: "for garnish", aisle: "produce" },
    ],
    [
      "Mix spirit, citrus, tea/mixer, and syrup. Chill hard.",
      "At service, add ice block and sparkling water so dilution stays controlled.",
      "Taste once; adjust acid or sweetness before guests arrive.",
      "Label the dispenser with spirit and strength. Keep a zero-proof Equal beside it.",
    ],
    "Still base 1 day ahead. Sparkling water and ice only at service.",
    ["Punch dispenser", "Ice block mold or large cubes"],
    [],
    "About 5-6 oz finished punch per guest as the volume pour.",
  ),
  "drink-batched-negroni": r(
    "drink-batched-negroni",
    "Serves 12 as volume or cut",
    20,
    20,
    "easy",
    "Bottled equal-parts aperitivo. Cold, consistent, no bar performance required.",
    [
      { item: "Gin", amount: "8 oz", aisle: "beverages" },
      { item: "Sweet vermouth", amount: "8 oz", aisle: "beverages" },
      { item: "Campari or bitter aperitivo", amount: "8 oz", aisle: "beverages" },
      { item: "Orange peels", amount: "12", aisle: "produce" },
      { item: "Ice", amount: "for service", aisle: "other" },
    ],
    [
      "Combine spirits in a clean bottle. Refrigerate at least 4 hours.",
      "Serve 3 oz over a large cube. Express orange peel over each glass.",
      "Do not dilute the batch — ice in the glass handles that.",
      "Park an equal-status zero-proof bitter pour next to it.",
    ],
    "Bottle up to 1 week cold. Peels cut day-of.",
    ["Bottles", "Jigger", "Peeler"],
    [],
    "One 3 oz serve per guest as a cut; more if it is the main pour.",
  ),
  "cw-drink-iced-tea-urn": r(
    "cw-drink-iced-tea-urn",
    "Serves 16 as volume",
    20,
    20 + 60,
    "easy",
    "Urn-scale black or mixed tea, chilled and lightly seasoned. Low attention once filled.",
    [
      { item: "Black tea bags or loose tea", amount: "12 bags or 1/3 cup loose", aisle: "pantry" },
      { item: "Boiling water", amount: "8 cups", aisle: "other" },
      { item: "Cold water to dilute", amount: "4-6 cups", aisle: "other" },
      { item: "Lemon and optional mint", amount: "for service", aisle: "produce" },
      { item: "Sugar or simple syrup", amount: "to taste", aisle: "pantry" },
      { item: "Ice", amount: "for the urn", aisle: "other" },
    ],
    [
      "Steep tea in boiling water 5-7 minutes. Remove leaves.",
      "Dilute with cold water, sweeten lightly if desired, and chill.",
      "Fill the urn with tea and ice just before doors open.",
      "Set lemon and cups beside it; refill from a cold backup pitcher.",
    ],
    "Brew morning-of or night-before. Ice only at service.",
    ["Urn or large dispenser", "Kettle"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 8-10 oz per guest.",
  ),
  "cw-drink-no-alcohol-cooler": r(
    "cw-drink-no-alcohol-cooler",
    "Serves 16 as equal",
    25,
    25,
    "easy",
    "Berry cooler built for a dispenser. Equal-status peer: clear label, same glassware, same station real estate.",
    [
      { item: "Mixed berries (fresh or frozen)", amount: "4 cups", aisle: "produce" },
      { item: "Lemon or lime juice", amount: "3/4 cup", aisle: "produce" },
      { item: "Sugar or honey syrup", amount: "1/2-3/4 cup", aisle: "pantry" },
      { item: "Cold water or sparkling water", amount: "8 cups", aisle: "beverages" },
      { item: "Ice", amount: "for dispenser", aisle: "other" },
    ],
    [
      "Muddle or blend berries with syrup and citrus; strain for a cleaner pour.",
      "Combine with cold water. Taste for acid — it should not read as soft drink syrup.",
      "Chill. Serve from a labeled dispenser with ice.",
      "Place beside any alcoholic volume pour so Equal visibility is structural, not verbal.",
    ],
    "Berry base 1 day ahead. Lengthen with water and ice at service.",
    ["Dispenser", "Strainer"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 8 oz per guest.",
  ),
  "drink-wine": r(
    "drink-wine",
    "Service plan for 12 guests",
    15,
    15,
    "easy",
    "Wine as a counted volume pour — not an open bar. Temperature, glassware, and a declared equal-status zero-proof beside it.",
    [
      { item: "Table wine matched to the anchor", amount: "3-4 bottles (750 ml)", aisle: "beverages" },
      { item: "Equal-status zero-proof option", amount: "1 full route", aisle: "beverages" },
      { item: "Wine glasses", amount: "1 per guest + 2-4 spare", aisle: "other" },
      { item: "Corkscrew, napkins, dump bucket", amount: "1 set", aisle: "other" },
    ],
    [
      "Chill whites and lighter reds appropriately; open reds that need air 30-60 minutes before service.",
      "Stage glasses and one backup bottle where the host can reach without leaving guests.",
      "Pour measured hospitality, not continuous top-ups that empty the case early.",
      "Keep the Equal pour on the same surface with equal visual intention.",
    ],
    "Buy and chill day-before. Open near service.",
    ["Corkscrew", "Ice bucket if needed", "Glassware"],
    [],
    "About 1/2 bottle per guest for a dinner; less for a short reception.",
  ),
  "cw-drink-spritz-station": r(
    "cw-drink-spritz-station",
    "Serves 12-16 as station",
    25,
    25,
    "moderate",
    "Build-your-own spritz: bitter, bubbles, citrus. Station attention is real — stock it so guests self-serve.",
    [
      { item: "Bitter aperitivo (alcoholic and/or zero-proof)", amount: "1 bottle each path", aisle: "beverages" },
      { item: "Prosecco or sparkling wine", amount: "2 bottles", aisle: "beverages" },
      { item: "Sparkling water", amount: "2 liters", aisle: "beverages" },
      { item: "Oranges and lemons", amount: "4 total", aisle: "produce" },
      { item: "Ice", amount: "high volume", aisle: "other" },
      { item: "Wine glasses", amount: "1 per guest + spare", aisle: "other" },
    ],
    [
      "Set three clear zones: bitter, bubbles, garnish — with a printed 3-2-1 or 2-3-1 guide.",
      "Ice must be abundant; a thin ice bowl is a station failure.",
      "Include a fully zero-proof path using non-alcoholic bitter + tonic or sparkling water.",
      "Check the station once mid-event for ice, glassware, and empty bottles.",
    ],
    "Prep citrus and signage morning-of. Open bubbles as guests arrive.",
    ["Ice tub", "Signage card", "Glassware"],
    [],
    "Plan 1.5 drinks per guest in the first hour for a standing reception.",
  ),
  "pairing-gin-tonic": r(
    "pairing-gin-tonic",
    "Serves 12 as cut or volume",
    15,
    15,
    "easy",
    "Highball structure with an equal tonic-only path on the same tray.",
    [
      { item: "Gin", amount: "1 bottle (750 ml)", aisle: "beverages" },
      { item: "Premium tonic", amount: "3 liters", aisle: "beverages" },
      { item: "Limes", amount: "6", aisle: "produce" },
      { item: "Ice", amount: "plenty", aisle: "other" },
      { item: "Optional: cucumber or rosemary", amount: "for garnish", aisle: "produce" },
    ],
    [
      "Chill tonic fully. Build 2 oz gin to 4-5 oz tonic over ice, or offer tonic-only as Equal.",
      "Garnish both paths the same way so zero-proof does not look stripped.",
      "Batch only if you must; bubbles fade in a pitcher.",
      "Keep spare tonic cold — flat tonic is a hard quality drop.",
    ],
    "Citrus cut day-of. Bottles chilled before service.",
    ["Highball glasses", "Ice bucket", "Knife"],
    [],
    "About 1.5 serves per guest for a cocktail hour.",
  ),
  "cw-drink-frozen-margarita-batch": r(
    "cw-drink-frozen-margarita-batch",
    "Serves 12 as station",
    30,
    30,
    "moderate",
    "Blender or pitcher frozen batch. Ice load and blender attention are the real constraints — plan them explicitly.",
    [
      { item: "Tequila", amount: "12 oz", aisle: "beverages" },
      { item: "Triple sec or orange liqueur", amount: "6 oz", aisle: "beverages" },
      { item: "Fresh lime juice", amount: "8 oz", aisle: "produce" },
      { item: "Simple syrup", amount: "3-4 oz", aisle: "pantry" },
      { item: "Ice", amount: "8-10 cups", aisle: "other" },
      { item: "Salt for rims optional", amount: "1/2 cup", aisle: "pantry" },
      { item: "Zero-proof: lime, syrup, orange juice, ice", amount: "parallel batch", aisle: "produce" },
    ],
    [
      "Blend spirit batch in two waves so the motor and ice stay cold.",
      "Hold in a chilled pitcher or insulated dispenser; refresh texture with a short re-blend if it thins.",
      "Run a zero-proof frozen lime batch with the same glass and salt option.",
      "Assign ice: frozen drinks compete with every other cold hold — buy extra.",
    ],
    "Juice and syrup morning-of. Blend as close to service as equipment allows.",
    ["Blender", "Insulated pitcher", "Ice chest"],
    [],
    "About 6-8 oz frozen pour per guest; ice budget is the limiting resource.",
  ),
  "cw-drink-hot-cider-urn": r(
    "cw-drink-hot-cider-urn",
    "Serves 16 as station or volume",
    20,
    20 + 30,
    "easy",
    "Hot spiced cider in an urn. Station heat is the constraint — one dedicated burner or plugged urn, not a borrowed sauce pot.",
    [
      { item: "Apple cider", amount: "1 gallon", aisle: "beverages" },
      { item: "Cinnamon sticks", amount: "4", aisle: "spices" },
      { item: "Whole cloves or allspice", amount: "1 tsp", aisle: "spices" },
      { item: "Orange", amount: "1, sliced", aisle: "produce" },
      { item: "Optional: brown sugar", amount: "2-3 tbsp", aisle: "pantry" },
      { item: "Mugs", amount: "1 per guest + spare", aisle: "other" },
    ],
    [
      "Warm cider with spices and orange 20-30 minutes; do not boil hard.",
      "Strain into a preheated urn or keep on the lowest steady heat.",
      "Label as alcohol-free unless you intentionally fortify a separate pot.",
      "Set mugs, ladle, and a trivet so guests self-serve without hunting the host.",
    ],
    "Spice the cider earlier in the day; reheat gently before service.",
    ["Urn or heavy pot", "Ladle", "Mugs"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 8 oz hot pour per guest.",
  ),
};
