/** Planning recipes for every catalog dish. Educational — not kitchen-tested certification. */

export type RecipeIngredient = {
  item: string;
  amount: string;
  aisle: "produce" | "pantry" | "dairy-eggs" | "bakery" | "protein" | "spices" | "frozen" | "deli" | "beverages" | "other";
};

export type Recipe = {
  dishId: string;
  yield: string;
  activeMinutes: number;
  totalMinutes: number;
  difficulty: "easy" | "moderate" | "involved";
  headnote: string;
  ingredients: RecipeIngredient[];
  steps: string[];
  makeAhead: string;
  equipment: string[];
  dietary: string[];
  scalingNote: string;
};

function r(
  dishId: string,
  yieldText: string,
  activeMinutes: number,
  totalMinutes: number,
  difficulty: Recipe["difficulty"],
  headnote: string,
  ingredients: RecipeIngredient[],
  steps: string[],
  makeAhead: string,
  equipment: string[],
  dietary: string[],
  scalingNote: string,
): Recipe {
  return {
    dishId,
    yield: yieldText,
    activeMinutes,
    totalMinutes,
    difficulty,
    headnote,
    ingredients,
    steps,
    makeAhead,
    equipment,
    dietary,
    scalingNote,
  };
}

export const RECIPES: Record<string, Recipe> = {
  "citrus-olives": r(
    "citrus-olives",
    "Serves 8 as a welcome",
    15,
    15,
    "easy",
    "A room-temperature bowl that sets a bright, salty tone before anyone sits. No heat, no last look.",
    [
      { item: "Mixed olives, drained", amount: "2½ cups", aisle: "pantry" },
      { item: "Orange", amount: "1, zest + 2 strips peel", aisle: "produce" },
      { item: "Lemon", amount: "1, zest + juice of ½", aisle: "produce" },
      { item: "Extra-virgin olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Garlic", amount: "1 clove, smashed", aisle: "produce" },
      { item: "Rosemary or thyme", amount: "2 sprigs", aisle: "produce" },
      { item: "Fennel seed or crushed red pepper", amount: "½ tsp", aisle: "spices" },
    ],
    [
      "Pat olives dry so the oil clings.",
      "Stir with zest, peel, lemon juice, oil, garlic, herbs, and spice.",
      "Rest at least 2 hours at room temperature, or refrigerate up to 5 days.",
      "Bring to room temp and lift out the garlic before serving.",
    ],
    "Fully make-ahead. Flavor deepens overnight.",
    ["Mixing bowl"],
    ["vegetarian", "vegan", "gluten_free"],
    "1½ cups olives per 6 guests as a welcome.",
  ),
  "spiced-nuts": r(
    "spiced-nuts",
    "Serves 8 as a welcome",
    10,
    25,
    "easy",
    "One sheet pan, one warm bowl. Hold in a low oven or serve room-temp after cooling.",
    [
      { item: "Mixed raw nuts", amount: "3 cups", aisle: "pantry" },
      { item: "Olive oil or melted butter", amount: "1½ tbsp", aisle: "pantry" },
      { item: "Maple syrup or honey", amount: "1 tbsp", aisle: "pantry" },
      { item: "Smoked paprika", amount: "1 tsp", aisle: "spices" },
      { item: "Cumin", amount: "½ tsp", aisle: "spices" },
      { item: "Cayenne", amount: "pinch", aisle: "spices" },
      { item: "Kosher salt", amount: "1 tsp", aisle: "spices" },
      { item: "Rosemary, chopped", amount: "1 tsp", aisle: "produce" },
    ],
    [
      "Heat oven to 325°F. Toss nuts with oil, syrup, spices, and salt.",
      "Spread in a single layer. Roast 12–16 minutes, stirring once, until fragrant.",
      "Toss with rosemary while hot. Cool on the pan.",
      "Store airtight up to 1 week. Rewarm 5 minutes at 300°F if you want them hot.",
    ],
    "Roast up to 5 days ahead. Finish warm in 8 minutes.",
    ["Sheet pan"],
    ["vegetarian", "gluten_free"],
    "About ⅓ cup nuts per guest as a welcome.",
  ),
  "pickled-veg-board": r(
    "pickled-veg-board",
    "Serves 8–10 as a welcome",
    25,
    145,
    "easy",
    "A self-serve board that frees the host completely. The brine is the only recipe.",
    [
      { item: "Carrots, radishes, cucumber, fennel", amount: "1½ lb mixed", aisle: "produce" },
      { item: "White wine or rice vinegar", amount: "1 cup", aisle: "pantry" },
      { item: "Water", amount: "1 cup", aisle: "other" },
      { item: "Sugar", amount: "2 tbsp", aisle: "pantry" },
      { item: "Kosher salt", amount: "1 tbsp", aisle: "spices" },
      { item: "Garlic", amount: "2 cloves", aisle: "produce" },
      { item: "Mustard seed or peppercorns", amount: "1 tsp", aisle: "spices" },
      { item: "Soft herbs, for serving", amount: "a handful", aisle: "produce" },
    ],
    [
      "Slice vegetables thin so they pickle in 2 hours.",
      "Simmer vinegar, water, sugar, and salt just until dissolved. Add garlic and spice.",
      "Pour hot brine over vegetables. Cool, then refrigerate at least 2 hours.",
      "Drain lightly and arrange on a board with herbs. Keep extra brine for leftovers.",
    ],
    "Pickle 1–3 days ahead. They keep a week.",
    ["Jar or container", "Small saucepan"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 3 oz pickled vegetables per guest.",
  ),
  "whipped-feta-honey": r(
    "whipped-feta-honey",
    "Serves 8 as a welcome",
    15,
    15,
    "easy",
    "Creamy, salty-sweet dip. The honey is the only last-minute heat.",
    [
      { item: "Block feta", amount: "8 oz", aisle: "dairy-eggs" },
      { item: "Greek yogurt or cream cheese", amount: "⅓ cup", aisle: "dairy-eggs" },
      { item: "Olive oil", amount: "2 tbsp + more to finish", aisle: "pantry" },
      { item: "Lemon zest", amount: "½ lemon", aisle: "produce" },
      { item: "Honey", amount: "3 tbsp", aisle: "pantry" },
      { item: "Chili flakes or hot honey", amount: "½ tsp", aisle: "spices" },
      { item: "Crudités or bread", amount: "to serve", aisle: "produce" },
    ],
    [
      "Blend feta, yogurt, oil, and zest until fluffy. Taste for salt — feta varies.",
      "Spoon into a shallow bowl. Chill up to 2 days.",
      "Warm honey with chili flakes 30 seconds. Swirl over the feta.",
      "Serve with bread or vegetables. Do not bake the dip.",
    ],
    "Whip 1 day ahead. Warm honey at service.",
    ["Food processor or blender"],
    ["vegetarian", "gluten_free"],
    "1 oz feta per guest as a welcome.",
  ),
  "lentil-walnut-pate": r(
    "lentil-walnut-pate",
    "Serves 10 as a welcome",
    25,
    50,
    "easy",
    "Earthy vegan spread that sits happily next to pickles and bread.",
    [
      { item: "Brown or green lentils", amount: "1 cup dry", aisle: "pantry" },
      { item: "Walnuts", amount: "¾ cup", aisle: "pantry" },
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Shallot", amount: "1, chopped", aisle: "produce" },
      { item: "Garlic", amount: "2 cloves", aisle: "produce" },
      { item: "Thyme", amount: "1 tsp", aisle: "produce" },
      { item: "Soy sauce or tamari", amount: "1 tbsp", aisle: "pantry" },
      { item: "Lemon juice", amount: "1 tbsp", aisle: "produce" },
    ],
    [
      "Simmer lentils in salted water until just tender. Drain well.",
      "Toast walnuts 6 minutes at 350°F. Soften shallot and garlic in oil.",
      "Pulse everything with thyme, tamari, and lemon until spreadable, not baby food.",
      "Chill at least 2 hours. Serve with crackers, toast, or cucumbers.",
    ],
    "Fully make-ahead. Holds 4 days refrigerated.",
    ["Saucepan", "Food processor"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 2 tablespoons per guest.",
  ),
  "tomato-braised-chickpeas": r(
    "tomato-braised-chickpeas",
    "Serves 8 as an anchor",
    25,
    55,
    "moderate",
    "One-pot vegetarian centerpiece that holds on a back burner without collapsing.",
    [
      { item: "Cooked chickpeas", amount: "2 × 15-oz cans, drained", aisle: "pantry" },
      { item: "Crushed tomatoes", amount: "28 oz", aisle: "pantry" },
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Onion", amount: "1 large, sliced", aisle: "produce" },
      { item: "Garlic", amount: "4 cloves", aisle: "produce" },
      { item: "Smoked paprika", amount: "1 tsp", aisle: "spices" },
      { item: "Cumin", amount: "1 tsp", aisle: "spices" },
      { item: "Greens (kale or chard)", amount: "1 bunch", aisle: "produce" },
      { item: "Lemon", amount: "1", aisle: "produce" },
    ],
    [
      "Sweat onion in oil with salt until soft. Add garlic and spices 1 minute.",
      "Add tomatoes and a splash of water. Simmer 10 minutes.",
      "Stir in chickpeas. Simmer 20 minutes until the sauce is thick and glossy.",
      "Fold in chopped greens until wilted. Finish with lemon and olive oil.",
    ],
    "Braise a day ahead. Reheat gently and add greens at the end.",
    ["Dutch oven or wide pot"],
    ["vegetarian", "vegan", "gluten_free"],
    "About ¾ cup stew per guest as the anchor.",
  ),
  "sheet-pan-lemon-chicken": r(
    "sheet-pan-lemon-chicken",
    "Serves 8 as an anchor",
    20,
    70,
    "easy",
    "Hands-off roasted chicken with citrus. The oven does the hosting.",
    [
      { item: "Bone-in, skin-on chicken thighs", amount: "4 lb", aisle: "protein" },
      { item: "Lemons", amount: "2, sliced + juiced", aisle: "produce" },
      { item: "Garlic", amount: "6 cloves, smashed", aisle: "produce" },
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Oregano or thyme", amount: "2 tsp", aisle: "spices" },
      { item: "Kosher salt and pepper", amount: "to taste", aisle: "spices" },
      { item: "Optional: small potatoes", amount: "1½ lb", aisle: "produce" },
    ],
    [
      "Heat oven to 425°F. Toss chicken with oil, lemon juice, garlic, herbs, salt, pepper.",
      "Arrange skin-up on a sheet pan with lemon slices (and potatoes if using).",
      "Roast 40–50 minutes until skin is bronze and juices run clear (175°F at the bone).",
      "Rest 8 minutes. Spoon pan juices over. Do not tent tightly or the skin steams.",
    ],
    "Season up to 12 hours ahead. Roast day-of.",
    ["Sheet pan"],
    ["gluten_free"],
    "One large thigh (or ½ lb) per guest.",
  ),
  "grilled-shrimp-skewers": r(
    "grilled-shrimp-skewers",
    "Serves 8 as an anchor",
    25,
    40,
    "moderate",
    "Fast, bright seafood for a patio or open house. Cook in batches; keep the first warm.",
    [
      { item: "Large shrimp, peeled", amount: "2½ lb", aisle: "protein" },
      { item: "Olive oil", amount: "¼ cup", aisle: "pantry" },
      { item: "Lemon", amount: "1, zest + juice", aisle: "produce" },
      { item: "Garlic", amount: "3 cloves, grated", aisle: "produce" },
      { item: "Parsley or cilantro", amount: "½ cup chopped", aisle: "produce" },
      { item: "Smoked paprika", amount: "1 tsp", aisle: "spices" },
      { item: "Wooden or metal skewers", amount: "16", aisle: "other" },
    ],
    [
      "Pat shrimp dry. Toss with half the oil, zest, garlic, paprika, salt.",
      "Thread 4–5 shrimp per skewer. Soak wood skewers 20 minutes if using.",
      "Grill or broil 2–3 minutes per side until just opaque.",
      "Stir remaining oil with lemon juice and herbs. Brush on after cooking.",
    ],
    "Marinate up to 4 hours. Cook at service — shrimp wait poorly.",
    ["Grill or broiler", "Skewers"],
    ["gluten_free"],
    "About 5 oz shrimp per guest as the anchor.",
  ),
  "braised-short-ribs": r(
    "braised-short-ribs",
    "Serves 8 as an anchor",
    35,
    220,
    "involved",
    "True make-ahead celebration beef. The fridge does the work; you only reheat.",
    [
      { item: "Bone-in short ribs", amount: "5 lb", aisle: "protein" },
      { item: "Onion, carrot, celery", amount: "1 each, chopped", aisle: "produce" },
      { item: "Tomato paste", amount: "2 tbsp", aisle: "pantry" },
      { item: "Dry red wine", amount: "1½ cups", aisle: "beverages" },
      { item: "Beef or chicken stock", amount: "2 cups", aisle: "pantry" },
      { item: "Garlic", amount: "4 cloves", aisle: "produce" },
      { item: "Thyme and bay", amount: "a few sprigs + 2 leaves", aisle: "produce" },
      { item: "Kosher salt and pepper", amount: "to taste", aisle: "spices" },
    ],
    [
      "Season ribs well. Brown in a Dutch oven in batches. Pour off excess fat.",
      "Sweat vegetables. Add tomato paste 2 minutes. Deglaze with wine.",
      "Return ribs. Add stock to come two-thirds up the meat, plus herbs.",
      "Cover and braise at 325°F 2½–3 hours until the bone slips.",
      "Chill overnight. Lift fat. Reheat covered 30–40 minutes at 325°F.",
    ],
    "Braise 1–2 days ahead. Reheat in its own sauce.",
    ["Dutch oven"],
    ["gluten_free"],
    "About 10 oz bone-in ribs per guest.",
  ),
  shakshuka: r(
    "shakshuka",
    "Serves 6–8 as an anchor",
    25,
    40,
    "moderate",
    "Tomato-pepper egg bake for brunch or a casual dinner. One skillet, flexible heat.",
    [
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Onion and red pepper", amount: "1 each, sliced", aisle: "produce" },
      { item: "Garlic", amount: "3 cloves", aisle: "produce" },
      { item: "Crushed tomatoes", amount: "28 oz", aisle: "pantry" },
      { item: "Cumin, paprika, chili flake", amount: "1 tsp each", aisle: "spices" },
      { item: "Eggs", amount: "8", aisle: "dairy-eggs" },
      { item: "Feta", amount: "4 oz", aisle: "dairy-eggs" },
      { item: "Cilantro or parsley", amount: "a handful", aisle: "produce" },
    ],
    [
      "Cook onion and pepper in oil until soft and sweet. Add garlic and spices.",
      "Add tomatoes. Simmer 12–15 minutes until the sauce can hold a well.",
      "Make wells, crack in eggs, crumble feta. Cover 6–8 minutes for set whites.",
      "Finish with herbs. Serve from the skillet with bread on the side.",
    ],
    "Sauce can be made a day ahead. Add eggs at service.",
    ["Wide skillet with lid"],
    ["vegetarian", "gluten_free"],
    "One egg plus sauce per guest; two eggs for a hungrier table.",
  ),
  "miso-glazed-salmon": r(
    "miso-glazed-salmon",
    "Serves 8 as an anchor",
    15,
    35,
    "easy",
    "Umami-rich, short oven time. The glaze is the only advance work.",
    [
      { item: "Salmon fillets", amount: "3 lb", aisle: "protein" },
      { item: "White miso", amount: "3 tbsp", aisle: "pantry" },
      { item: "Mirin or honey + water", amount: "2 tbsp", aisle: "pantry" },
      { item: "Soy sauce or tamari", amount: "1 tbsp", aisle: "pantry" },
      { item: "Rice vinegar", amount: "1 tsp", aisle: "pantry" },
      { item: "Sesame oil", amount: "1 tsp", aisle: "pantry" },
      { item: "Scallions and sesame seeds", amount: "to finish", aisle: "produce" },
    ],
    [
      "Stir miso, mirin, soy, vinegar, and sesame oil into a loose glaze.",
      "Pat salmon dry. Spread glaze on the flesh. Rest 15–30 minutes.",
      "Roast at 425°F 10–14 minutes until just opaque in the center.",
      "Broil 1 minute if you want blistered glaze. Finish with scallion.",
    ],
    "Glaze 2 days ahead. Fish is day-of only.",
    ["Sheet pan"],
    ["gluten_free"],
    "About 6 oz salmon per guest.",
  ),
  "porchetta-style-pork": r(
    "porchetta-style-pork",
    "Serves 10 as an anchor",
    30,
    180,
    "involved",
    "Herb-crusted, sliceable pork for family-style. Rest is part of the method.",
    [
      { item: "Boneless pork shoulder or loin", amount: "4–5 lb", aisle: "protein" },
      { item: "Garlic", amount: "6 cloves", aisle: "produce" },
      { item: "Fennel seed", amount: "1 tbsp, crushed", aisle: "spices" },
      { item: "Rosemary and sage", amount: "2 tbsp chopped", aisle: "produce" },
      { item: "Lemon zest", amount: "1 lemon", aisle: "produce" },
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Kosher salt and pepper", amount: "to taste", aisle: "spices" },
    ],
    [
      "Mash garlic, fennel, herbs, zest, oil, and plenty of salt into a paste.",
      "Score fat. Rub paste all over. Tie if using shoulder. Refrigerate overnight.",
      "Roast at 450°F 20 minutes, then 325°F until 145°F (loin) or 185°F (shoulder).",
      "Rest 20 minutes. Slice thin. Save juices for the table.",
    ],
    "Season the night before. Roast the morning of and hold warm.",
    ["Roasting pan", "Kitchen twine"],
    ["gluten_free"],
    "About 6–8 oz cooked pork per guest.",
  ),
  "mushroom-risotto": r(
    "mushroom-risotto",
    "Serves 6–8 as an anchor",
    40,
    50,
    "involved",
    "Creamy vegetarian main. Attention-heavy at the stove — only choose it when the host can stay put.",
    [
      { item: "Arborio or carnaroli rice", amount: "2 cups", aisle: "pantry" },
      { item: "Mixed mushrooms", amount: "1½ lb", aisle: "produce" },
      { item: "Shallot", amount: "2, minced", aisle: "produce" },
      { item: "Dry white wine", amount: "¾ cup", aisle: "beverages" },
      { item: "Warm vegetable stock", amount: "6 cups", aisle: "pantry" },
      { item: "Butter and Parmesan", amount: "3 tbsp + ¾ cup", aisle: "dairy-eggs" },
      { item: "Thyme", amount: "1 tsp", aisle: "produce" },
      { item: "Olive oil", amount: "2 tbsp", aisle: "pantry" },
    ],
    [
      "Brown mushrooms hard in oil; salt; set aside.",
      "Sweat shallot. Toast rice 2 minutes. Add wine; cook dry.",
      "Add warm stock a ladle at a time, stirring, 18–20 minutes.",
      "Fold in mushrooms, butter, cheese, thyme. Rest 2 minutes. Serve immediately.",
    ],
    "Mushrooms and stock ahead. Rice must be finished at service, or par-cook 12 minutes and finish later.",
    ["Wide saucepan"],
    ["vegetarian", "gluten_free"],
    "About 1 cup finished risotto per guest.",
  ),
  "bitter-greens-salad": r(
    "bitter-greens-salad",
    "Serves 8 as contrast",
    15,
    15,
    "easy",
    "Sharp counterpoint that cuts a rich anchor. Dress only when you walk to the table.",
    [
      { item: "Escarole, radicchio, or frisée", amount: "10 oz", aisle: "produce" },
      { item: "Lemon juice", amount: "2 tbsp", aisle: "produce" },
      { item: "Dijon mustard", amount: "1 tsp", aisle: "pantry" },
      { item: "Olive oil", amount: "¼ cup", aisle: "pantry" },
      { item: "Honey", amount: "½ tsp", aisle: "pantry" },
      { item: "Shaved Parmesan (optional)", amount: "1 oz", aisle: "deli" },
    ],
    [
      "Wash and dry greens thoroughly. Chill until service.",
      "Shake lemon, Dijon, honey, salt, and oil into a vinaigrette.",
      "Toss greens with just enough dressing to gloss. Add cheese if using.",
      "Do not dress early — bitter greens wilt and go sodden.",
    ],
    "Wash greens and mix vinaigrette up to 1 day ahead.",
    ["Salad spinner"],
    ["vegetarian", "vegan", "gluten_free"],
    "A generous handful of greens per guest.",
  ),
  "quick-pickles": r(
    "quick-pickles",
    "Serves 8 as contrast",
    15,
    75,
    "easy",
    "Crunchy, acidic, fully offline. Wakes up any rich plate.",
    [
      { item: "Cucumbers or radishes", amount: "1 lb, thin sliced", aisle: "produce" },
      { item: "Rice or white wine vinegar", amount: "¾ cup", aisle: "pantry" },
      { item: "Water", amount: "½ cup", aisle: "other" },
      { item: "Sugar", amount: "2 tbsp", aisle: "pantry" },
      { item: "Kosher salt", amount: "2 tsp", aisle: "spices" },
      { item: "Garlic or dill", amount: "optional", aisle: "produce" },
    ],
    [
      "Pack sliced vegetables into a jar.",
      "Warm vinegar, water, sugar, and salt until dissolved. Pour over.",
      "Cool, then refrigerate at least 1 hour.",
      "Drain just before the plate so they stay crisp.",
    ],
    "Pickle 1–4 days ahead.",
    ["Jar"],
    ["vegetarian", "vegan", "gluten_free"],
    "A small pile — 2 oz — per guest.",
  ),
  "charred-broccoli": r(
    "charred-broccoli",
    "Serves 8 as contrast",
    15,
    25,
    "easy",
    "High heat, short time, strong texture. Chili crisp does the seasoning.",
    [
      { item: "Broccoli crowns", amount: "2 lb", aisle: "produce" },
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Chili crisp or chili oil", amount: "2 tbsp", aisle: "pantry" },
      { item: "Lemon", amount: "1", aisle: "produce" },
      { item: "Kosher salt", amount: "to taste", aisle: "spices" },
    ],
    [
      "Heat oven to 450°F or preheat a grill.",
      "Toss broccoli with oil and salt. Spread with space — crowding steams.",
      "Roast or grill 12–16 minutes until charred at the edges.",
      "Toss with chili crisp and lemon. Serve hot or warm.",
    ],
    "Cut broccoli ahead. Char at service — it waits 15 minutes, not an hour.",
    ["Sheet pan or grill"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 4 oz broccoli per guest.",
  ),
  "fennel-citrus-salad": r(
    "fennel-citrus-salad",
    "Serves 8 as contrast",
    20,
    20,
    "easy",
    "Crisp, anise-bright salad for rich anchors. Slice ahead; dress late.",
    [
      { item: "Fennel bulbs", amount: "2 large", aisle: "produce" },
      { item: "Oranges or grapefruit", amount: "2", aisle: "produce" },
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Lemon juice", amount: "1 tbsp", aisle: "produce" },
      { item: "Fennel fronds or mint", amount: "a handful", aisle: "produce" },
      { item: "Flaky salt and pepper", amount: "to taste", aisle: "spices" },
    ],
    [
      "Halve fennel, core, and shave thin. Soak in ice water 10 minutes, then dry.",
      "Supreme or slice citrus; save the juice.",
      "Toss fennel with oil, lemon, citrus juice, salt.",
      "Fold in citrus and herbs at the table.",
    ],
    "Shaved fennel keeps 8 hours in water. Dress at service.",
    ["Sharp knife or mandoline"],
    ["vegetarian", "vegan", "gluten_free"],
    "About ½ fennel bulb per 2 guests.",
  ),
  "kimchi-slaw": r(
    "kimchi-slaw",
    "Serves 8 as contrast",
    15,
    15,
    "easy",
    "Fermented heat and crunch. Assemble day-of from a make-ahead base.",
    [
      { item: "Napa or green cabbage", amount: "½ small head", aisle: "produce" },
      { item: "Kimchi, chopped", amount: "1½ cups", aisle: "pantry" },
      { item: "Kimchi brine", amount: "2 tbsp", aisle: "pantry" },
      { item: "Rice vinegar", amount: "1 tbsp", aisle: "pantry" },
      { item: "Toasted sesame oil", amount: "1 tsp", aisle: "pantry" },
      { item: "Scallions", amount: "3", aisle: "produce" },
    ],
    [
      "Shred cabbage thin. Salt lightly and rest 10 minutes; squeeze dry if wet.",
      "Toss with chopped kimchi, brine, vinegar, and sesame oil.",
      "Fold in scallions. Taste — add brine, not more salt, first.",
      "Serve cold. It stays crisp about 4 hours.",
    ],
    "Shred cabbage a day ahead. Toss 1 hour before service.",
    ["Mixing bowl"],
    ["vegetarian", "vegan", "gluten_free"],
    "About ½ cup slaw per guest.",
  ),
  "grilled-halloumi": r(
    "grilled-halloumi",
    "Serves 8 as contrast",
    15,
    15,
    "easy",
    "Salty, squeaky cheese that adds protein contrast in minutes.",
    [
      { item: "Halloumi", amount: "14 oz", aisle: "dairy-eggs" },
      { item: "Olive oil", amount: "1 tbsp", aisle: "pantry" },
      { item: "Lemon", amount: "1", aisle: "produce" },
      { item: "Oregano or mint", amount: "1 tbsp", aisle: "produce" },
      { item: "Black pepper", amount: "to taste", aisle: "spices" },
    ],
    [
      "Pat halloumi dry and slice ⅓-inch thick. Brush lightly with oil.",
      "Grill or sear in a hot dry skillet 2 minutes per side until marked.",
      "Finish with lemon, herbs, and pepper. Serve immediately — it firms as it cools.",
    ],
    "Slice ahead. Cook at service.",
    ["Grill or skillet"],
    ["vegetarian", "gluten_free"],
    "About 1½ oz halloumi per guest as contrast.",
  ),
  "simple-green-salad": r(
    "simple-green-salad",
    "Serves 8 as relief",
    10,
    10,
    "easy",
    "Soft, mild green that never competes. Pure host freedom.",
    [
      { item: "Butter lettuce or little gems", amount: "2 heads", aisle: "produce" },
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "White wine vinegar or lemon", amount: "1 tbsp", aisle: "pantry" },
      { item: "Kosher salt", amount: "to taste", aisle: "spices" },
    ],
    [
      "Separate leaves. Wash and dry completely.",
      "Whisk oil, acid, and salt.",
      "Toss at the last moment with a light hand.",
    ],
    "Wash and dry greens the morning of. Dress at the table.",
    ["Salad spinner"],
    ["vegetarian", "vegan", "gluten_free"],
    "A small handful per guest — this is relief, not a course.",
  ),
  "herbed-rice": r(
    "herbed-rice",
    "Serves 8 as relief",
    10,
    30,
    "easy",
    "Neutral, absorbent grains that calm a loud plate. Holds and reheats cleanly.",
    [
      { item: "Long-grain rice or farro", amount: "2 cups dry", aisle: "pantry" },
      { item: "Water or light stock", amount: "as package directs", aisle: "pantry" },
      { item: "Olive oil or butter", amount: "2 tbsp", aisle: "pantry" },
      { item: "Parsley, dill, or chives", amount: "½ cup chopped", aisle: "produce" },
      { item: "Lemon zest", amount: "1 tsp", aisle: "produce" },
      { item: "Kosher salt", amount: "to taste", aisle: "spices" },
    ],
    [
      "Rinse rice. Cook in salted water until just tender. Rest 10 minutes, covered.",
      "Fluff with oil or butter.",
      "Fold in herbs and zest just before serving so they stay green.",
    ],
    "Cook up to 1 day ahead. Reheat with a splash of water, covered.",
    ["Saucepan with lid"],
    ["vegetarian", "vegan", "gluten_free"],
    "About ¾ cup cooked grains per guest.",
  ),
  "roasted-root-veg": r(
    "roasted-root-veg",
    "Serves 8 as relief",
    20,
    50,
    "easy",
    "Sweet, earthy, oven-friendly. Shares a rack with many anchors.",
    [
      { item: "Carrots, parsnips, potatoes, or beets", amount: "3 lb mixed", aisle: "produce" },
      { item: "Olive oil", amount: "3 tbsp", aisle: "pantry" },
      { item: "Garlic", amount: "4 cloves", aisle: "produce" },
      { item: "Thyme or rosemary", amount: "a few sprigs", aisle: "produce" },
      { item: "Kosher salt and pepper", amount: "to taste", aisle: "spices" },
    ],
    [
      "Heat oven to 425°F. Cut vegetables into even chunks.",
      "Toss with oil, salt, pepper, garlic, herbs.",
      "Roast 35–45 minutes, turning once, until browned and tender.",
      "Hold in a 200°F oven up to 40 minutes.",
    ],
    "Cut vegetables a day ahead. Roast morning-of or with the anchor.",
    ["Sheet pan"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 5 oz vegetables per guest.",
  ),
  "cucumber-yogurt": r(
    "cucumber-yogurt",
    "Serves 8 as relief",
    15,
    15,
    "easy",
    "Cool, dairy-bright relief for spice or smoke. Fully offline.",
    [
      { item: "Greek yogurt", amount: "2 cups", aisle: "dairy-eggs" },
      { item: "Cucumber", amount: "1 large, grated", aisle: "produce" },
      { item: "Garlic", amount: "1 small clove", aisle: "produce" },
      { item: "Lemon juice", amount: "1 tbsp", aisle: "produce" },
      { item: "Dill or mint", amount: "2 tbsp", aisle: "produce" },
      { item: "Olive oil", amount: "1 tbsp", aisle: "pantry" },
      { item: "Kosher salt", amount: "to taste", aisle: "spices" },
    ],
    [
      "Grate cucumber. Salt and squeeze dry in a towel.",
      "Stir into yogurt with grated garlic, lemon, herbs, oil, and salt.",
      "Chill at least 30 minutes. Taste again — cucumber waters down seasoning.",
    ],
    "Make up to 2 days ahead. Stir before serving.",
    ["Bowl", "Box grater"],
    ["vegetarian", "gluten_free"],
    "About ¼ cup sauce per guest.",
  ),
  "blistered-tomatoes": r(
    "blistered-tomatoes",
    "Serves 8 as relief",
    10,
    10,
    "easy",
    "Sweet-acidic burst. Five minutes in a skillet or on a sheet pan.",
    [
      { item: "Cherry tomatoes", amount: "2 pints", aisle: "produce" },
      { item: "Olive oil", amount: "2 tbsp", aisle: "pantry" },
      { item: "Garlic", amount: "2 cloves, sliced", aisle: "produce" },
      { item: "Kosher salt", amount: "to taste", aisle: "spices" },
      { item: "Basil or oregano", amount: "a few leaves", aisle: "produce" },
    ],
    [
      "Heat a wide skillet until very hot. Add oil, then tomatoes.",
      "Do not stir for 2 minutes. Shake. Add garlic.",
      "Cook until skins blister and some collapse. Salt. Tear in herbs.",
    ],
    "Day-of only. Holds 20 minutes warm.",
    ["Skillet or sheet pan"],
    ["vegetarian", "vegan", "gluten_free"],
    "A small spoonful — 4–5 tomatoes — per guest.",
  ),
  "stone-fruit-crumble": r(
    "stone-fruit-crumble",
    "Serves 8 as a finish",
    20,
    60,
    "easy",
    "Warm fruit under a toasty lid. Bakes earlier and holds.",
    [
      { item: "Ripe stone fruit (peach, plum, apricot)", amount: "2½ lb", aisle: "produce" },
      { item: "Sugar", amount: "⅓ cup + 2 tbsp", aisle: "pantry" },
      { item: "Lemon juice", amount: "1 tbsp", aisle: "produce" },
      { item: "Rolled oats", amount: "1 cup", aisle: "pantry" },
      { item: "Flour", amount: "½ cup", aisle: "pantry" },
      { item: "Butter, cold", amount: "6 tbsp", aisle: "dairy-eggs" },
      { item: "Cinnamon or cardamom", amount: "½ tsp", aisle: "spices" },
    ],
    [
      "Heat oven to 375°F. Toss sliced fruit with ⅓ cup sugar and lemon.",
      "Rub oats, flour, 2 tbsp sugar, spice, and butter into clumps.",
      "Pile fruit in a baking dish. Cover with crumble.",
      "Bake 35–40 minutes until bubbling and gold. Rest 15 minutes.",
    ],
    "Assemble morning-of. Bake 1 hour before service and hold warm.",
    ["Baking dish"],
    ["vegetarian"],
    "One 2-quart dish serves 8; double the dish, not the depth.",
  ),
  "chocolate-olive-oil-cake": r(
    "chocolate-olive-oil-cake",
    "Serves 10 as a finish",
    20,
    70,
    "moderate",
    "Dense, make-ahead cake. No frosting drama — powdered sugar or crème fraîche.",
    [
      { item: "Good cocoa powder", amount: "¾ cup", aisle: "spices" },
      { item: "All-purpose flour", amount: "1 cup", aisle: "pantry" },
      { item: "Sugar", amount: "1 cup", aisle: "pantry" },
      { item: "Baking soda", amount: "1 tsp", aisle: "spices" },
      { item: "Eggs", amount: "2", aisle: "dairy-eggs" },
      { item: "Olive oil", amount: "½ cup", aisle: "pantry" },
      { item: "Strong coffee or water", amount: "¾ cup", aisle: "beverages" },
      { item: "Vanilla and salt", amount: "1 tsp + ½ tsp", aisle: "spices" },
    ],
    [
      "Heat oven to 350°F. Oil a 9-inch pan and line the base.",
      "Whisk dry ingredients. Whisk eggs, oil, coffee, vanilla. Combine.",
      "Bake 35–40 minutes until a crumb clings, not wet batter.",
      "Cool in the pan. Serve at room temperature.",
    ],
    "Bake 1 day ahead. Wrap once cool. Do not refrigerate if you can help it.",
    ["9-inch cake pan"],
    ["vegetarian"],
    "Thin slices — this is rich. One cake for 10.",
  ),
  "citrus-posset": r(
    "citrus-posset",
    "Serves 8 as a finish",
    15,
    195,
    "easy",
    "Set cream with a sharp citrus top. Fully make-ahead and quietly elegant.",
    [
      { item: "Heavy cream", amount: "2 cups", aisle: "dairy-eggs" },
      { item: "Sugar", amount: "½ cup", aisle: "pantry" },
      { item: "Lemon and orange juice", amount: "6 tbsp total, strained", aisle: "produce" },
      { item: "Citrus zest", amount: "1 tsp", aisle: "produce" },
    ],
    [
      "Simmer cream and sugar 3 minutes — do not boil hard.",
      "Off heat, stir in juice and zest. It will look thin; it sets as it cools.",
      "Pour into 8 small glasses. Cool, then refrigerate at least 3 hours.",
      "Serve cold, optionally with a few berries.",
    ],
    "Make up to 2 days ahead. Keep covered so they do not pick up fridge smells.",
    ["Saucepan", "8 small glasses"],
    ["vegetarian", "gluten_free"],
    "About ⅓ cup per guest.",
  ),
  "affogato-bar": r(
    "affogato-bar",
    "Serves 8 as a finish",
    10,
    10,
    "easy",
    "Self-serve, temperature-contrast finish. Almost zero host work at service.",
    [
      { item: "Vanilla ice cream or gelato", amount: "1½ qt", aisle: "frozen" },
      { item: "Hot espresso or strong coffee", amount: "2 cups", aisle: "beverages" },
      { item: "Optional: chocolate shavings, amaretti, olive oil", amount: "to taste", aisle: "pantry" },
    ],
    [
      "Scoop ice cream into a chilled tub. Keep in the freezer until the last course.",
      "Brew coffee just before dessert.",
      "Set out scoops, hot coffee, and toppings. Guests assemble.",
      "Have a dairy-free scoop if the table needs it.",
    ],
    "Buy ice cream any time. Brew coffee at dessert.",
    ["Ice-cream scoop", "Kettle or espresso"],
    ["vegetarian", "gluten_free"],
    "Two small scoops per guest.",
  ),
  "honey-roasted-fruit": r(
    "honey-roasted-fruit",
    "Serves 8 as a finish",
    10,
    30,
    "easy",
    "Simple warm fruit. The oven can share with other dishes.",
    [
      { item: "Seasonal fruit (plums, pears, grapes, figs)", amount: "2 lb", aisle: "produce" },
      { item: "Honey", amount: "3 tbsp", aisle: "pantry" },
      { item: "Olive oil or butter", amount: "1 tbsp", aisle: "pantry" },
      { item: "Thyme or cinnamon", amount: "a pinch", aisle: "spices" },
      { item: "Optional: yogurt or crème fraîche", amount: "1 cup", aisle: "dairy-eggs" },
    ],
    [
      "Heat oven to 400°F. Halve or slice fruit.",
      "Toss with honey, fat, and spice. Roast 18–25 minutes until syrupy.",
      "Serve warm with a spoon of yogurt if you want cool contrast.",
    ],
    "Prep fruit morning-of. Roast during the main course.",
    ["Sheet pan"],
    ["vegetarian", "vegan", "gluten_free"],
    "About 4 oz fruit per guest.",
  ),
};

export function getRecipe(dishId: string): Recipe | undefined {
  return RECIPES[dishId];
}

export function recipesForIds(ids: string[]): Recipe[] {
  return ids.map((id) => RECIPES[id]).filter((r): r is Recipe => Boolean(r));
}

export const RECIPE_COUNT = Object.keys(RECIPES).length;
